// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"context"

	"ai-copilot-platform/ai-rpc/internal/logic/aireportservice"
	"ai-copilot-platform/ai-rpc/internal/svc"
	"ai-copilot-platform/ai-rpc/pb"
)

type AiReportServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiReportServiceServer
}

func NewAiReportServiceServer(svcCtx *svc.ServiceContext) *AiReportServiceServer {
	return &AiReportServiceServer{
		svcCtx: svcCtx,
	}
}

// 生成指定日期的 AI 安全日报。
func (s *AiReportServiceServer) GenerateDailyReport(ctx context.Context, in *pb.GenerateDailyReportReq) (*pb.DailyReportResp, error) {
	l := aireportservicelogic.NewGenerateDailyReportLogic(ctx, s.svcCtx)
	return l.GenerateDailyReport(in)
}

// 查询 AI 安全日报列表。
func (s *AiReportServiceServer) ListDailyReport(ctx context.Context, in *pb.ListDailyReportReq) (*pb.ListDailyReportResp, error) {
	l := aireportservicelogic.NewListDailyReportLogic(ctx, s.svcCtx)
	return l.ListDailyReport(in)
}

// 查询单份 AI 安全日报详情。
func (s *AiReportServiceServer) GetDailyReport(ctx context.Context, in *pb.GetDailyReportReq) (*pb.DailyReportResp, error) {
	l := aireportservicelogic.NewGetDailyReportLogic(ctx, s.svcCtx)
	return l.GetDailyReport(in)
}
