apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd                   ## 创建出来的名字叫etcd-0，如果replicas 是 3，则是etcd-0~3
  namespace: blade
spec:
  serviceName: etcd-headless   #依赖一个名字叫etcd-headless的 Headless Service一块用
  replicas: 1   
  selector:     # 选择器,用来认领Pod
    matchLabels: # 要管理下面template.labels中带有app=etcd标签的 Pod
      app: etcd  #实际项目就写app:

  template:    # 下面这一整块template.metadata.spec本质上就是一个Pod模板。StatefulSet 的设计是用同一个Pod模板，创建一组有序的 Pod，如果要部署mysql，再写一个statefulset
    metadata:
      labels:
        app: etcd    # 这就是一个pod    
    spec:
      containers:
        - name: etcd
          image: bitnami/etcd:3.5
          ports:
            - containerPort: 2379   # 客户端访问端口
              name: client  
            - containerPort: 2380   # 集群节点之间通信端口
              name: peer
          env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_NAME
              value: "etcd-0"
            - name: ETCD_ADVERTISE_CLIENT_URLS             # 我的客户端访问地址是下面的
              value: "http://etcd-0.etcd-headless.blade.svc.cluster.local:2379"
            - name: ETCD_LISTEN_CLIENT_URLS
              value: "http://0.0.0.0:2379"
            - name: ETCD_LISTEN_PEER_URLS
              value: "http://0.0.0.0:2380"
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: "http://etcd-0.etcd-headless.blade.svc.cluster.local:2380"
            - name: ETCD_INITIAL_CLUSTER
              value: "etcd-0=http://etcd-0.etcd-headless.blade.svc.cluster.local:2380"
            - name: ETCD_DATA_DIR    # 数据目录
              value: "/bitnami/etcd/data"
          volumeMounts:             # 容器内路径/bitnami/etcd/data；实际后端存储:etcd-data这个volume,etcd-data不是一个目录名,是一个volume卷的名字,在下面的volumeClaimTemplates配置
            - name: etcd-data
              mountPath: /bitnami/etcd/data
          livenessProbe:
            exec:
              command:
                - etcdctl
                - endpoint
                - health
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - etcdctl
                - endpoint
                - health
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:    # 跟docker挂载不一样，K8s里一般不是直接写宿主机目录，而是写：我需要一块 2Gi 的持久化存储，K8s 会帮忙找底层存储
    - metadata:
        name: etcd-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
