// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package aiwindmetadataservice

import (
	"context"

	"ai-copilot-platform/ai-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ListWindDeviceReq   = pb.ListWindDeviceReq
	ListWindDeviceResp  = pb.ListWindDeviceResp
	ListWindFarmReq     = pb.ListWindFarmReq
	ListWindFarmResp    = pb.ListWindFarmResp
	ListWindTurbineReq  = pb.ListWindTurbineReq
	ListWindTurbineResp = pb.ListWindTurbineResp

	AiWindMetadataService interface {
		ListFarms(ctx context.Context, in *ListWindFarmReq, opts ...grpc.CallOption) (*ListWindFarmResp, error)
		ListTurbines(ctx context.Context, in *ListWindTurbineReq, opts ...grpc.CallOption) (*ListWindTurbineResp, error)
		ListDevices(ctx context.Context, in *ListWindDeviceReq, opts ...grpc.CallOption) (*ListWindDeviceResp, error)
	}

	defaultAiWindMetadataService struct {
		cli zrpc.Client
	}
)

func NewAiWindMetadataService(cli zrpc.Client) AiWindMetadataService {
	return &defaultAiWindMetadataService{
		cli: cli,
	}
}

func (m *defaultAiWindMetadataService) ListFarms(ctx context.Context, in *ListWindFarmReq, opts ...grpc.CallOption) (*ListWindFarmResp, error) {
	client := pb.NewAiWindMetadataServiceClient(m.cli.Conn())
	return client.ListFarms(ctx, in, opts...)
}

func (m *defaultAiWindMetadataService) ListTurbines(ctx context.Context, in *ListWindTurbineReq, opts ...grpc.CallOption) (*ListWindTurbineResp, error) {
	client := pb.NewAiWindMetadataServiceClient(m.cli.Conn())
	return client.ListTurbines(ctx, in, opts...)
}

func (m *defaultAiWindMetadataService) ListDevices(ctx context.Context, in *ListWindDeviceReq, opts ...grpc.CallOption) (*ListWindDeviceResp, error) {
	client := pb.NewAiWindMetadataServiceClient(m.cli.Conn())
	return client.ListDevices(ctx, in, opts...)
}
