// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package aisecurityservice

import (
	"context"

	"ai-copilot-platform/ai-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AnalyzeSecurityEventsReq     = pb.AnalyzeSecurityEventsReq
	AnalyzeSecurityEventsResp    = pb.AnalyzeSecurityEventsResp
	Empty                        = pb.Empty
	ListSecurityAlertsReq        = pb.ListSecurityAlertsReq
	ListSecurityAlertsResp       = pb.ListSecurityAlertsResp
	ListSecurityEventsReq        = pb.ListSecurityEventsReq
	ListSecurityEventsResp       = pb.ListSecurityEventsResp
	SearchSecurityLogsReq        = pb.SearchSecurityLogsReq
	SecurityLogSearchResp        = pb.SecurityLogSearchResp
	UpdateSecurityAlertStatusReq = pb.UpdateSecurityAlertStatusReq

	AiSecurityService interface {
		// 检索 SSH 原始日志。
		SearchSecurityLogs(ctx context.Context, in *SearchSecurityLogsReq, opts ...grpc.CallOption) (*SecurityLogSearchResp, error)
		// 分析原始日志并生成结构化安全事件和告警摘要。
		AnalyzeSecurityEvents(ctx context.Context, in *AnalyzeSecurityEventsReq, opts ...grpc.CallOption) (*AnalyzeSecurityEventsResp, error)
		// 查询结构化安全事件列表。
		ListSecurityEvents(ctx context.Context, in *ListSecurityEventsReq, opts ...grpc.CallOption) (*ListSecurityEventsResp, error)
		// 查询安全告警列表。
		ListSecurityAlerts(ctx context.Context, in *ListSecurityAlertsReq, opts ...grpc.CallOption) (*ListSecurityAlertsResp, error)
		// 更新安全告警处理状态。
		UpdateSecurityAlertStatus(ctx context.Context, in *UpdateSecurityAlertStatusReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultAiSecurityService struct {
		cli zrpc.Client
	}
)

func NewAiSecurityService(cli zrpc.Client) AiSecurityService {
	return &defaultAiSecurityService{
		cli: cli,
	}
}

// 检索 SSH 原始日志。
func (m *defaultAiSecurityService) SearchSecurityLogs(ctx context.Context, in *SearchSecurityLogsReq, opts ...grpc.CallOption) (*SecurityLogSearchResp, error) {
	client := pb.NewAiSecurityServiceClient(m.cli.Conn())
	return client.SearchSecurityLogs(ctx, in, opts...)
}

// 分析原始日志并生成结构化安全事件和告警摘要。
func (m *defaultAiSecurityService) AnalyzeSecurityEvents(ctx context.Context, in *AnalyzeSecurityEventsReq, opts ...grpc.CallOption) (*AnalyzeSecurityEventsResp, error) {
	client := pb.NewAiSecurityServiceClient(m.cli.Conn())
	return client.AnalyzeSecurityEvents(ctx, in, opts...)
}

// 查询结构化安全事件列表。
func (m *defaultAiSecurityService) ListSecurityEvents(ctx context.Context, in *ListSecurityEventsReq, opts ...grpc.CallOption) (*ListSecurityEventsResp, error) {
	client := pb.NewAiSecurityServiceClient(m.cli.Conn())
	return client.ListSecurityEvents(ctx, in, opts...)
}

// 查询安全告警列表。
func (m *defaultAiSecurityService) ListSecurityAlerts(ctx context.Context, in *ListSecurityAlertsReq, opts ...grpc.CallOption) (*ListSecurityAlertsResp, error) {
	client := pb.NewAiSecurityServiceClient(m.cli.Conn())
	return client.ListSecurityAlerts(ctx, in, opts...)
}

// 更新安全告警处理状态。
func (m *defaultAiSecurityService) UpdateSecurityAlertStatus(ctx context.Context, in *UpdateSecurityAlertStatusReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAiSecurityServiceClient(m.cli.Conn())
	return client.UpdateSecurityAlertStatus(ctx, in, opts...)
}
