// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"context"

	"ai-copilot-platform/ai-rpc/internal/logic/aiwindtimeseriesservice"
	"ai-copilot-platform/ai-rpc/internal/svc"
	"ai-copilot-platform/ai-rpc/pb"
)

type AiWindTimeseriesServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiWindTimeseriesServiceServer
}

func NewAiWindTimeseriesServiceServer(svcCtx *svc.ServiceContext) *AiWindTimeseriesServiceServer {
	return &AiWindTimeseriesServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AiWindTimeseriesServiceServer) QueryTimeseries(ctx context.Context, in *pb.WindTimeseriesQueryReq) (*pb.WindTimeseriesQueryResp, error) {
	l := aiwindtimeseriesservicelogic.NewQueryTimeseriesLogic(ctx, s.svcCtx)
	return l.QueryTimeseries(in)
}

func (s *AiWindTimeseriesServiceServer) CompareTrend(ctx context.Context, in *pb.WindTrendCompareReq) (*pb.WindTrendCompareResp, error) {
	l := aiwindtimeseriesservicelogic.NewCompareTrendLogic(ctx, s.svcCtx)
	return l.CompareTrend(in)
}
