// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: pb/ai.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiStatusService_Health_FullMethodName = "/ai.AiStatusService/Health"
)

// AiStatusServiceClient is the client API for AiStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI 状态服务，负责检查 Go AI RPC 与 Python AI Engine 的可用性。
type AiStatusServiceClient interface {
	// 检查 AI 引擎健康状态。
	Health(ctx context.Context, in *HealthReq, opts ...grpc.CallOption) (*HealthResp, error)
}

type aiStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiStatusServiceClient(cc grpc.ClientConnInterface) AiStatusServiceClient {
	return &aiStatusServiceClient{cc}
}

func (c *aiStatusServiceClient) Health(ctx context.Context, in *HealthReq, opts ...grpc.CallOption) (*HealthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResp)
	err := c.cc.Invoke(ctx, AiStatusService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiStatusServiceServer is the server API for AiStatusService service.
// All implementations must embed UnimplementedAiStatusServiceServer
// for forward compatibility.
//
// AI 状态服务，负责检查 Go AI RPC 与 Python AI Engine 的可用性。
type AiStatusServiceServer interface {
	// 检查 AI 引擎健康状态。
	Health(context.Context, *HealthReq) (*HealthResp, error)
	mustEmbedUnimplementedAiStatusServiceServer()
}

// UnimplementedAiStatusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiStatusServiceServer struct{}

func (UnimplementedAiStatusServiceServer) Health(context.Context, *HealthReq) (*HealthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAiStatusServiceServer) mustEmbedUnimplementedAiStatusServiceServer() {}
func (UnimplementedAiStatusServiceServer) testEmbeddedByValue()                         {}

// UnsafeAiStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiStatusServiceServer will
// result in compilation errors.
type UnsafeAiStatusServiceServer interface {
	mustEmbedUnimplementedAiStatusServiceServer()
}

func RegisterAiStatusServiceServer(s grpc.ServiceRegistrar, srv AiStatusServiceServer) {
	// If the following call pancis, it indicates UnimplementedAiStatusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiStatusService_ServiceDesc, srv)
}

func _AiStatusService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiStatusServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiStatusService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiStatusServiceServer).Health(ctx, req.(*HealthReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AiStatusService_ServiceDesc is the grpc.ServiceDesc for AiStatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiStatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AiStatusService",
	HandlerType: (*AiStatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _AiStatusService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/ai.proto",
}

const (
	AiKnowledgeService_CreateDomain_FullMethodName         = "/ai.AiKnowledgeService/CreateDomain"
	AiKnowledgeService_UpdateDomain_FullMethodName         = "/ai.AiKnowledgeService/UpdateDomain"
	AiKnowledgeService_DeleteDomain_FullMethodName         = "/ai.AiKnowledgeService/DeleteDomain"
	AiKnowledgeService_ListDomain_FullMethodName           = "/ai.AiKnowledgeService/ListDomain"
	AiKnowledgeService_CreateKnowledgeBase_FullMethodName  = "/ai.AiKnowledgeService/CreateKnowledgeBase"
	AiKnowledgeService_UpdateKnowledgeBase_FullMethodName  = "/ai.AiKnowledgeService/UpdateKnowledgeBase"
	AiKnowledgeService_DeleteKnowledgeBase_FullMethodName  = "/ai.AiKnowledgeService/DeleteKnowledgeBase"
	AiKnowledgeService_GetKnowledgeBase_FullMethodName     = "/ai.AiKnowledgeService/GetKnowledgeBase"
	AiKnowledgeService_ListKnowledgeBase_FullMethodName    = "/ai.AiKnowledgeService/ListKnowledgeBase"
	AiKnowledgeService_ListKbMember_FullMethodName         = "/ai.AiKnowledgeService/ListKbMember"
	AiKnowledgeService_AddKbMember_FullMethodName          = "/ai.AiKnowledgeService/AddKbMember"
	AiKnowledgeService_UpdateKbMember_FullMethodName       = "/ai.AiKnowledgeService/UpdateKbMember"
	AiKnowledgeService_RemoveKbMember_FullMethodName       = "/ai.AiKnowledgeService/RemoveKbMember"
	AiKnowledgeService_IngestDocument_FullMethodName       = "/ai.AiKnowledgeService/IngestDocument"
	AiKnowledgeService_ListDocument_FullMethodName         = "/ai.AiKnowledgeService/ListDocument"
	AiKnowledgeService_GetDocument_FullMethodName          = "/ai.AiKnowledgeService/GetDocument"
	AiKnowledgeService_DeleteDocument_FullMethodName       = "/ai.AiKnowledgeService/DeleteDocument"
	AiKnowledgeService_RebuildDocumentIndex_FullMethodName = "/ai.AiKnowledgeService/RebuildDocumentIndex"
	AiKnowledgeService_SearchKnowledge_FullMethodName      = "/ai.AiKnowledgeService/SearchKnowledge"
)

// AiKnowledgeServiceClient is the client API for AiKnowledgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI 知识库服务，负责领域、知识库、成员、文档入库和检索能力。
type AiKnowledgeServiceClient interface {
	// 创建公共知识库领域。
	CreateDomain(ctx context.Context, in *CreateDomainReq, opts ...grpc.CallOption) (*CreateDomainResp, error)
	// 更新公共知识库领域基础信息。
	UpdateDomain(ctx context.Context, in *UpdateDomainReq, opts ...grpc.CallOption) (*Empty, error)
	// 删除公共知识库领域。
	DeleteDomain(ctx context.Context, in *DeleteDomainReq, opts ...grpc.CallOption) (*Empty, error)
	// 查询公共知识库领域列表。
	ListDomain(ctx context.Context, in *ListDomainReq, opts ...grpc.CallOption) (*ListDomainResp, error)
	// 创建个人或公共知识库。
	CreateKnowledgeBase(ctx context.Context, in *CreateKnowledgeBaseReq, opts ...grpc.CallOption) (*CreateKnowledgeBaseResp, error)
	// 更新知识库名称、描述、领域、可见性或状态。
	UpdateKnowledgeBase(ctx context.Context, in *UpdateKnowledgeBaseReq, opts ...grpc.CallOption) (*Empty, error)
	// 删除知识库，并由实现层清理关联文档和索引。
	DeleteKnowledgeBase(ctx context.Context, in *DeleteKnowledgeBaseReq, opts ...grpc.CallOption) (*Empty, error)
	// 查询知识库详情。
	GetKnowledgeBase(ctx context.Context, in *GetKnowledgeBaseReq, opts ...grpc.CallOption) (*KnowledgeBaseItem, error)
	// 查询当前用户可访问的知识库列表。
	ListKnowledgeBase(ctx context.Context, in *ListKnowledgeBaseReq, opts ...grpc.CallOption) (*ListKnowledgeBaseResp, error)
	// 查询公共知识库成员列表。
	ListKbMember(ctx context.Context, in *ListKbMemberReq, opts ...grpc.CallOption) (*ListKbMemberResp, error)
	// 添加公共知识库成员并授予角色。
	AddKbMember(ctx context.Context, in *AddKbMemberReq, opts ...grpc.CallOption) (*Empty, error)
	// 更新公共知识库成员角色。
	UpdateKbMember(ctx context.Context, in *UpdateKbMemberReq, opts ...grpc.CallOption) (*Empty, error)
	// 移除公共知识库成员。
	RemoveKbMember(ctx context.Context, in *RemoveKbMemberReq, opts ...grpc.CallOption) (*Empty, error)
	// 将文档写入知识库并触发解析、分块、向量化和索引。
	IngestDocument(ctx context.Context, in *IngestDocumentReq, opts ...grpc.CallOption) (*TaskResp, error)
	// 查询知识库文档列表。
	ListDocument(ctx context.Context, in *ListDocumentReq, opts ...grpc.CallOption) (*ListDocumentResp, error)
	// 查询文档元数据和入库状态。
	GetDocument(ctx context.Context, in *GetDocumentReq, opts ...grpc.CallOption) (*DocumentItem, error)
	// 删除知识库文档，并由实现层清理 chunk、向量和 ES 索引。
	DeleteDocument(ctx context.Context, in *DeleteDocumentReq, opts ...grpc.CallOption) (*Empty, error)
	// 重新构建指定文档的向量和全文索引。
	RebuildDocumentIndex(ctx context.Context, in *RebuildDocumentIndexReq, opts ...grpc.CallOption) (*TaskResp, error)
	// 执行知识库检索，支持 quick/deep 模式和不同检索范围。
	SearchKnowledge(ctx context.Context, in *SearchKnowledgeReq, opts ...grpc.CallOption) (*SearchKnowledgeResp, error)
}

type aiKnowledgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiKnowledgeServiceClient(cc grpc.ClientConnInterface) AiKnowledgeServiceClient {
	return &aiKnowledgeServiceClient{cc}
}

func (c *aiKnowledgeServiceClient) CreateDomain(ctx context.Context, in *CreateDomainReq, opts ...grpc.CallOption) (*CreateDomainResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDomainResp)
	err := c.cc.Invoke(ctx, AiKnowledgeService_CreateDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) UpdateDomain(ctx context.Context, in *UpdateDomainReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AiKnowledgeService_UpdateDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) DeleteDomain(ctx context.Context, in *DeleteDomainReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AiKnowledgeService_DeleteDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) ListDomain(ctx context.Context, in *ListDomainReq, opts ...grpc.CallOption) (*ListDomainResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDomainResp)
	err := c.cc.Invoke(ctx, AiKnowledgeService_ListDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) CreateKnowledgeBase(ctx context.Context, in *CreateKnowledgeBaseReq, opts ...grpc.CallOption) (*CreateKnowledgeBaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKnowledgeBaseResp)
	err := c.cc.Invoke(ctx, AiKnowledgeService_CreateKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) UpdateKnowledgeBase(ctx context.Context, in *UpdateKnowledgeBaseReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AiKnowledgeService_UpdateKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) DeleteKnowledgeBase(ctx context.Context, in *DeleteKnowledgeBaseReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AiKnowledgeService_DeleteKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) GetKnowledgeBase(ctx context.Context, in *GetKnowledgeBaseReq, opts ...grpc.CallOption) (*KnowledgeBaseItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeBaseItem)
	err := c.cc.Invoke(ctx, AiKnowledgeService_GetKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) ListKnowledgeBase(ctx context.Context, in *ListKnowledgeBaseReq, opts ...grpc.CallOption) (*ListKnowledgeBaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKnowledgeBaseResp)
	err := c.cc.Invoke(ctx, AiKnowledgeService_ListKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) ListKbMember(ctx context.Context, in *ListKbMemberReq, opts ...grpc.CallOption) (*ListKbMemberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKbMemberResp)
	err := c.cc.Invoke(ctx, AiKnowledgeService_ListKbMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) AddKbMember(ctx context.Context, in *AddKbMemberReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AiKnowledgeService_AddKbMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) UpdateKbMember(ctx context.Context, in *UpdateKbMemberReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AiKnowledgeService_UpdateKbMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) RemoveKbMember(ctx context.Context, in *RemoveKbMemberReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AiKnowledgeService_RemoveKbMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) IngestDocument(ctx context.Context, in *IngestDocumentReq, opts ...grpc.CallOption) (*TaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResp)
	err := c.cc.Invoke(ctx, AiKnowledgeService_IngestDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) ListDocument(ctx context.Context, in *ListDocumentReq, opts ...grpc.CallOption) (*ListDocumentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentResp)
	err := c.cc.Invoke(ctx, AiKnowledgeService_ListDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) GetDocument(ctx context.Context, in *GetDocumentReq, opts ...grpc.CallOption) (*DocumentItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentItem)
	err := c.cc.Invoke(ctx, AiKnowledgeService_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) DeleteDocument(ctx context.Context, in *DeleteDocumentReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AiKnowledgeService_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) RebuildDocumentIndex(ctx context.Context, in *RebuildDocumentIndexReq, opts ...grpc.CallOption) (*TaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResp)
	err := c.cc.Invoke(ctx, AiKnowledgeService_RebuildDocumentIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiKnowledgeServiceClient) SearchKnowledge(ctx context.Context, in *SearchKnowledgeReq, opts ...grpc.CallOption) (*SearchKnowledgeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchKnowledgeResp)
	err := c.cc.Invoke(ctx, AiKnowledgeService_SearchKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiKnowledgeServiceServer is the server API for AiKnowledgeService service.
// All implementations must embed UnimplementedAiKnowledgeServiceServer
// for forward compatibility.
//
// AI 知识库服务，负责领域、知识库、成员、文档入库和检索能力。
type AiKnowledgeServiceServer interface {
	// 创建公共知识库领域。
	CreateDomain(context.Context, *CreateDomainReq) (*CreateDomainResp, error)
	// 更新公共知识库领域基础信息。
	UpdateDomain(context.Context, *UpdateDomainReq) (*Empty, error)
	// 删除公共知识库领域。
	DeleteDomain(context.Context, *DeleteDomainReq) (*Empty, error)
	// 查询公共知识库领域列表。
	ListDomain(context.Context, *ListDomainReq) (*ListDomainResp, error)
	// 创建个人或公共知识库。
	CreateKnowledgeBase(context.Context, *CreateKnowledgeBaseReq) (*CreateKnowledgeBaseResp, error)
	// 更新知识库名称、描述、领域、可见性或状态。
	UpdateKnowledgeBase(context.Context, *UpdateKnowledgeBaseReq) (*Empty, error)
	// 删除知识库，并由实现层清理关联文档和索引。
	DeleteKnowledgeBase(context.Context, *DeleteKnowledgeBaseReq) (*Empty, error)
	// 查询知识库详情。
	GetKnowledgeBase(context.Context, *GetKnowledgeBaseReq) (*KnowledgeBaseItem, error)
	// 查询当前用户可访问的知识库列表。
	ListKnowledgeBase(context.Context, *ListKnowledgeBaseReq) (*ListKnowledgeBaseResp, error)
	// 查询公共知识库成员列表。
	ListKbMember(context.Context, *ListKbMemberReq) (*ListKbMemberResp, error)
	// 添加公共知识库成员并授予角色。
	AddKbMember(context.Context, *AddKbMemberReq) (*Empty, error)
	// 更新公共知识库成员角色。
	UpdateKbMember(context.Context, *UpdateKbMemberReq) (*Empty, error)
	// 移除公共知识库成员。
	RemoveKbMember(context.Context, *RemoveKbMemberReq) (*Empty, error)
	// 将文档写入知识库并触发解析、分块、向量化和索引。
	IngestDocument(context.Context, *IngestDocumentReq) (*TaskResp, error)
	// 查询知识库文档列表。
	ListDocument(context.Context, *ListDocumentReq) (*ListDocumentResp, error)
	// 查询文档元数据和入库状态。
	GetDocument(context.Context, *GetDocumentReq) (*DocumentItem, error)
	// 删除知识库文档，并由实现层清理 chunk、向量和 ES 索引。
	DeleteDocument(context.Context, *DeleteDocumentReq) (*Empty, error)
	// 重新构建指定文档的向量和全文索引。
	RebuildDocumentIndex(context.Context, *RebuildDocumentIndexReq) (*TaskResp, error)
	// 执行知识库检索，支持 quick/deep 模式和不同检索范围。
	SearchKnowledge(context.Context, *SearchKnowledgeReq) (*SearchKnowledgeResp, error)
	mustEmbedUnimplementedAiKnowledgeServiceServer()
}

// UnimplementedAiKnowledgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiKnowledgeServiceServer struct{}

func (UnimplementedAiKnowledgeServiceServer) CreateDomain(context.Context, *CreateDomainReq) (*CreateDomainResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDomain not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) UpdateDomain(context.Context, *UpdateDomainReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDomain not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) DeleteDomain(context.Context, *DeleteDomainReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDomain not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) ListDomain(context.Context, *ListDomainReq) (*ListDomainResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDomain not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) CreateKnowledgeBase(context.Context, *CreateKnowledgeBaseReq) (*CreateKnowledgeBaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKnowledgeBase not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) UpdateKnowledgeBase(context.Context, *UpdateKnowledgeBaseReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKnowledgeBase not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) DeleteKnowledgeBase(context.Context, *DeleteKnowledgeBaseReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKnowledgeBase not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) GetKnowledgeBase(context.Context, *GetKnowledgeBaseReq) (*KnowledgeBaseItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKnowledgeBase not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) ListKnowledgeBase(context.Context, *ListKnowledgeBaseReq) (*ListKnowledgeBaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKnowledgeBase not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) ListKbMember(context.Context, *ListKbMemberReq) (*ListKbMemberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKbMember not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) AddKbMember(context.Context, *AddKbMemberReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddKbMember not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) UpdateKbMember(context.Context, *UpdateKbMemberReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKbMember not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) RemoveKbMember(context.Context, *RemoveKbMemberReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveKbMember not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) IngestDocument(context.Context, *IngestDocumentReq) (*TaskResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestDocument not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) ListDocument(context.Context, *ListDocumentReq) (*ListDocumentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocument not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) GetDocument(context.Context, *GetDocumentReq) (*DocumentItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) DeleteDocument(context.Context, *DeleteDocumentReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) RebuildDocumentIndex(context.Context, *RebuildDocumentIndexReq) (*TaskResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebuildDocumentIndex not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) SearchKnowledge(context.Context, *SearchKnowledgeReq) (*SearchKnowledgeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchKnowledge not implemented")
}
func (UnimplementedAiKnowledgeServiceServer) mustEmbedUnimplementedAiKnowledgeServiceServer() {}
func (UnimplementedAiKnowledgeServiceServer) testEmbeddedByValue()                            {}

// UnsafeAiKnowledgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiKnowledgeServiceServer will
// result in compilation errors.
type UnsafeAiKnowledgeServiceServer interface {
	mustEmbedUnimplementedAiKnowledgeServiceServer()
}

func RegisterAiKnowledgeServiceServer(s grpc.ServiceRegistrar, srv AiKnowledgeServiceServer) {
	// If the following call pancis, it indicates UnimplementedAiKnowledgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiKnowledgeService_ServiceDesc, srv)
}

func _AiKnowledgeService_CreateDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDomainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).CreateDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_CreateDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).CreateDomain(ctx, req.(*CreateDomainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_UpdateDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDomainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).UpdateDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_UpdateDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).UpdateDomain(ctx, req.(*UpdateDomainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_DeleteDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDomainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).DeleteDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_DeleteDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).DeleteDomain(ctx, req.(*DeleteDomainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_ListDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDomainReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).ListDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_ListDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).ListDomain(ctx, req.(*ListDomainReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_CreateKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKnowledgeBaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).CreateKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_CreateKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).CreateKnowledgeBase(ctx, req.(*CreateKnowledgeBaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_UpdateKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKnowledgeBaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).UpdateKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_UpdateKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).UpdateKnowledgeBase(ctx, req.(*UpdateKnowledgeBaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_DeleteKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKnowledgeBaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).DeleteKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_DeleteKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).DeleteKnowledgeBase(ctx, req.(*DeleteKnowledgeBaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_GetKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKnowledgeBaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).GetKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_GetKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).GetKnowledgeBase(ctx, req.(*GetKnowledgeBaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_ListKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKnowledgeBaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).ListKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_ListKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).ListKnowledgeBase(ctx, req.(*ListKnowledgeBaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_ListKbMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKbMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).ListKbMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_ListKbMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).ListKbMember(ctx, req.(*ListKbMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_AddKbMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddKbMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).AddKbMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_AddKbMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).AddKbMember(ctx, req.(*AddKbMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_UpdateKbMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKbMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).UpdateKbMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_UpdateKbMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).UpdateKbMember(ctx, req.(*UpdateKbMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_RemoveKbMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveKbMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).RemoveKbMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_RemoveKbMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).RemoveKbMember(ctx, req.(*RemoveKbMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_IngestDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestDocumentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).IngestDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_IngestDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).IngestDocument(ctx, req.(*IngestDocumentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_ListDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).ListDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_ListDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).ListDocument(ctx, req.(*ListDocumentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).GetDocument(ctx, req.(*GetDocumentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).DeleteDocument(ctx, req.(*DeleteDocumentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_RebuildDocumentIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildDocumentIndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).RebuildDocumentIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_RebuildDocumentIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).RebuildDocumentIndex(ctx, req.(*RebuildDocumentIndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiKnowledgeService_SearchKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchKnowledgeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiKnowledgeServiceServer).SearchKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiKnowledgeService_SearchKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiKnowledgeServiceServer).SearchKnowledge(ctx, req.(*SearchKnowledgeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AiKnowledgeService_ServiceDesc is the grpc.ServiceDesc for AiKnowledgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiKnowledgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AiKnowledgeService",
	HandlerType: (*AiKnowledgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDomain",
			Handler:    _AiKnowledgeService_CreateDomain_Handler,
		},
		{
			MethodName: "UpdateDomain",
			Handler:    _AiKnowledgeService_UpdateDomain_Handler,
		},
		{
			MethodName: "DeleteDomain",
			Handler:    _AiKnowledgeService_DeleteDomain_Handler,
		},
		{
			MethodName: "ListDomain",
			Handler:    _AiKnowledgeService_ListDomain_Handler,
		},
		{
			MethodName: "CreateKnowledgeBase",
			Handler:    _AiKnowledgeService_CreateKnowledgeBase_Handler,
		},
		{
			MethodName: "UpdateKnowledgeBase",
			Handler:    _AiKnowledgeService_UpdateKnowledgeBase_Handler,
		},
		{
			MethodName: "DeleteKnowledgeBase",
			Handler:    _AiKnowledgeService_DeleteKnowledgeBase_Handler,
		},
		{
			MethodName: "GetKnowledgeBase",
			Handler:    _AiKnowledgeService_GetKnowledgeBase_Handler,
		},
		{
			MethodName: "ListKnowledgeBase",
			Handler:    _AiKnowledgeService_ListKnowledgeBase_Handler,
		},
		{
			MethodName: "ListKbMember",
			Handler:    _AiKnowledgeService_ListKbMember_Handler,
		},
		{
			MethodName: "AddKbMember",
			Handler:    _AiKnowledgeService_AddKbMember_Handler,
		},
		{
			MethodName: "UpdateKbMember",
			Handler:    _AiKnowledgeService_UpdateKbMember_Handler,
		},
		{
			MethodName: "RemoveKbMember",
			Handler:    _AiKnowledgeService_RemoveKbMember_Handler,
		},
		{
			MethodName: "IngestDocument",
			Handler:    _AiKnowledgeService_IngestDocument_Handler,
		},
		{
			MethodName: "ListDocument",
			Handler:    _AiKnowledgeService_ListDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _AiKnowledgeService_GetDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _AiKnowledgeService_DeleteDocument_Handler,
		},
		{
			MethodName: "RebuildDocumentIndex",
			Handler:    _AiKnowledgeService_RebuildDocumentIndex_Handler,
		},
		{
			MethodName: "SearchKnowledge",
			Handler:    _AiKnowledgeService_SearchKnowledge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/ai.proto",
}

const (
	AiChatService_RagChat_FullMethodName                 = "/ai.AiChatService/RagChat"
	AiChatService_RagChatStream_FullMethodName           = "/ai.AiChatService/RagChatStream"
	AiChatService_ListConversation_FullMethodName        = "/ai.AiChatService/ListConversation"
	AiChatService_GetConversationMessages_FullMethodName = "/ai.AiChatService/GetConversationMessages"
)

// AiChatServiceClient is the client API for AiChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI 会话服务，负责 RAG 问答、流式输出和会话历史。
type AiChatServiceClient interface {
	// 执行普通 RAG 问答，返回完整答案。
	RagChat(ctx context.Context, in *RagChatReq, opts ...grpc.CallOption) (*RagChatResp, error)
	// 执行流式 RAG 问答，逐步返回 token、引用和完成事件。
	RagChatStream(ctx context.Context, in *RagChatReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RagChatStreamEvent], error)
	// 查询当前用户的 AI 会话列表。
	ListConversation(ctx context.Context, in *ListConversationReq, opts ...grpc.CallOption) (*ListConversationResp, error)
	// 查询指定会话的消息历史。
	GetConversationMessages(ctx context.Context, in *GetConversationMessagesReq, opts ...grpc.CallOption) (*GetConversationMessagesResp, error)
}

type aiChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiChatServiceClient(cc grpc.ClientConnInterface) AiChatServiceClient {
	return &aiChatServiceClient{cc}
}

func (c *aiChatServiceClient) RagChat(ctx context.Context, in *RagChatReq, opts ...grpc.CallOption) (*RagChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RagChatResp)
	err := c.cc.Invoke(ctx, AiChatService_RagChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) RagChatStream(ctx context.Context, in *RagChatReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RagChatStreamEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AiChatService_ServiceDesc.Streams[0], AiChatService_RagChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RagChatReq, RagChatStreamEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiChatService_RagChatStreamClient = grpc.ServerStreamingClient[RagChatStreamEvent]

func (c *aiChatServiceClient) ListConversation(ctx context.Context, in *ListConversationReq, opts ...grpc.CallOption) (*ListConversationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConversationResp)
	err := c.cc.Invoke(ctx, AiChatService_ListConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) GetConversationMessages(ctx context.Context, in *GetConversationMessagesReq, opts ...grpc.CallOption) (*GetConversationMessagesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversationMessagesResp)
	err := c.cc.Invoke(ctx, AiChatService_GetConversationMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiChatServiceServer is the server API for AiChatService service.
// All implementations must embed UnimplementedAiChatServiceServer
// for forward compatibility.
//
// AI 会话服务，负责 RAG 问答、流式输出和会话历史。
type AiChatServiceServer interface {
	// 执行普通 RAG 问答，返回完整答案。
	RagChat(context.Context, *RagChatReq) (*RagChatResp, error)
	// 执行流式 RAG 问答，逐步返回 token、引用和完成事件。
	RagChatStream(*RagChatReq, grpc.ServerStreamingServer[RagChatStreamEvent]) error
	// 查询当前用户的 AI 会话列表。
	ListConversation(context.Context, *ListConversationReq) (*ListConversationResp, error)
	// 查询指定会话的消息历史。
	GetConversationMessages(context.Context, *GetConversationMessagesReq) (*GetConversationMessagesResp, error)
	mustEmbedUnimplementedAiChatServiceServer()
}

// UnimplementedAiChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiChatServiceServer struct{}

func (UnimplementedAiChatServiceServer) RagChat(context.Context, *RagChatReq) (*RagChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RagChat not implemented")
}
func (UnimplementedAiChatServiceServer) RagChatStream(*RagChatReq, grpc.ServerStreamingServer[RagChatStreamEvent]) error {
	return status.Errorf(codes.Unimplemented, "method RagChatStream not implemented")
}
func (UnimplementedAiChatServiceServer) ListConversation(context.Context, *ListConversationReq) (*ListConversationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConversation not implemented")
}
func (UnimplementedAiChatServiceServer) GetConversationMessages(context.Context, *GetConversationMessagesReq) (*GetConversationMessagesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversationMessages not implemented")
}
func (UnimplementedAiChatServiceServer) mustEmbedUnimplementedAiChatServiceServer() {}
func (UnimplementedAiChatServiceServer) testEmbeddedByValue()                       {}

// UnsafeAiChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiChatServiceServer will
// result in compilation errors.
type UnsafeAiChatServiceServer interface {
	mustEmbedUnimplementedAiChatServiceServer()
}

func RegisterAiChatServiceServer(s grpc.ServiceRegistrar, srv AiChatServiceServer) {
	// If the following call pancis, it indicates UnimplementedAiChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiChatService_ServiceDesc, srv)
}

func _AiChatService_RagChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RagChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).RagChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_RagChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).RagChat(ctx, req.(*RagChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_RagChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RagChatReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiChatServiceServer).RagChatStream(m, &grpc.GenericServerStream[RagChatReq, RagChatStreamEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiChatService_RagChatStreamServer = grpc.ServerStreamingServer[RagChatStreamEvent]

func _AiChatService_ListConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).ListConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_ListConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).ListConversation(ctx, req.(*ListConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_GetConversationMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).GetConversationMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiChatService_GetConversationMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).GetConversationMessages(ctx, req.(*GetConversationMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AiChatService_ServiceDesc is the grpc.ServiceDesc for AiChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AiChatService",
	HandlerType: (*AiChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RagChat",
			Handler:    _AiChatService_RagChat_Handler,
		},
		{
			MethodName: "ListConversation",
			Handler:    _AiChatService_ListConversation_Handler,
		},
		{
			MethodName: "GetConversationMessages",
			Handler:    _AiChatService_GetConversationMessages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RagChatStream",
			Handler:       _AiChatService_RagChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/ai.proto",
}

const (
	AiSecurityService_SearchSecurityLogs_FullMethodName        = "/ai.AiSecurityService/SearchSecurityLogs"
	AiSecurityService_AnalyzeSecurityEvents_FullMethodName     = "/ai.AiSecurityService/AnalyzeSecurityEvents"
	AiSecurityService_ListSecurityEvents_FullMethodName        = "/ai.AiSecurityService/ListSecurityEvents"
	AiSecurityService_ListSecurityAlerts_FullMethodName        = "/ai.AiSecurityService/ListSecurityAlerts"
	AiSecurityService_UpdateSecurityAlertStatus_FullMethodName = "/ai.AiSecurityService/UpdateSecurityAlertStatus"
)

// AiSecurityServiceClient is the client API for AiSecurityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI 安全服务，负责 SSH 日志检索、事件分析和告警管理。
type AiSecurityServiceClient interface {
	// 检索 SSH 原始日志。
	SearchSecurityLogs(ctx context.Context, in *SearchSecurityLogsReq, opts ...grpc.CallOption) (*SecurityLogSearchResp, error)
	// 分析原始日志并生成结构化安全事件和告警摘要。
	AnalyzeSecurityEvents(ctx context.Context, in *AnalyzeSecurityEventsReq, opts ...grpc.CallOption) (*AnalyzeSecurityEventsResp, error)
	// 查询结构化安全事件列表。
	ListSecurityEvents(ctx context.Context, in *ListSecurityEventsReq, opts ...grpc.CallOption) (*ListSecurityEventsResp, error)
	// 查询安全告警列表。
	ListSecurityAlerts(ctx context.Context, in *ListSecurityAlertsReq, opts ...grpc.CallOption) (*ListSecurityAlertsResp, error)
	// 更新安全告警处理状态。
	UpdateSecurityAlertStatus(ctx context.Context, in *UpdateSecurityAlertStatusReq, opts ...grpc.CallOption) (*Empty, error)
}

type aiSecurityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiSecurityServiceClient(cc grpc.ClientConnInterface) AiSecurityServiceClient {
	return &aiSecurityServiceClient{cc}
}

func (c *aiSecurityServiceClient) SearchSecurityLogs(ctx context.Context, in *SearchSecurityLogsReq, opts ...grpc.CallOption) (*SecurityLogSearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityLogSearchResp)
	err := c.cc.Invoke(ctx, AiSecurityService_SearchSecurityLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiSecurityServiceClient) AnalyzeSecurityEvents(ctx context.Context, in *AnalyzeSecurityEventsReq, opts ...grpc.CallOption) (*AnalyzeSecurityEventsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeSecurityEventsResp)
	err := c.cc.Invoke(ctx, AiSecurityService_AnalyzeSecurityEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiSecurityServiceClient) ListSecurityEvents(ctx context.Context, in *ListSecurityEventsReq, opts ...grpc.CallOption) (*ListSecurityEventsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecurityEventsResp)
	err := c.cc.Invoke(ctx, AiSecurityService_ListSecurityEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiSecurityServiceClient) ListSecurityAlerts(ctx context.Context, in *ListSecurityAlertsReq, opts ...grpc.CallOption) (*ListSecurityAlertsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecurityAlertsResp)
	err := c.cc.Invoke(ctx, AiSecurityService_ListSecurityAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiSecurityServiceClient) UpdateSecurityAlertStatus(ctx context.Context, in *UpdateSecurityAlertStatusReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AiSecurityService_UpdateSecurityAlertStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiSecurityServiceServer is the server API for AiSecurityService service.
// All implementations must embed UnimplementedAiSecurityServiceServer
// for forward compatibility.
//
// AI 安全服务，负责 SSH 日志检索、事件分析和告警管理。
type AiSecurityServiceServer interface {
	// 检索 SSH 原始日志。
	SearchSecurityLogs(context.Context, *SearchSecurityLogsReq) (*SecurityLogSearchResp, error)
	// 分析原始日志并生成结构化安全事件和告警摘要。
	AnalyzeSecurityEvents(context.Context, *AnalyzeSecurityEventsReq) (*AnalyzeSecurityEventsResp, error)
	// 查询结构化安全事件列表。
	ListSecurityEvents(context.Context, *ListSecurityEventsReq) (*ListSecurityEventsResp, error)
	// 查询安全告警列表。
	ListSecurityAlerts(context.Context, *ListSecurityAlertsReq) (*ListSecurityAlertsResp, error)
	// 更新安全告警处理状态。
	UpdateSecurityAlertStatus(context.Context, *UpdateSecurityAlertStatusReq) (*Empty, error)
	mustEmbedUnimplementedAiSecurityServiceServer()
}

// UnimplementedAiSecurityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiSecurityServiceServer struct{}

func (UnimplementedAiSecurityServiceServer) SearchSecurityLogs(context.Context, *SearchSecurityLogsReq) (*SecurityLogSearchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchSecurityLogs not implemented")
}
func (UnimplementedAiSecurityServiceServer) AnalyzeSecurityEvents(context.Context, *AnalyzeSecurityEventsReq) (*AnalyzeSecurityEventsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeSecurityEvents not implemented")
}
func (UnimplementedAiSecurityServiceServer) ListSecurityEvents(context.Context, *ListSecurityEventsReq) (*ListSecurityEventsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSecurityEvents not implemented")
}
func (UnimplementedAiSecurityServiceServer) ListSecurityAlerts(context.Context, *ListSecurityAlertsReq) (*ListSecurityAlertsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSecurityAlerts not implemented")
}
func (UnimplementedAiSecurityServiceServer) UpdateSecurityAlertStatus(context.Context, *UpdateSecurityAlertStatusReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSecurityAlertStatus not implemented")
}
func (UnimplementedAiSecurityServiceServer) mustEmbedUnimplementedAiSecurityServiceServer() {}
func (UnimplementedAiSecurityServiceServer) testEmbeddedByValue()                           {}

// UnsafeAiSecurityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiSecurityServiceServer will
// result in compilation errors.
type UnsafeAiSecurityServiceServer interface {
	mustEmbedUnimplementedAiSecurityServiceServer()
}

func RegisterAiSecurityServiceServer(s grpc.ServiceRegistrar, srv AiSecurityServiceServer) {
	// If the following call pancis, it indicates UnimplementedAiSecurityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiSecurityService_ServiceDesc, srv)
}

func _AiSecurityService_SearchSecurityLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSecurityLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiSecurityServiceServer).SearchSecurityLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiSecurityService_SearchSecurityLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiSecurityServiceServer).SearchSecurityLogs(ctx, req.(*SearchSecurityLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiSecurityService_AnalyzeSecurityEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeSecurityEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiSecurityServiceServer).AnalyzeSecurityEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiSecurityService_AnalyzeSecurityEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiSecurityServiceServer).AnalyzeSecurityEvents(ctx, req.(*AnalyzeSecurityEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiSecurityService_ListSecurityEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecurityEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiSecurityServiceServer).ListSecurityEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiSecurityService_ListSecurityEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiSecurityServiceServer).ListSecurityEvents(ctx, req.(*ListSecurityEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiSecurityService_ListSecurityAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecurityAlertsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiSecurityServiceServer).ListSecurityAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiSecurityService_ListSecurityAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiSecurityServiceServer).ListSecurityAlerts(ctx, req.(*ListSecurityAlertsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiSecurityService_UpdateSecurityAlertStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecurityAlertStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiSecurityServiceServer).UpdateSecurityAlertStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiSecurityService_UpdateSecurityAlertStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiSecurityServiceServer).UpdateSecurityAlertStatus(ctx, req.(*UpdateSecurityAlertStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AiSecurityService_ServiceDesc is the grpc.ServiceDesc for AiSecurityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiSecurityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AiSecurityService",
	HandlerType: (*AiSecurityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchSecurityLogs",
			Handler:    _AiSecurityService_SearchSecurityLogs_Handler,
		},
		{
			MethodName: "AnalyzeSecurityEvents",
			Handler:    _AiSecurityService_AnalyzeSecurityEvents_Handler,
		},
		{
			MethodName: "ListSecurityEvents",
			Handler:    _AiSecurityService_ListSecurityEvents_Handler,
		},
		{
			MethodName: "ListSecurityAlerts",
			Handler:    _AiSecurityService_ListSecurityAlerts_Handler,
		},
		{
			MethodName: "UpdateSecurityAlertStatus",
			Handler:    _AiSecurityService_UpdateSecurityAlertStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/ai.proto",
}

const (
	AiReportService_GenerateDailyReport_FullMethodName = "/ai.AiReportService/GenerateDailyReport"
	AiReportService_ListDailyReport_FullMethodName     = "/ai.AiReportService/ListDailyReport"
	AiReportService_GetDailyReport_FullMethodName      = "/ai.AiReportService/GetDailyReport"
)

// AiReportServiceClient is the client API for AiReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI 日报服务，负责生成和查询安全日报。
type AiReportServiceClient interface {
	// 生成指定日期的 AI 安全日报。
	GenerateDailyReport(ctx context.Context, in *GenerateDailyReportReq, opts ...grpc.CallOption) (*DailyReportResp, error)
	// 查询 AI 安全日报列表。
	ListDailyReport(ctx context.Context, in *ListDailyReportReq, opts ...grpc.CallOption) (*ListDailyReportResp, error)
	// 查询单份 AI 安全日报详情。
	GetDailyReport(ctx context.Context, in *GetDailyReportReq, opts ...grpc.CallOption) (*DailyReportResp, error)
}

type aiReportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiReportServiceClient(cc grpc.ClientConnInterface) AiReportServiceClient {
	return &aiReportServiceClient{cc}
}

func (c *aiReportServiceClient) GenerateDailyReport(ctx context.Context, in *GenerateDailyReportReq, opts ...grpc.CallOption) (*DailyReportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyReportResp)
	err := c.cc.Invoke(ctx, AiReportService_GenerateDailyReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiReportServiceClient) ListDailyReport(ctx context.Context, in *ListDailyReportReq, opts ...grpc.CallOption) (*ListDailyReportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDailyReportResp)
	err := c.cc.Invoke(ctx, AiReportService_ListDailyReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiReportServiceClient) GetDailyReport(ctx context.Context, in *GetDailyReportReq, opts ...grpc.CallOption) (*DailyReportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyReportResp)
	err := c.cc.Invoke(ctx, AiReportService_GetDailyReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiReportServiceServer is the server API for AiReportService service.
// All implementations must embed UnimplementedAiReportServiceServer
// for forward compatibility.
//
// AI 日报服务，负责生成和查询安全日报。
type AiReportServiceServer interface {
	// 生成指定日期的 AI 安全日报。
	GenerateDailyReport(context.Context, *GenerateDailyReportReq) (*DailyReportResp, error)
	// 查询 AI 安全日报列表。
	ListDailyReport(context.Context, *ListDailyReportReq) (*ListDailyReportResp, error)
	// 查询单份 AI 安全日报详情。
	GetDailyReport(context.Context, *GetDailyReportReq) (*DailyReportResp, error)
	mustEmbedUnimplementedAiReportServiceServer()
}

// UnimplementedAiReportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiReportServiceServer struct{}

func (UnimplementedAiReportServiceServer) GenerateDailyReport(context.Context, *GenerateDailyReportReq) (*DailyReportResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDailyReport not implemented")
}
func (UnimplementedAiReportServiceServer) ListDailyReport(context.Context, *ListDailyReportReq) (*ListDailyReportResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDailyReport not implemented")
}
func (UnimplementedAiReportServiceServer) GetDailyReport(context.Context, *GetDailyReportReq) (*DailyReportResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyReport not implemented")
}
func (UnimplementedAiReportServiceServer) mustEmbedUnimplementedAiReportServiceServer() {}
func (UnimplementedAiReportServiceServer) testEmbeddedByValue()                         {}

// UnsafeAiReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiReportServiceServer will
// result in compilation errors.
type UnsafeAiReportServiceServer interface {
	mustEmbedUnimplementedAiReportServiceServer()
}

func RegisterAiReportServiceServer(s grpc.ServiceRegistrar, srv AiReportServiceServer) {
	// If the following call pancis, it indicates UnimplementedAiReportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiReportService_ServiceDesc, srv)
}

func _AiReportService_GenerateDailyReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDailyReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiReportServiceServer).GenerateDailyReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiReportService_GenerateDailyReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiReportServiceServer).GenerateDailyReport(ctx, req.(*GenerateDailyReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiReportService_ListDailyReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDailyReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiReportServiceServer).ListDailyReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiReportService_ListDailyReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiReportServiceServer).ListDailyReport(ctx, req.(*ListDailyReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiReportService_GetDailyReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiReportServiceServer).GetDailyReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiReportService_GetDailyReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiReportServiceServer).GetDailyReport(ctx, req.(*GetDailyReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AiReportService_ServiceDesc is the grpc.ServiceDesc for AiReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AiReportService",
	HandlerType: (*AiReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateDailyReport",
			Handler:    _AiReportService_GenerateDailyReport_Handler,
		},
		{
			MethodName: "ListDailyReport",
			Handler:    _AiReportService_ListDailyReport_Handler,
		},
		{
			MethodName: "GetDailyReport",
			Handler:    _AiReportService_GetDailyReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/ai.proto",
}

const (
	AiAgentService_RunAgent_FullMethodName        = "/ai.AiAgentService/RunAgent"
	AiAgentService_ListToolCallLog_FullMethodName = "/ai.AiAgentService/ListToolCallLog"
)

// AiAgentServiceClient is the client API for AiAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI Agent 服务，负责受控 Agent 执行和工具调用审计。
type AiAgentServiceClient interface {
	// 运行受控 Agent，只允许调用白名单工具。
	RunAgent(ctx context.Context, in *AgentRunReq, opts ...grpc.CallOption) (*AgentRunResp, error)
	// 查询 Agent 工具调用日志。
	ListToolCallLog(ctx context.Context, in *ListToolCallLogReq, opts ...grpc.CallOption) (*ListToolCallLogResp, error)
}

type aiAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiAgentServiceClient(cc grpc.ClientConnInterface) AiAgentServiceClient {
	return &aiAgentServiceClient{cc}
}

func (c *aiAgentServiceClient) RunAgent(ctx context.Context, in *AgentRunReq, opts ...grpc.CallOption) (*AgentRunResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentRunResp)
	err := c.cc.Invoke(ctx, AiAgentService_RunAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiAgentServiceClient) ListToolCallLog(ctx context.Context, in *ListToolCallLogReq, opts ...grpc.CallOption) (*ListToolCallLogResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolCallLogResp)
	err := c.cc.Invoke(ctx, AiAgentService_ListToolCallLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiAgentServiceServer is the server API for AiAgentService service.
// All implementations must embed UnimplementedAiAgentServiceServer
// for forward compatibility.
//
// AI Agent 服务，负责受控 Agent 执行和工具调用审计。
type AiAgentServiceServer interface {
	// 运行受控 Agent，只允许调用白名单工具。
	RunAgent(context.Context, *AgentRunReq) (*AgentRunResp, error)
	// 查询 Agent 工具调用日志。
	ListToolCallLog(context.Context, *ListToolCallLogReq) (*ListToolCallLogResp, error)
	mustEmbedUnimplementedAiAgentServiceServer()
}

// UnimplementedAiAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiAgentServiceServer struct{}

func (UnimplementedAiAgentServiceServer) RunAgent(context.Context, *AgentRunReq) (*AgentRunResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunAgent not implemented")
}
func (UnimplementedAiAgentServiceServer) ListToolCallLog(context.Context, *ListToolCallLogReq) (*ListToolCallLogResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListToolCallLog not implemented")
}
func (UnimplementedAiAgentServiceServer) mustEmbedUnimplementedAiAgentServiceServer() {}
func (UnimplementedAiAgentServiceServer) testEmbeddedByValue()                        {}

// UnsafeAiAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiAgentServiceServer will
// result in compilation errors.
type UnsafeAiAgentServiceServer interface {
	mustEmbedUnimplementedAiAgentServiceServer()
}

func RegisterAiAgentServiceServer(s grpc.ServiceRegistrar, srv AiAgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAiAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiAgentService_ServiceDesc, srv)
}

func _AiAgentService_RunAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRunReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiAgentServiceServer).RunAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiAgentService_RunAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiAgentServiceServer).RunAgent(ctx, req.(*AgentRunReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiAgentService_ListToolCallLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolCallLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiAgentServiceServer).ListToolCallLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiAgentService_ListToolCallLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiAgentServiceServer).ListToolCallLog(ctx, req.(*ListToolCallLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AiAgentService_ServiceDesc is the grpc.ServiceDesc for AiAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AiAgentService",
	HandlerType: (*AiAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunAgent",
			Handler:    _AiAgentService_RunAgent_Handler,
		},
		{
			MethodName: "ListToolCallLog",
			Handler:    _AiAgentService_ListToolCallLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/ai.proto",
}

const (
	AiObservabilityService_GetLlmTrace_FullMethodName    = "/ai.AiObservabilityService/GetLlmTrace"
	AiObservabilityService_ListLlmCallLog_FullMethodName = "/ai.AiObservabilityService/ListLlmCallLog"
	AiObservabilityService_GetTokenStats_FullMethodName  = "/ai.AiObservabilityService/GetTokenStats"
)

// AiObservabilityServiceClient is the client API for AiObservabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI 可观测性服务，负责 LLM 调用 trace 和 token 统计。
type AiObservabilityServiceClient interface {
	// 查询指定 traceId 下的 LLM 调用链路。
	GetLlmTrace(ctx context.Context, in *GetLlmTraceReq, opts ...grpc.CallOption) (*LlmTraceResp, error)
	// 分页查询 LLM 调用日志。
	ListLlmCallLog(ctx context.Context, in *ListLlmCallLogReq, opts ...grpc.CallOption) (*ListLlmCallLogResp, error)
	// 查询当前用户在指定范围内的 token 用量统计。
	GetTokenStats(ctx context.Context, in *GetTokenStatsReq, opts ...grpc.CallOption) (*TokenStatsResp, error)
}

type aiObservabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiObservabilityServiceClient(cc grpc.ClientConnInterface) AiObservabilityServiceClient {
	return &aiObservabilityServiceClient{cc}
}

func (c *aiObservabilityServiceClient) GetLlmTrace(ctx context.Context, in *GetLlmTraceReq, opts ...grpc.CallOption) (*LlmTraceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LlmTraceResp)
	err := c.cc.Invoke(ctx, AiObservabilityService_GetLlmTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiObservabilityServiceClient) ListLlmCallLog(ctx context.Context, in *ListLlmCallLogReq, opts ...grpc.CallOption) (*ListLlmCallLogResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLlmCallLogResp)
	err := c.cc.Invoke(ctx, AiObservabilityService_ListLlmCallLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiObservabilityServiceClient) GetTokenStats(ctx context.Context, in *GetTokenStatsReq, opts ...grpc.CallOption) (*TokenStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenStatsResp)
	err := c.cc.Invoke(ctx, AiObservabilityService_GetTokenStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiObservabilityServiceServer is the server API for AiObservabilityService service.
// All implementations must embed UnimplementedAiObservabilityServiceServer
// for forward compatibility.
//
// AI 可观测性服务，负责 LLM 调用 trace 和 token 统计。
type AiObservabilityServiceServer interface {
	// 查询指定 traceId 下的 LLM 调用链路。
	GetLlmTrace(context.Context, *GetLlmTraceReq) (*LlmTraceResp, error)
	// 分页查询 LLM 调用日志。
	ListLlmCallLog(context.Context, *ListLlmCallLogReq) (*ListLlmCallLogResp, error)
	// 查询当前用户在指定范围内的 token 用量统计。
	GetTokenStats(context.Context, *GetTokenStatsReq) (*TokenStatsResp, error)
	mustEmbedUnimplementedAiObservabilityServiceServer()
}

// UnimplementedAiObservabilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiObservabilityServiceServer struct{}

func (UnimplementedAiObservabilityServiceServer) GetLlmTrace(context.Context, *GetLlmTraceReq) (*LlmTraceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLlmTrace not implemented")
}
func (UnimplementedAiObservabilityServiceServer) ListLlmCallLog(context.Context, *ListLlmCallLogReq) (*ListLlmCallLogResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLlmCallLog not implemented")
}
func (UnimplementedAiObservabilityServiceServer) GetTokenStats(context.Context, *GetTokenStatsReq) (*TokenStatsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenStats not implemented")
}
func (UnimplementedAiObservabilityServiceServer) mustEmbedUnimplementedAiObservabilityServiceServer() {
}
func (UnimplementedAiObservabilityServiceServer) testEmbeddedByValue() {}

// UnsafeAiObservabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiObservabilityServiceServer will
// result in compilation errors.
type UnsafeAiObservabilityServiceServer interface {
	mustEmbedUnimplementedAiObservabilityServiceServer()
}

func RegisterAiObservabilityServiceServer(s grpc.ServiceRegistrar, srv AiObservabilityServiceServer) {
	// If the following call pancis, it indicates UnimplementedAiObservabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiObservabilityService_ServiceDesc, srv)
}

func _AiObservabilityService_GetLlmTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLlmTraceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiObservabilityServiceServer).GetLlmTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiObservabilityService_GetLlmTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiObservabilityServiceServer).GetLlmTrace(ctx, req.(*GetLlmTraceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiObservabilityService_ListLlmCallLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLlmCallLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiObservabilityServiceServer).ListLlmCallLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiObservabilityService_ListLlmCallLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiObservabilityServiceServer).ListLlmCallLog(ctx, req.(*ListLlmCallLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiObservabilityService_GetTokenStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiObservabilityServiceServer).GetTokenStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiObservabilityService_GetTokenStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiObservabilityServiceServer).GetTokenStats(ctx, req.(*GetTokenStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AiObservabilityService_ServiceDesc is the grpc.ServiceDesc for AiObservabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiObservabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AiObservabilityService",
	HandlerType: (*AiObservabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLlmTrace",
			Handler:    _AiObservabilityService_GetLlmTrace_Handler,
		},
		{
			MethodName: "ListLlmCallLog",
			Handler:    _AiObservabilityService_ListLlmCallLog_Handler,
		},
		{
			MethodName: "GetTokenStats",
			Handler:    _AiObservabilityService_GetTokenStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/ai.proto",
}
