// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"context"

	"ai-copilot-platform/ai-rpc/internal/logic/aistatusservice"
	"ai-copilot-platform/ai-rpc/internal/svc"
	"ai-copilot-platform/ai-rpc/pb"
)

type AiStatusServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiStatusServiceServer
}

func NewAiStatusServiceServer(svcCtx *svc.ServiceContext) *AiStatusServiceServer {
	return &AiStatusServiceServer{
		svcCtx: svcCtx,
	}
}

// 检查 AI 引擎健康状态。
func (s *AiStatusServiceServer) Health(ctx context.Context, in *pb.HealthReq) (*pb.HealthResp, error) {
	l := aistatusservicelogic.NewHealthLogic(ctx, s.svcCtx)
	return l.Health(in)
}
