// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package aiwindreportservice

import (
	"context"

	"ai-copilot-platform/ai-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	WindHealthReportGetReq = pb.WindHealthReportGetReq
	WindHealthReportReq    = pb.WindHealthReportReq
	WindScaffoldResp       = pb.WindScaffoldResp

	AiWindReportService interface {
		GenerateHealthReport(ctx context.Context, in *WindHealthReportReq, opts ...grpc.CallOption) (*WindScaffoldResp, error)
		GetHealthReport(ctx context.Context, in *WindHealthReportGetReq, opts ...grpc.CallOption) (*WindScaffoldResp, error)
	}

	defaultAiWindReportService struct {
		cli zrpc.Client
	}
)

func NewAiWindReportService(cli zrpc.Client) AiWindReportService {
	return &defaultAiWindReportService{
		cli: cli,
	}
}

func (m *defaultAiWindReportService) GenerateHealthReport(ctx context.Context, in *WindHealthReportReq, opts ...grpc.CallOption) (*WindScaffoldResp, error) {
	client := pb.NewAiWindReportServiceClient(m.cli.Conn())
	return client.GenerateHealthReport(ctx, in, opts...)
}

func (m *defaultAiWindReportService) GetHealthReport(ctx context.Context, in *WindHealthReportGetReq, opts ...grpc.CallOption) (*WindScaffoldResp, error) {
	client := pb.NewAiWindReportServiceClient(m.cli.Conn())
	return client.GetHealthReport(ctx, in, opts...)
}
