// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package aiwindalarmservice

import (
	"context"

	"ai-copilot-platform/ai-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	WindAlarmAnalyzeReq = pb.WindAlarmAnalyzeReq
	WindAlarmQueryReq   = pb.WindAlarmQueryReq
	WindAlarmQueryResp  = pb.WindAlarmQueryResp
	WindScaffoldResp    = pb.WindScaffoldResp

	AiWindAlarmService interface {
		QueryAlarms(ctx context.Context, in *WindAlarmQueryReq, opts ...grpc.CallOption) (*WindAlarmQueryResp, error)
		AnalyzeAlarm(ctx context.Context, in *WindAlarmAnalyzeReq, opts ...grpc.CallOption) (*WindScaffoldResp, error)
	}

	defaultAiWindAlarmService struct {
		cli zrpc.Client
	}
)

func NewAiWindAlarmService(cli zrpc.Client) AiWindAlarmService {
	return &defaultAiWindAlarmService{
		cli: cli,
	}
}

func (m *defaultAiWindAlarmService) QueryAlarms(ctx context.Context, in *WindAlarmQueryReq, opts ...grpc.CallOption) (*WindAlarmQueryResp, error) {
	client := pb.NewAiWindAlarmServiceClient(m.cli.Conn())
	return client.QueryAlarms(ctx, in, opts...)
}

func (m *defaultAiWindAlarmService) AnalyzeAlarm(ctx context.Context, in *WindAlarmAnalyzeReq, opts ...grpc.CallOption) (*WindScaffoldResp, error) {
	client := pb.NewAiWindAlarmServiceClient(m.cli.Conn())
	return client.AnalyzeAlarm(ctx, in, opts...)
}
