// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package aireportservice

import (
	"context"

	"ai-copilot-platform/ai-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DailyReportResp        = pb.DailyReportResp
	GenerateDailyReportReq = pb.GenerateDailyReportReq
	GetDailyReportReq      = pb.GetDailyReportReq
	ListDailyReportReq     = pb.ListDailyReportReq
	ListDailyReportResp    = pb.ListDailyReportResp

	AiReportService interface {
		// 生成指定日期的 AI 安全日报。
		GenerateDailyReport(ctx context.Context, in *GenerateDailyReportReq, opts ...grpc.CallOption) (*DailyReportResp, error)
		// 查询 AI 安全日报列表。
		ListDailyReport(ctx context.Context, in *ListDailyReportReq, opts ...grpc.CallOption) (*ListDailyReportResp, error)
		// 查询单份 AI 安全日报详情。
		GetDailyReport(ctx context.Context, in *GetDailyReportReq, opts ...grpc.CallOption) (*DailyReportResp, error)
	}

	defaultAiReportService struct {
		cli zrpc.Client
	}
)

func NewAiReportService(cli zrpc.Client) AiReportService {
	return &defaultAiReportService{
		cli: cli,
	}
}

// 生成指定日期的 AI 安全日报。
func (m *defaultAiReportService) GenerateDailyReport(ctx context.Context, in *GenerateDailyReportReq, opts ...grpc.CallOption) (*DailyReportResp, error) {
	client := pb.NewAiReportServiceClient(m.cli.Conn())
	return client.GenerateDailyReport(ctx, in, opts...)
}

// 查询 AI 安全日报列表。
func (m *defaultAiReportService) ListDailyReport(ctx context.Context, in *ListDailyReportReq, opts ...grpc.CallOption) (*ListDailyReportResp, error) {
	client := pb.NewAiReportServiceClient(m.cli.Conn())
	return client.ListDailyReport(ctx, in, opts...)
}

// 查询单份 AI 安全日报详情。
func (m *defaultAiReportService) GetDailyReport(ctx context.Context, in *GetDailyReportReq, opts ...grpc.CallOption) (*DailyReportResp, error) {
	client := pb.NewAiReportServiceClient(m.cli.Conn())
	return client.GetDailyReport(ctx, in, opts...)
}
