// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"context"

	"ai-copilot-platform/ai-rpc/internal/logic/aiobservabilityservice"
	"ai-copilot-platform/ai-rpc/internal/svc"
	"ai-copilot-platform/ai-rpc/pb"
)

type AiObservabilityServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiObservabilityServiceServer
}

func NewAiObservabilityServiceServer(svcCtx *svc.ServiceContext) *AiObservabilityServiceServer {
	return &AiObservabilityServiceServer{
		svcCtx: svcCtx,
	}
}

// 查询指定 traceId 下的 LLM 调用链路。
func (s *AiObservabilityServiceServer) GetLlmTrace(ctx context.Context, in *pb.GetLlmTraceReq) (*pb.LlmTraceResp, error) {
	l := aiobservabilityservicelogic.NewGetLlmTraceLogic(ctx, s.svcCtx)
	return l.GetLlmTrace(in)
}

// 分页查询 LLM 调用日志。
func (s *AiObservabilityServiceServer) ListLlmCallLog(ctx context.Context, in *pb.ListLlmCallLogReq) (*pb.ListLlmCallLogResp, error) {
	l := aiobservabilityservicelogic.NewListLlmCallLogLogic(ctx, s.svcCtx)
	return l.ListLlmCallLog(in)
}

// 查询当前用户在指定范围内的 token 用量统计。
func (s *AiObservabilityServiceServer) GetTokenStats(ctx context.Context, in *pb.GetTokenStatsReq) (*pb.TokenStatsResp, error) {
	l := aiobservabilityservicelogic.NewGetTokenStatsLogic(ctx, s.svcCtx)
	return l.GetTokenStats(in)
}
