// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"context"

	"ai-copilot-platform/ai-rpc/internal/logic/aiagentservice"
	"ai-copilot-platform/ai-rpc/internal/svc"
	"ai-copilot-platform/ai-rpc/pb"
)

type AiAgentServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiAgentServiceServer
}

func NewAiAgentServiceServer(svcCtx *svc.ServiceContext) *AiAgentServiceServer {
	return &AiAgentServiceServer{
		svcCtx: svcCtx,
	}
}

// 运行受控 Agent，只允许调用白名单工具。
func (s *AiAgentServiceServer) RunAgent(ctx context.Context, in *pb.AgentRunReq) (*pb.AgentRunResp, error) {
	l := aiagentservicelogic.NewRunAgentLogic(ctx, s.svcCtx)
	return l.RunAgent(in)
}

// 查询 Agent 工具调用日志。
func (s *AiAgentServiceServer) ListToolCallLog(ctx context.Context, in *pb.ListToolCallLogReq) (*pb.ListToolCallLogResp, error) {
	l := aiagentservicelogic.NewListToolCallLogLogic(ctx, s.svcCtx)
	return l.ListToolCallLog(in)
}
