// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	ai_chat "ai-copilot-platform/gateway/internal/handler/ai_chat"
	ai_conversation "ai-copilot-platform/gateway/internal/handler/ai_conversation"
	ai_document "ai-copilot-platform/gateway/internal/handler/ai_document"
	ai_kb_domain "ai-copilot-platform/gateway/internal/handler/ai_kb_domain"
	ai_kb_member "ai-copilot-platform/gateway/internal/handler/ai_kb_member"
	ai_kb_personal "ai-copilot-platform/gateway/internal/handler/ai_kb_personal"
	ai_kb_public "ai-copilot-platform/gateway/internal/handler/ai_kb_public"
	ai_llmops "ai-copilot-platform/gateway/internal/handler/ai_llmops"
	ai_search "ai-copilot-platform/gateway/internal/handler/ai_search"
	ai_wind_agent "ai-copilot-platform/gateway/internal/handler/ai_wind_agent"
	ai_wind_alarm "ai-copilot-platform/gateway/internal/handler/ai_wind_alarm"
	ai_wind_metadata "ai-copilot-platform/gateway/internal/handler/ai_wind_metadata"
	ai_wind_report "ai-copilot-platform/gateway/internal/handler/ai_wind_report"
	ai_wind_timeseries "ai-copilot-platform/gateway/internal/handler/ai_wind_timeseries"
	health "ai-copilot-platform/gateway/internal/handler/health"
	"ai-copilot-platform/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/chat",
					Handler: ai_chat.AiChatHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/chat/stream",
					Handler: ai_chat.AiChatStreamHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/conversations",
					Handler: ai_conversation.AiListConversationHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/conversations/:conversationId",
					Handler: ai_conversation.AiDeleteConversationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/conversations/:conversationId/messages",
					Handler: ai_conversation.AiGetConversationMessagesHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/conversations/:conversationId/messages/:messageId",
					Handler: ai_conversation.AiDeleteMessageHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/conversations/:conversationId/title",
					Handler: ai_conversation.AiUpdateConversationTitleHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/kb/:kbId/documents",
					Handler: ai_document.AiIngestDocumentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/kb/:kbId/documents",
					Handler: ai_document.AiListDocumentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/kb/:kbId/documents/:documentId",
					Handler: ai_document.AiGetDocumentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/kb/:kbId/documents/:documentId",
					Handler: ai_document.AiDeleteDocumentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/kb/:kbId/documents/:documentId/rebuild",
					Handler: ai_document.AiRebuildDocumentIndexHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/kb/domains",
					Handler: ai_kb_domain.AiListKbDomainHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/kb/domains",
					Handler: ai_kb_domain.AiCreateKbDomainHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/kb/domains/:domainId",
					Handler: ai_kb_domain.AiUpdateKbDomainHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/kb/domains/:domainId",
					Handler: ai_kb_domain.AiDeleteKbDomainHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/kb/public/:kbId/members",
					Handler: ai_kb_member.AiListKbMemberHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/kb/public/:kbId/members",
					Handler: ai_kb_member.AiAddKbMemberHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/kb/public/:kbId/members/:userId",
					Handler: ai_kb_member.AiUpdateKbMemberHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/kb/public/:kbId/members/:userId",
					Handler: ai_kb_member.AiRemoveKbMemberHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/kb/personal",
					Handler: ai_kb_personal.AiCreatePersonalKbHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/kb/personal",
					Handler: ai_kb_personal.AiListPersonalKbHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/kb/personal/:kbId",
					Handler: ai_kb_personal.AiGetPersonalKbHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/kb/personal/:kbId",
					Handler: ai_kb_personal.AiUpdatePersonalKbHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/kb/personal/:kbId",
					Handler: ai_kb_personal.AiDeletePersonalKbHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/kb/public",
					Handler: ai_kb_public.AiCreatePublicKbHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/kb/public",
					Handler: ai_kb_public.AiListPublicKbHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/kb/public/:kbId",
					Handler: ai_kb_public.AiGetPublicKbHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/kb/public/:kbId",
					Handler: ai_kb_public.AiUpdatePublicKbHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/kb/public/:kbId",
					Handler: ai_kb_public.AiDeletePublicKbHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/llm/calls",
					Handler: ai_llmops.AiListLlmCallHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/llm/token-stats",
					Handler: ai_llmops.AiGetTokenStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/llm/traces/:traceId",
					Handler: ai_llmops.AiGetLlmTraceHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/kb/search",
					Handler: ai_search.AiSearchKnowledgeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/agent/run",
					Handler: ai_wind_agent.AiWindRunAgentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/agent/stream",
					Handler: ai_wind_agent.AiWindCopilotAgentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/agent/tool-calls",
					Handler: ai_wind_agent.AiWindListToolCallsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/tickets/draft",
					Handler: ai_wind_agent.AiWindCreateTicketDraftHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai/wind"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/alarms/analyze",
					Handler: ai_wind_alarm.AiWindAnalyzeAlarmHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/alarms/query",
					Handler: ai_wind_alarm.AiWindQueryAlarmsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai/wind"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/metadata/devices",
					Handler: ai_wind_metadata.AiWindListDevicesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/metadata/farms",
					Handler: ai_wind_metadata.AiWindListFarmsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/metadata/turbines",
					Handler: ai_wind_metadata.AiWindListTurbinesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai/wind"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/reports/health/:reportId",
					Handler: ai_wind_report.AiWindGetHealthReportHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/reports/health/generate",
					Handler: ai_wind_report.AiWindGenerateHealthReportHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai/wind"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/timeseries/compare",
					Handler: ai_wind_timeseries.AiWindCompareTrendHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/timeseries/query",
					Handler: ai_wind_timeseries.AiWindQueryTimeseriesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai/wind"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.AiHealthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/ai"),
	)
}
