// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	ai_agent "ai-copilot-platform/gateway/internal/handler/ai_agent"
	ai_chat "ai-copilot-platform/gateway/internal/handler/ai_chat"
	ai_document "ai-copilot-platform/gateway/internal/handler/ai_document"
	ai_kb_domain "ai-copilot-platform/gateway/internal/handler/ai_kb_domain"
	ai_kb_member "ai-copilot-platform/gateway/internal/handler/ai_kb_member"
	ai_kb_personal "ai-copilot-platform/gateway/internal/handler/ai_kb_personal"
	ai_kb_public "ai-copilot-platform/gateway/internal/handler/ai_kb_public"
	ai_llmops "ai-copilot-platform/gateway/internal/handler/ai_llmops"
	ai_report "ai-copilot-platform/gateway/internal/handler/ai_report"
	ai_search "ai-copilot-platform/gateway/internal/handler/ai_search"
	ai_security "ai-copilot-platform/gateway/internal/handler/ai_security"
	health "ai-copilot-platform/gateway/internal/handler/health"
	"ai-copilot-platform/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/agent/run",
				Handler: ai_agent.AiRunAgentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/agent/tool-calls",
				Handler: ai_agent.AiListToolCallHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/chat",
				Handler: ai_chat.AiChatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/chat/stream",
				Handler: ai_chat.AiChatStreamHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/kb/:kbId/documents",
					Handler: ai_document.AiIngestDocumentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/kb/:kbId/documents",
					Handler: ai_document.AiListDocumentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/kb/:kbId/documents/:documentId",
					Handler: ai_document.AiGetDocumentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/kb/:kbId/documents/:documentId",
					Handler: ai_document.AiDeleteDocumentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/kb/:kbId/documents/:documentId/rebuild",
					Handler: ai_document.AiRebuildDocumentIndexHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/kb/domains",
				Handler: ai_kb_domain.AiListKbDomainHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/kb/domains",
				Handler: ai_kb_domain.AiCreateKbDomainHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/kb/domains/:domainId",
				Handler: ai_kb_domain.AiUpdateKbDomainHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/kb/domains/:domainId",
				Handler: ai_kb_domain.AiDeleteKbDomainHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/kb/public/:kbId/members",
				Handler: ai_kb_member.AiListKbMemberHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/kb/public/:kbId/members",
				Handler: ai_kb_member.AiAddKbMemberHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/kb/public/:kbId/members/:userId",
				Handler: ai_kb_member.AiUpdateKbMemberHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/kb/public/:kbId/members/:userId",
				Handler: ai_kb_member.AiRemoveKbMemberHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/kb/personal",
				Handler: ai_kb_personal.AiCreatePersonalKbHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/kb/personal",
				Handler: ai_kb_personal.AiListPersonalKbHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/kb/personal/:kbId",
				Handler: ai_kb_personal.AiGetPersonalKbHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/kb/personal/:kbId",
				Handler: ai_kb_personal.AiUpdatePersonalKbHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/kb/personal/:kbId",
				Handler: ai_kb_personal.AiDeletePersonalKbHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/kb/public",
				Handler: ai_kb_public.AiCreatePublicKbHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/kb/public",
				Handler: ai_kb_public.AiListPublicKbHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/kb/public/:kbId",
				Handler: ai_kb_public.AiGetPublicKbHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/kb/public/:kbId",
				Handler: ai_kb_public.AiUpdatePublicKbHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/kb/public/:kbId",
				Handler: ai_kb_public.AiDeletePublicKbHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/llm/calls",
				Handler: ai_llmops.AiListLlmCallHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/llm/token-stats",
				Handler: ai_llmops.AiGetTokenStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/llm/traces/:traceId",
				Handler: ai_llmops.AiGetLlmTraceHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/reports/daily",
				Handler: ai_report.AiListDailyReportHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/reports/daily/:reportId",
				Handler: ai_report.AiGetDailyReportHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/reports/daily/generate",
				Handler: ai_report.AiGenerateDailyReportHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.CasbinMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/kb/search",
					Handler: ai_search.AiSearchKnowledgeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/security/alerts",
				Handler: ai_security.AiListSecurityAlertsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/security/alerts/:alertId/status",
				Handler: ai_security.AiUpdateSecurityAlertStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/security/events",
				Handler: ai_security.AiListSecurityEventsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/security/events/analyze",
				Handler: ai_security.AiAnalyzeSecurityEventsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/security/logs/search",
				Handler: ai_security.AiSearchSecurityLogsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/ai"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.AiHealthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/ai"),
	)
}
