// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"context"

	"ai-copilot-platform/ai-rpc/internal/logic/aiknowledgeservice"
	"ai-copilot-platform/ai-rpc/internal/svc"
	"ai-copilot-platform/ai-rpc/pb"
)

type AiKnowledgeServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiKnowledgeServiceServer
}

func NewAiKnowledgeServiceServer(svcCtx *svc.ServiceContext) *AiKnowledgeServiceServer {
	return &AiKnowledgeServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建公共知识库领域。
func (s *AiKnowledgeServiceServer) CreateDomain(ctx context.Context, in *pb.CreateDomainReq) (*pb.CreateDomainResp, error) {
	l := aiknowledgeservicelogic.NewCreateDomainLogic(ctx, s.svcCtx)
	return l.CreateDomain(in)
}

// 更新公共知识库领域基础信息。
func (s *AiKnowledgeServiceServer) UpdateDomain(ctx context.Context, in *pb.UpdateDomainReq) (*pb.Empty, error) {
	l := aiknowledgeservicelogic.NewUpdateDomainLogic(ctx, s.svcCtx)
	return l.UpdateDomain(in)
}

// 删除公共知识库领域。
func (s *AiKnowledgeServiceServer) DeleteDomain(ctx context.Context, in *pb.DeleteDomainReq) (*pb.Empty, error) {
	l := aiknowledgeservicelogic.NewDeleteDomainLogic(ctx, s.svcCtx)
	return l.DeleteDomain(in)
}

// 查询公共知识库领域列表。
func (s *AiKnowledgeServiceServer) ListDomain(ctx context.Context, in *pb.ListDomainReq) (*pb.ListDomainResp, error) {
	l := aiknowledgeservicelogic.NewListDomainLogic(ctx, s.svcCtx)
	return l.ListDomain(in)
}

// 创建个人或公共知识库。
func (s *AiKnowledgeServiceServer) CreateKnowledgeBase(ctx context.Context, in *pb.CreateKnowledgeBaseReq) (*pb.CreateKnowledgeBaseResp, error) {
	l := aiknowledgeservicelogic.NewCreateKnowledgeBaseLogic(ctx, s.svcCtx)
	return l.CreateKnowledgeBase(in)
}

// 更新知识库名称、描述、领域、可见性或状态。
func (s *AiKnowledgeServiceServer) UpdateKnowledgeBase(ctx context.Context, in *pb.UpdateKnowledgeBaseReq) (*pb.Empty, error) {
	l := aiknowledgeservicelogic.NewUpdateKnowledgeBaseLogic(ctx, s.svcCtx)
	return l.UpdateKnowledgeBase(in)
}

// 删除知识库，并由实现层清理关联文档和索引。
func (s *AiKnowledgeServiceServer) DeleteKnowledgeBase(ctx context.Context, in *pb.DeleteKnowledgeBaseReq) (*pb.Empty, error) {
	l := aiknowledgeservicelogic.NewDeleteKnowledgeBaseLogic(ctx, s.svcCtx)
	return l.DeleteKnowledgeBase(in)
}

// 查询知识库详情。
func (s *AiKnowledgeServiceServer) GetKnowledgeBase(ctx context.Context, in *pb.GetKnowledgeBaseReq) (*pb.KnowledgeBaseItem, error) {
	l := aiknowledgeservicelogic.NewGetKnowledgeBaseLogic(ctx, s.svcCtx)
	return l.GetKnowledgeBase(in)
}

// 查询当前用户可访问的知识库列表。
func (s *AiKnowledgeServiceServer) ListKnowledgeBase(ctx context.Context, in *pb.ListKnowledgeBaseReq) (*pb.ListKnowledgeBaseResp, error) {
	l := aiknowledgeservicelogic.NewListKnowledgeBaseLogic(ctx, s.svcCtx)
	return l.ListKnowledgeBase(in)
}

// 查询公共知识库成员列表。
func (s *AiKnowledgeServiceServer) ListKbMember(ctx context.Context, in *pb.ListKbMemberReq) (*pb.ListKbMemberResp, error) {
	l := aiknowledgeservicelogic.NewListKbMemberLogic(ctx, s.svcCtx)
	return l.ListKbMember(in)
}

// 添加公共知识库成员并授予角色。
func (s *AiKnowledgeServiceServer) AddKbMember(ctx context.Context, in *pb.AddKbMemberReq) (*pb.Empty, error) {
	l := aiknowledgeservicelogic.NewAddKbMemberLogic(ctx, s.svcCtx)
	return l.AddKbMember(in)
}

// 更新公共知识库成员角色。
func (s *AiKnowledgeServiceServer) UpdateKbMember(ctx context.Context, in *pb.UpdateKbMemberReq) (*pb.Empty, error) {
	l := aiknowledgeservicelogic.NewUpdateKbMemberLogic(ctx, s.svcCtx)
	return l.UpdateKbMember(in)
}

// 移除公共知识库成员。
func (s *AiKnowledgeServiceServer) RemoveKbMember(ctx context.Context, in *pb.RemoveKbMemberReq) (*pb.Empty, error) {
	l := aiknowledgeservicelogic.NewRemoveKbMemberLogic(ctx, s.svcCtx)
	return l.RemoveKbMember(in)
}

// 将文档写入知识库并触发解析、分块、向量化和索引。
func (s *AiKnowledgeServiceServer) IngestDocument(ctx context.Context, in *pb.IngestDocumentReq) (*pb.TaskResp, error) {
	l := aiknowledgeservicelogic.NewIngestDocumentLogic(ctx, s.svcCtx)
	return l.IngestDocument(in)
}

// 查询知识库文档列表。
func (s *AiKnowledgeServiceServer) ListDocument(ctx context.Context, in *pb.ListDocumentReq) (*pb.ListDocumentResp, error) {
	l := aiknowledgeservicelogic.NewListDocumentLogic(ctx, s.svcCtx)
	return l.ListDocument(in)
}

func (s *AiKnowledgeServiceServer) CheckDocumentImportCandidates(ctx context.Context, in *pb.CheckDocumentImportCandidatesReq) (*pb.CheckDocumentImportCandidatesResp, error) {
	l := aiknowledgeservicelogic.NewCheckDocumentImportCandidatesLogic(ctx, s.svcCtx)
	return l.CheckDocumentImportCandidates(in)
}

// 查询文档元数据和入库状态。
func (s *AiKnowledgeServiceServer) GetDocument(ctx context.Context, in *pb.GetDocumentReq) (*pb.DocumentItem, error) {
	l := aiknowledgeservicelogic.NewGetDocumentLogic(ctx, s.svcCtx)
	return l.GetDocument(in)
}

// 删除知识库文档，并由实现层清理 chunk、向量和 ES 索引。
func (s *AiKnowledgeServiceServer) DeleteDocument(ctx context.Context, in *pb.DeleteDocumentReq) (*pb.Empty, error) {
	l := aiknowledgeservicelogic.NewDeleteDocumentLogic(ctx, s.svcCtx)
	return l.DeleteDocument(in)
}

// 重新构建指定文档的向量和全文索引。
func (s *AiKnowledgeServiceServer) RebuildDocumentIndex(ctx context.Context, in *pb.RebuildDocumentIndexReq) (*pb.TaskResp, error) {
	l := aiknowledgeservicelogic.NewRebuildDocumentIndexLogic(ctx, s.svcCtx)
	return l.RebuildDocumentIndex(in)
}

// 执行知识库检索，支持 quick/deep 模式和不同检索范围。
func (s *AiKnowledgeServiceServer) SearchKnowledge(ctx context.Context, in *pb.SearchKnowledgeReq) (*pb.SearchKnowledgeResp, error) {
	l := aiknowledgeservicelogic.NewSearchKnowledgeLogic(ctx, s.svcCtx)
	return l.SearchKnowledge(in)
}
