// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"context"

	"ai-copilot-platform/ai-rpc/internal/logic/aisecurityservice"
	"ai-copilot-platform/ai-rpc/internal/svc"
	"ai-copilot-platform/ai-rpc/pb"
)

type AiSecurityServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiSecurityServiceServer
}

func NewAiSecurityServiceServer(svcCtx *svc.ServiceContext) *AiSecurityServiceServer {
	return &AiSecurityServiceServer{
		svcCtx: svcCtx,
	}
}

// 检索 SSH 原始日志。
func (s *AiSecurityServiceServer) SearchSecurityLogs(ctx context.Context, in *pb.SearchSecurityLogsReq) (*pb.SecurityLogSearchResp, error) {
	l := aisecurityservicelogic.NewSearchSecurityLogsLogic(ctx, s.svcCtx)
	return l.SearchSecurityLogs(in)
}

// 分析原始日志并生成结构化安全事件和告警摘要。
func (s *AiSecurityServiceServer) AnalyzeSecurityEvents(ctx context.Context, in *pb.AnalyzeSecurityEventsReq) (*pb.AnalyzeSecurityEventsResp, error) {
	l := aisecurityservicelogic.NewAnalyzeSecurityEventsLogic(ctx, s.svcCtx)
	return l.AnalyzeSecurityEvents(in)
}

// 查询结构化安全事件列表。
func (s *AiSecurityServiceServer) ListSecurityEvents(ctx context.Context, in *pb.ListSecurityEventsReq) (*pb.ListSecurityEventsResp, error) {
	l := aisecurityservicelogic.NewListSecurityEventsLogic(ctx, s.svcCtx)
	return l.ListSecurityEvents(in)
}

// 查询安全告警列表。
func (s *AiSecurityServiceServer) ListSecurityAlerts(ctx context.Context, in *pb.ListSecurityAlertsReq) (*pb.ListSecurityAlertsResp, error) {
	l := aisecurityservicelogic.NewListSecurityAlertsLogic(ctx, s.svcCtx)
	return l.ListSecurityAlerts(in)
}

// 更新安全告警处理状态。
func (s *AiSecurityServiceServer) UpdateSecurityAlertStatus(ctx context.Context, in *pb.UpdateSecurityAlertStatusReq) (*pb.Empty, error) {
	l := aisecurityservicelogic.NewUpdateSecurityAlertStatusLogic(ctx, s.svcCtx)
	return l.UpdateSecurityAlertStatus(in)
}
