// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package aiobservabilityservice

import (
	"context"

	"ai-copilot-platform/ai-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetLlmTraceReq     = pb.GetLlmTraceReq
	GetTokenStatsReq   = pb.GetTokenStatsReq
	ListLlmCallLogReq  = pb.ListLlmCallLogReq
	ListLlmCallLogResp = pb.ListLlmCallLogResp
	LlmTraceResp       = pb.LlmTraceResp
	TokenStatsResp     = pb.TokenStatsResp

	AiObservabilityService interface {
		// 查询指定 traceId 下的 LLM 调用链路。
		GetLlmTrace(ctx context.Context, in *GetLlmTraceReq, opts ...grpc.CallOption) (*LlmTraceResp, error)
		// 分页查询 LLM 调用日志。
		ListLlmCallLog(ctx context.Context, in *ListLlmCallLogReq, opts ...grpc.CallOption) (*ListLlmCallLogResp, error)
		// 查询当前用户在指定范围内的 token 用量统计。
		GetTokenStats(ctx context.Context, in *GetTokenStatsReq, opts ...grpc.CallOption) (*TokenStatsResp, error)
	}

	defaultAiObservabilityService struct {
		cli zrpc.Client
	}
)

func NewAiObservabilityService(cli zrpc.Client) AiObservabilityService {
	return &defaultAiObservabilityService{
		cli: cli,
	}
}

// 查询指定 traceId 下的 LLM 调用链路。
func (m *defaultAiObservabilityService) GetLlmTrace(ctx context.Context, in *GetLlmTraceReq, opts ...grpc.CallOption) (*LlmTraceResp, error) {
	client := pb.NewAiObservabilityServiceClient(m.cli.Conn())
	return client.GetLlmTrace(ctx, in, opts...)
}

// 分页查询 LLM 调用日志。
func (m *defaultAiObservabilityService) ListLlmCallLog(ctx context.Context, in *ListLlmCallLogReq, opts ...grpc.CallOption) (*ListLlmCallLogResp, error) {
	client := pb.NewAiObservabilityServiceClient(m.cli.Conn())
	return client.ListLlmCallLog(ctx, in, opts...)
}

// 查询当前用户在指定范围内的 token 用量统计。
func (m *defaultAiObservabilityService) GetTokenStats(ctx context.Context, in *GetTokenStatsReq, opts ...grpc.CallOption) (*TokenStatsResp, error) {
	client := pb.NewAiObservabilityServiceClient(m.cli.Conn())
	return client.GetTokenStats(ctx, in, opts...)
}
