// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package aiknowledgeservice

import (
	"context"

	"ai-copilot-platform/ai-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddKbMemberReq                    = pb.AddKbMemberReq
	CheckDocumentImportCandidatesReq  = pb.CheckDocumentImportCandidatesReq
	CheckDocumentImportCandidatesResp = pb.CheckDocumentImportCandidatesResp
	CreateDomainReq                   = pb.CreateDomainReq
	CreateDomainResp                  = pb.CreateDomainResp
	CreateKnowledgeBaseReq            = pb.CreateKnowledgeBaseReq
	CreateKnowledgeBaseResp           = pb.CreateKnowledgeBaseResp
	DeleteDocumentReq                 = pb.DeleteDocumentReq
	DeleteDomainReq                   = pb.DeleteDomainReq
	DeleteKnowledgeBaseReq            = pb.DeleteKnowledgeBaseReq
	DocumentItem                      = pb.DocumentItem
	Empty                             = pb.Empty
	GetDocumentReq                    = pb.GetDocumentReq
	GetKnowledgeBaseReq               = pb.GetKnowledgeBaseReq
	IngestDocumentReq                 = pb.IngestDocumentReq
	KnowledgeBaseItem                 = pb.KnowledgeBaseItem
	ListDocumentReq                   = pb.ListDocumentReq
	ListDocumentResp                  = pb.ListDocumentResp
	ListDomainReq                     = pb.ListDomainReq
	ListDomainResp                    = pb.ListDomainResp
	ListKbMemberReq                   = pb.ListKbMemberReq
	ListKbMemberResp                  = pb.ListKbMemberResp
	ListKnowledgeBaseReq              = pb.ListKnowledgeBaseReq
	ListKnowledgeBaseResp             = pb.ListKnowledgeBaseResp
	RebuildDocumentIndexReq           = pb.RebuildDocumentIndexReq
	RemoveKbMemberReq                 = pb.RemoveKbMemberReq
	SearchKnowledgeReq                = pb.SearchKnowledgeReq
	SearchKnowledgeResp               = pb.SearchKnowledgeResp
	TaskResp                          = pb.TaskResp
	UpdateDomainReq                   = pb.UpdateDomainReq
	UpdateKbMemberReq                 = pb.UpdateKbMemberReq
	UpdateKnowledgeBaseReq            = pb.UpdateKnowledgeBaseReq

	AiKnowledgeService interface {
		// 创建公共知识库领域。
		CreateDomain(ctx context.Context, in *CreateDomainReq, opts ...grpc.CallOption) (*CreateDomainResp, error)
		// 更新公共知识库领域基础信息。
		UpdateDomain(ctx context.Context, in *UpdateDomainReq, opts ...grpc.CallOption) (*Empty, error)
		// 删除公共知识库领域。
		DeleteDomain(ctx context.Context, in *DeleteDomainReq, opts ...grpc.CallOption) (*Empty, error)
		// 查询公共知识库领域列表。
		ListDomain(ctx context.Context, in *ListDomainReq, opts ...grpc.CallOption) (*ListDomainResp, error)
		// 创建个人或公共知识库。
		CreateKnowledgeBase(ctx context.Context, in *CreateKnowledgeBaseReq, opts ...grpc.CallOption) (*CreateKnowledgeBaseResp, error)
		// 更新知识库名称、描述、领域、可见性或状态。
		UpdateKnowledgeBase(ctx context.Context, in *UpdateKnowledgeBaseReq, opts ...grpc.CallOption) (*Empty, error)
		// 删除知识库，并由实现层清理关联文档和索引。
		DeleteKnowledgeBase(ctx context.Context, in *DeleteKnowledgeBaseReq, opts ...grpc.CallOption) (*Empty, error)
		// 查询知识库详情。
		GetKnowledgeBase(ctx context.Context, in *GetKnowledgeBaseReq, opts ...grpc.CallOption) (*KnowledgeBaseItem, error)
		// 查询当前用户可访问的知识库列表。
		ListKnowledgeBase(ctx context.Context, in *ListKnowledgeBaseReq, opts ...grpc.CallOption) (*ListKnowledgeBaseResp, error)
		// 查询公共知识库成员列表。
		ListKbMember(ctx context.Context, in *ListKbMemberReq, opts ...grpc.CallOption) (*ListKbMemberResp, error)
		// 添加公共知识库成员并授予角色。
		AddKbMember(ctx context.Context, in *AddKbMemberReq, opts ...grpc.CallOption) (*Empty, error)
		// 更新公共知识库成员角色。
		UpdateKbMember(ctx context.Context, in *UpdateKbMemberReq, opts ...grpc.CallOption) (*Empty, error)
		// 移除公共知识库成员。
		RemoveKbMember(ctx context.Context, in *RemoveKbMemberReq, opts ...grpc.CallOption) (*Empty, error)
		// 将文档写入知识库并触发解析、分块、向量化和索引。
		IngestDocument(ctx context.Context, in *IngestDocumentReq, opts ...grpc.CallOption) (*TaskResp, error)
		// 查询知识库文档列表。
		ListDocument(ctx context.Context, in *ListDocumentReq, opts ...grpc.CallOption) (*ListDocumentResp, error)
		CheckDocumentImportCandidates(ctx context.Context, in *CheckDocumentImportCandidatesReq, opts ...grpc.CallOption) (*CheckDocumentImportCandidatesResp, error)
		// 查询文档元数据和入库状态。
		GetDocument(ctx context.Context, in *GetDocumentReq, opts ...grpc.CallOption) (*DocumentItem, error)
		// 删除知识库文档，并由实现层清理 chunk、向量和 ES 索引。
		DeleteDocument(ctx context.Context, in *DeleteDocumentReq, opts ...grpc.CallOption) (*Empty, error)
		// 重新构建指定文档的向量和全文索引。
		RebuildDocumentIndex(ctx context.Context, in *RebuildDocumentIndexReq, opts ...grpc.CallOption) (*TaskResp, error)
		// 执行知识库检索，支持 quick/deep 模式和不同检索范围。
		SearchKnowledge(ctx context.Context, in *SearchKnowledgeReq, opts ...grpc.CallOption) (*SearchKnowledgeResp, error)
	}

	defaultAiKnowledgeService struct {
		cli zrpc.Client
	}
)

func NewAiKnowledgeService(cli zrpc.Client) AiKnowledgeService {
	return &defaultAiKnowledgeService{
		cli: cli,
	}
}

// 创建公共知识库领域。
func (m *defaultAiKnowledgeService) CreateDomain(ctx context.Context, in *CreateDomainReq, opts ...grpc.CallOption) (*CreateDomainResp, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.CreateDomain(ctx, in, opts...)
}

// 更新公共知识库领域基础信息。
func (m *defaultAiKnowledgeService) UpdateDomain(ctx context.Context, in *UpdateDomainReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.UpdateDomain(ctx, in, opts...)
}

// 删除公共知识库领域。
func (m *defaultAiKnowledgeService) DeleteDomain(ctx context.Context, in *DeleteDomainReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.DeleteDomain(ctx, in, opts...)
}

// 查询公共知识库领域列表。
func (m *defaultAiKnowledgeService) ListDomain(ctx context.Context, in *ListDomainReq, opts ...grpc.CallOption) (*ListDomainResp, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.ListDomain(ctx, in, opts...)
}

// 创建个人或公共知识库。
func (m *defaultAiKnowledgeService) CreateKnowledgeBase(ctx context.Context, in *CreateKnowledgeBaseReq, opts ...grpc.CallOption) (*CreateKnowledgeBaseResp, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.CreateKnowledgeBase(ctx, in, opts...)
}

// 更新知识库名称、描述、领域、可见性或状态。
func (m *defaultAiKnowledgeService) UpdateKnowledgeBase(ctx context.Context, in *UpdateKnowledgeBaseReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.UpdateKnowledgeBase(ctx, in, opts...)
}

// 删除知识库，并由实现层清理关联文档和索引。
func (m *defaultAiKnowledgeService) DeleteKnowledgeBase(ctx context.Context, in *DeleteKnowledgeBaseReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.DeleteKnowledgeBase(ctx, in, opts...)
}

// 查询知识库详情。
func (m *defaultAiKnowledgeService) GetKnowledgeBase(ctx context.Context, in *GetKnowledgeBaseReq, opts ...grpc.CallOption) (*KnowledgeBaseItem, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.GetKnowledgeBase(ctx, in, opts...)
}

// 查询当前用户可访问的知识库列表。
func (m *defaultAiKnowledgeService) ListKnowledgeBase(ctx context.Context, in *ListKnowledgeBaseReq, opts ...grpc.CallOption) (*ListKnowledgeBaseResp, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.ListKnowledgeBase(ctx, in, opts...)
}

// 查询公共知识库成员列表。
func (m *defaultAiKnowledgeService) ListKbMember(ctx context.Context, in *ListKbMemberReq, opts ...grpc.CallOption) (*ListKbMemberResp, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.ListKbMember(ctx, in, opts...)
}

// 添加公共知识库成员并授予角色。
func (m *defaultAiKnowledgeService) AddKbMember(ctx context.Context, in *AddKbMemberReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.AddKbMember(ctx, in, opts...)
}

// 更新公共知识库成员角色。
func (m *defaultAiKnowledgeService) UpdateKbMember(ctx context.Context, in *UpdateKbMemberReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.UpdateKbMember(ctx, in, opts...)
}

// 移除公共知识库成员。
func (m *defaultAiKnowledgeService) RemoveKbMember(ctx context.Context, in *RemoveKbMemberReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.RemoveKbMember(ctx, in, opts...)
}

// 将文档写入知识库并触发解析、分块、向量化和索引。
func (m *defaultAiKnowledgeService) IngestDocument(ctx context.Context, in *IngestDocumentReq, opts ...grpc.CallOption) (*TaskResp, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.IngestDocument(ctx, in, opts...)
}

// 查询知识库文档列表。
func (m *defaultAiKnowledgeService) ListDocument(ctx context.Context, in *ListDocumentReq, opts ...grpc.CallOption) (*ListDocumentResp, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.ListDocument(ctx, in, opts...)
}

func (m *defaultAiKnowledgeService) CheckDocumentImportCandidates(ctx context.Context, in *CheckDocumentImportCandidatesReq, opts ...grpc.CallOption) (*CheckDocumentImportCandidatesResp, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.CheckDocumentImportCandidates(ctx, in, opts...)
}

// 查询文档元数据和入库状态。
func (m *defaultAiKnowledgeService) GetDocument(ctx context.Context, in *GetDocumentReq, opts ...grpc.CallOption) (*DocumentItem, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.GetDocument(ctx, in, opts...)
}

// 删除知识库文档，并由实现层清理 chunk、向量和 ES 索引。
func (m *defaultAiKnowledgeService) DeleteDocument(ctx context.Context, in *DeleteDocumentReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.DeleteDocument(ctx, in, opts...)
}

// 重新构建指定文档的向量和全文索引。
func (m *defaultAiKnowledgeService) RebuildDocumentIndex(ctx context.Context, in *RebuildDocumentIndexReq, opts ...grpc.CallOption) (*TaskResp, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.RebuildDocumentIndex(ctx, in, opts...)
}

// 执行知识库检索，支持 quick/deep 模式和不同检索范围。
func (m *defaultAiKnowledgeService) SearchKnowledge(ctx context.Context, in *SearchKnowledgeReq, opts ...grpc.CallOption) (*SearchKnowledgeResp, error) {
	client := pb.NewAiKnowledgeServiceClient(m.cli.Conn())
	return client.SearchKnowledge(ctx, in, opts...)
}
