// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"context"

	"ai-copilot-platform/ai-rpc/internal/logic/aiwindmetadataservice"
	"ai-copilot-platform/ai-rpc/internal/svc"
	"ai-copilot-platform/ai-rpc/pb"
)

type AiWindMetadataServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiWindMetadataServiceServer
}

func NewAiWindMetadataServiceServer(svcCtx *svc.ServiceContext) *AiWindMetadataServiceServer {
	return &AiWindMetadataServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AiWindMetadataServiceServer) ListFarms(ctx context.Context, in *pb.ListWindFarmReq) (*pb.ListWindFarmResp, error) {
	l := aiwindmetadataservicelogic.NewListFarmsLogic(ctx, s.svcCtx)
	return l.ListFarms(in)
}

func (s *AiWindMetadataServiceServer) ListTurbines(ctx context.Context, in *pb.ListWindTurbineReq) (*pb.ListWindTurbineResp, error) {
	l := aiwindmetadataservicelogic.NewListTurbinesLogic(ctx, s.svcCtx)
	return l.ListTurbines(in)
}

func (s *AiWindMetadataServiceServer) ListDevices(ctx context.Context, in *pb.ListWindDeviceReq) (*pb.ListWindDeviceResp, error) {
	l := aiwindmetadataservicelogic.NewListDevicesLogic(ctx, s.svcCtx)
	return l.ListDevices(in)
}
