// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"context"

	"ai-copilot-platform/ai-rpc/internal/logic/aiwindreportservice"
	"ai-copilot-platform/ai-rpc/internal/svc"
	"ai-copilot-platform/ai-rpc/pb"
)

type AiWindReportServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiWindReportServiceServer
}

func NewAiWindReportServiceServer(svcCtx *svc.ServiceContext) *AiWindReportServiceServer {
	return &AiWindReportServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AiWindReportServiceServer) GenerateHealthReport(ctx context.Context, in *pb.WindHealthReportReq) (*pb.WindScaffoldResp, error) {
	l := aiwindreportservicelogic.NewGenerateHealthReportLogic(ctx, s.svcCtx)
	return l.GenerateHealthReport(in)
}

func (s *AiWindReportServiceServer) GetHealthReport(ctx context.Context, in *pb.WindHealthReportGetReq) (*pb.WindScaffoldResp, error) {
	l := aiwindreportservicelogic.NewGetHealthReportLogic(ctx, s.svcCtx)
	return l.GetHealthReport(in)
}
