// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiConversationFieldNames          = builder.RawFieldNames(&AiConversation{}, true)
	aiConversationRows                = strings.Join(aiConversationFieldNames, ",")
	aiConversationRowsExpectAutoSet   = strings.Join(stringx.Remove(aiConversationFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aiConversationRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aiConversationFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aiConversationModel interface {
		Insert(ctx context.Context, data *AiConversation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiConversation, error)
		Update(ctx context.Context, data *AiConversation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiConversationModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiConversation struct {
		Id        int64         `db:"id"`         // 主键ID，自增
		UserId    int64         `db:"user_id"`    // 会话所属用户ID
		KbId      sql.NullInt64 `db:"kb_id"`      // 关联知识库ID，可空（不在知识库上下文中的对话）
		Title     string        `db:"title"`      // 会话标题
		CreatedAt time.Time     `db:"created_at"` // 创建时间
		UpdatedAt time.Time     `db:"updated_at"` // 更新时间
	}
)

func newAiConversationModel(conn sqlx.SqlConn) *defaultAiConversationModel {
	return &defaultAiConversationModel{
		conn:  conn,
		table: `"public"."ai_conversation"`,
	}
}

func (m *defaultAiConversationModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiConversationModel) FindOne(ctx context.Context, id int64) (*AiConversation, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aiConversationRows, m.table)
	var resp AiConversation
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiConversationModel) Insert(ctx context.Context, data *AiConversation) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, aiConversationRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.KbId, data.Title)
	return ret, err
}

func (m *defaultAiConversationModel) Update(ctx context.Context, data *AiConversation) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aiConversationRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.KbId, data.Title)
	return err
}

func (m *defaultAiConversationModel) tableName() string {
	return m.table
}
