// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiDocumentParentChunkFieldNames          = builder.RawFieldNames(&AiDocumentParentChunk{}, true)
	aiDocumentParentChunkRows                = strings.Join(aiDocumentParentChunkFieldNames, ",")
	aiDocumentParentChunkRowsExpectAutoSet   = strings.Join(stringx.Remove(aiDocumentParentChunkFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aiDocumentParentChunkRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aiDocumentParentChunkFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aiDocumentParentChunkModel interface {
		Insert(ctx context.Context, data *AiDocumentParentChunk) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiDocumentParentChunk, error)
		Update(ctx context.Context, data *AiDocumentParentChunk) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiDocumentParentChunkModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiDocumentParentChunk struct {
		Id          int64     `db:"id"`           // 主键ID，自增
		DocumentId  int64     `db:"document_id"`  // 所属文档ID，外键关联ai_document，级联删除
		ParentIndex int64     `db:"parent_index"` // 父块在文档中的顺序索引
		Content     string    `db:"content"`      // 父块文本内容，800-1200中文字符，用于给LLM提供完整上下文
		TokenCount  int64     `db:"token_count"`  // 父块token数量
		CreatedAt   time.Time `db:"created_at"`   // 创建时间
	}
)

func newAiDocumentParentChunkModel(conn sqlx.SqlConn) *defaultAiDocumentParentChunkModel {
	return &defaultAiDocumentParentChunkModel{
		conn:  conn,
		table: `"public"."ai_document_parent_chunk"`,
	}
}

func (m *defaultAiDocumentParentChunkModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiDocumentParentChunkModel) FindOne(ctx context.Context, id int64) (*AiDocumentParentChunk, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aiDocumentParentChunkRows, m.table)
	var resp AiDocumentParentChunk
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiDocumentParentChunkModel) Insert(ctx context.Context, data *AiDocumentParentChunk) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, aiDocumentParentChunkRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DocumentId, data.ParentIndex, data.Content, data.TokenCount)
	return ret, err
}

func (m *defaultAiDocumentParentChunkModel) Update(ctx context.Context, data *AiDocumentParentChunk) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aiDocumentParentChunkRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.DocumentId, data.ParentIndex, data.Content, data.TokenCount)
	return err
}

func (m *defaultAiDocumentParentChunkModel) tableName() string {
	return m.table
}
