// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiDailyReportFieldNames          = builder.RawFieldNames(&AiDailyReport{}, true)
	aiDailyReportRows                = strings.Join(aiDailyReportFieldNames, ",")
	aiDailyReportRowsExpectAutoSet   = strings.Join(stringx.Remove(aiDailyReportFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aiDailyReportRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aiDailyReportFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aiDailyReportModel interface {
		Insert(ctx context.Context, data *AiDailyReport) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiDailyReport, error)
		FindOneByUserIdReportDate(ctx context.Context, userId int64, reportDate time.Time) (*AiDailyReport, error)
		Update(ctx context.Context, data *AiDailyReport) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiDailyReportModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiDailyReport struct {
		Id         int64     `db:"id"`          // 主键ID，自增
		UserId     int64     `db:"user_id"`     // 日报所属用户ID
		ReportDate time.Time `db:"report_date"` // 报告日期
		Title      string    `db:"title"`       // 日报标题
		Content    string    `db:"content"`     // 日报内容，AI生成的自然语言总结
		Metrics    string    `db:"metrics"`     // 日报指标数据，JSON格式，包含登录统计、告警统计等
		CreatedAt  time.Time `db:"created_at"`  // 创建时间
	}
)

func newAiDailyReportModel(conn sqlx.SqlConn) *defaultAiDailyReportModel {
	return &defaultAiDailyReportModel{
		conn:  conn,
		table: `"public"."ai_daily_report"`,
	}
}

func (m *defaultAiDailyReportModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiDailyReportModel) FindOne(ctx context.Context, id int64) (*AiDailyReport, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aiDailyReportRows, m.table)
	var resp AiDailyReport
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiDailyReportModel) FindOneByUserIdReportDate(ctx context.Context, userId int64, reportDate time.Time) (*AiDailyReport, error) {
	var resp AiDailyReport
	query := fmt.Sprintf("select %s from %s where user_id = $1 and report_date = $2 limit 1", aiDailyReportRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, reportDate)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiDailyReportModel) Insert(ctx context.Context, data *AiDailyReport) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, aiDailyReportRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ReportDate, data.Title, data.Content, data.Metrics)
	return ret, err
}

func (m *defaultAiDailyReportModel) Update(ctx context.Context, newData *AiDailyReport) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aiDailyReportRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.ReportDate, newData.Title, newData.Content, newData.Metrics)
	return err
}

func (m *defaultAiDailyReportModel) tableName() string {
	return m.table
}
