// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiDocumentFieldNames          = builder.RawFieldNames(&AiDocument{}, true)
	aiDocumentRows                = strings.Join(aiDocumentFieldNames, ",")
	aiDocumentRowsExpectAutoSet   = strings.Join(stringx.Remove(aiDocumentFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aiDocumentRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aiDocumentFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aiDocumentModel interface {
		Insert(ctx context.Context, data *AiDocument) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiDocument, error)
		FindOneByKbIdContentHash(ctx context.Context, kbId int64, contentHash string) (*AiDocument, error)
		Update(ctx context.Context, data *AiDocument) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiDocumentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiDocument struct {
		Id          int64     `db:"id"`           // 主键ID，自增
		KbId        int64     `db:"kb_id"`        // 所属知识库ID，外键关联ai_knowledge_base
		UploadedBy  int64     `db:"uploaded_by"`  // 上传人用户ID
		FileName    string    `db:"file_name"`    // 文件名
		FileType    string    `db:"file_type"`    // 文件类型，如md、pdf、docx等
		ContentHash string    `db:"content_hash"` // 文档内容哈希，用于去重校验，同一kb_id下不可重复
		Status      string    `db:"status"`       // 文档处理状态，pending/parsing/chunking/indexing/ready/failed
		ErrorMsg    string    `db:"error_msg"`    // 处理失败时的错误信息
		CreatedAt   time.Time `db:"created_at"`   // 创建时间
		UpdatedAt   time.Time `db:"updated_at"`   // 更新时间
	}
)

func newAiDocumentModel(conn sqlx.SqlConn) *defaultAiDocumentModel {
	return &defaultAiDocumentModel{
		conn:  conn,
		table: `"public"."ai_document"`,
	}
}

func (m *defaultAiDocumentModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiDocumentModel) FindOne(ctx context.Context, id int64) (*AiDocument, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aiDocumentRows, m.table)
	var resp AiDocument
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiDocumentModel) FindOneByKbIdContentHash(ctx context.Context, kbId int64, contentHash string) (*AiDocument, error) {
	var resp AiDocument
	query := fmt.Sprintf("select %s from %s where kb_id = $1 and content_hash = $2 limit 1", aiDocumentRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, kbId, contentHash)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiDocumentModel) Insert(ctx context.Context, data *AiDocument) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7)", m.table, aiDocumentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.KbId, data.UploadedBy, data.FileName, data.FileType, data.ContentHash, data.Status, data.ErrorMsg)
	return ret, err
}

func (m *defaultAiDocumentModel) Update(ctx context.Context, newData *AiDocument) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aiDocumentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.KbId, newData.UploadedBy, newData.FileName, newData.FileType, newData.ContentHash, newData.Status, newData.ErrorMsg)
	return err
}

func (m *defaultAiDocumentModel) tableName() string {
	return m.table
}
