// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiKnowledgeBaseFieldNames          = builder.RawFieldNames(&AiKnowledgeBase{}, true)
	aiKnowledgeBaseRows                = strings.Join(aiKnowledgeBaseFieldNames, ",")
	aiKnowledgeBaseRowsExpectAutoSet   = strings.Join(stringx.Remove(aiKnowledgeBaseFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aiKnowledgeBaseRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aiKnowledgeBaseFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aiKnowledgeBaseModel interface {
		Insert(ctx context.Context, data *AiKnowledgeBase) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiKnowledgeBase, error)
		Update(ctx context.Context, data *AiKnowledgeBase) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiKnowledgeBaseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiKnowledgeBase struct {
		Id          int64         `db:"id"`            // 主键ID，自增
		KbType      string        `db:"kb_type"`       // 知识库类型，personal=个人知识库，public=公共知识库
		OwnerUserId sql.NullInt64 `db:"owner_user_id"` // 所有者用户ID，个人知识库必填，公共知识库为空
		DomainId    sql.NullInt64 `db:"domain_id"`     // 所属领域ID，公共知识库必填，个人知识库为空
		Name        string        `db:"name"`          // 知识库名称
		Description string        `db:"description"`   // 知识库描述
		Visibility  string        `db:"visibility"`    // 可见性，private=私有，public=公开可读
		Status      int64         `db:"status"`        // 状态，1=启用，0=禁用
		CreatedBy   int64         `db:"created_by"`    // 创建人用户ID
		CreatedAt   time.Time     `db:"created_at"`    // 创建时间
		UpdatedAt   time.Time     `db:"updated_at"`    // 更新时间
	}
)

func newAiKnowledgeBaseModel(conn sqlx.SqlConn) *defaultAiKnowledgeBaseModel {
	return &defaultAiKnowledgeBaseModel{
		conn:  conn,
		table: `"public"."ai_knowledge_base"`,
	}
}

func (m *defaultAiKnowledgeBaseModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiKnowledgeBaseModel) FindOne(ctx context.Context, id int64) (*AiKnowledgeBase, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aiKnowledgeBaseRows, m.table)
	var resp AiKnowledgeBase
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiKnowledgeBaseModel) Insert(ctx context.Context, data *AiKnowledgeBase) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, aiKnowledgeBaseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.KbType, data.OwnerUserId, data.DomainId, data.Name, data.Description, data.Visibility, data.Status, data.CreatedBy)
	return ret, err
}

func (m *defaultAiKnowledgeBaseModel) Update(ctx context.Context, data *AiKnowledgeBase) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aiKnowledgeBaseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.KbType, data.OwnerUserId, data.DomainId, data.Name, data.Description, data.Visibility, data.Status, data.CreatedBy)
	return err
}

func (m *defaultAiKnowledgeBaseModel) tableName() string {
	return m.table
}
