// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiKbMemberFieldNames          = builder.RawFieldNames(&AiKbMember{}, true)
	aiKbMemberRows                = strings.Join(aiKbMemberFieldNames, ",")
	aiKbMemberRowsExpectAutoSet   = strings.Join(stringx.Remove(aiKbMemberFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aiKbMemberRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aiKbMemberFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aiKbMemberModel interface {
		Insert(ctx context.Context, data *AiKbMember) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiKbMember, error)
		FindOneByKbIdUserId(ctx context.Context, kbId int64, userId int64) (*AiKbMember, error)
		Update(ctx context.Context, data *AiKbMember) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiKbMemberModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiKbMember struct {
		Id        int64     `db:"id"`         // 主键ID，自增
		KbId      int64     `db:"kb_id"`      // 知识库ID，外键关联ai_knowledge_base，级联删除
		UserId    int64     `db:"user_id"`    // 成员用户ID
		Role      string    `db:"role"`       // 成员角色，viewer=可查看，editor=可编辑上传，manager=可管理成员
		CreatedBy int64     `db:"created_by"` // 添加该成员的用户ID
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newAiKbMemberModel(conn sqlx.SqlConn) *defaultAiKbMemberModel {
	return &defaultAiKbMemberModel{
		conn:  conn,
		table: `"public"."ai_kb_member"`,
	}
}

func (m *defaultAiKbMemberModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiKbMemberModel) FindOne(ctx context.Context, id int64) (*AiKbMember, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aiKbMemberRows, m.table)
	var resp AiKbMember
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiKbMemberModel) FindOneByKbIdUserId(ctx context.Context, kbId int64, userId int64) (*AiKbMember, error) {
	var resp AiKbMember
	query := fmt.Sprintf("select %s from %s where kb_id = $1 and user_id = $2 limit 1", aiKbMemberRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, kbId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiKbMemberModel) Insert(ctx context.Context, data *AiKbMember) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, aiKbMemberRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.KbId, data.UserId, data.Role, data.CreatedBy)
	return ret, err
}

func (m *defaultAiKbMemberModel) Update(ctx context.Context, newData *AiKbMember) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aiKbMemberRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.KbId, newData.UserId, newData.Role, newData.CreatedBy)
	return err
}

func (m *defaultAiKbMemberModel) tableName() string {
	return m.table
}
