// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiKbDomainFieldNames          = builder.RawFieldNames(&AiKbDomain{}, true)
	aiKbDomainRows                = strings.Join(aiKbDomainFieldNames, ",")
	aiKbDomainRowsExpectAutoSet   = strings.Join(stringx.Remove(aiKbDomainFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aiKbDomainRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aiKbDomainFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aiKbDomainModel interface {
		Insert(ctx context.Context, data *AiKbDomain) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiKbDomain, error)
		FindOneByCode(ctx context.Context, code string) (*AiKbDomain, error)
		Update(ctx context.Context, data *AiKbDomain) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiKbDomainModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiKbDomain struct {
		Id          int64     `db:"id"`          // 主键ID，自增
		Name        string    `db:"name"`        // 领域名称，如"后端开发"、"运维部署"
		Code        string    `db:"code"`        // 领域编码，唯一标识，如"backend"、"ops"
		Description string    `db:"description"` // 领域描述
		Sort        int64     `db:"sort"`        // 排序权重，值越小越靠前
		Status      int64     `db:"status"`      // 状态，1=启用，0=禁用
		CreatedBy   int64     `db:"created_by"`  // 创建人用户ID
		CreatedAt   time.Time `db:"created_at"`  // 创建时间
		UpdatedAt   time.Time `db:"updated_at"`  // 更新时间
	}
)

func newAiKbDomainModel(conn sqlx.SqlConn) *defaultAiKbDomainModel {
	return &defaultAiKbDomainModel{
		conn:  conn,
		table: `"public"."ai_kb_domain"`,
	}
}

func (m *defaultAiKbDomainModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiKbDomainModel) FindOne(ctx context.Context, id int64) (*AiKbDomain, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aiKbDomainRows, m.table)
	var resp AiKbDomain
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiKbDomainModel) FindOneByCode(ctx context.Context, code string) (*AiKbDomain, error) {
	var resp AiKbDomain
	query := fmt.Sprintf("select %s from %s where code = $1 limit 1", aiKbDomainRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiKbDomainModel) Insert(ctx context.Context, data *AiKbDomain) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, aiKbDomainRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Code, data.Description, data.Sort, data.Status, data.CreatedBy)
	return ret, err
}

func (m *defaultAiKbDomainModel) Update(ctx context.Context, newData *AiKbDomain) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aiKbDomainRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.Name, newData.Code, newData.Description, newData.Sort, newData.Status, newData.CreatedBy)
	return err
}

func (m *defaultAiKbDomainModel) tableName() string {
	return m.table
}
