// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiLlmCallLogFieldNames          = builder.RawFieldNames(&AiLlmCallLog{}, true)
	aiLlmCallLogRows                = strings.Join(aiLlmCallLogFieldNames, ",")
	aiLlmCallLogRowsExpectAutoSet   = strings.Join(stringx.Remove(aiLlmCallLogFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aiLlmCallLogRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aiLlmCallLogFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aiLlmCallLogModel interface {
		Insert(ctx context.Context, data *AiLlmCallLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiLlmCallLog, error)
		Update(ctx context.Context, data *AiLlmCallLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiLlmCallLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiLlmCallLog struct {
		Id               int64         `db:"id"`                // 主键ID，自增
		UserId           sql.NullInt64 `db:"user_id"`           // 调用用户ID，可空（系统调用时为空）
		TraceId          string        `db:"trace_id"`          // 链路追踪ID，用于关联整个请求链路
		Provider         string        `db:"provider"`          // 模型提供商
		Model            string        `db:"model"`             // 模型名称
		Prompt           string        `db:"prompt"`            // 输入提示文本
		PromptTokens     int64         `db:"prompt_tokens"`     // 输入token数量
		CompletionTokens int64         `db:"completion_tokens"` // 输出token数量
		LatencyMs        int64         `db:"latency_ms"`        // 调用延迟（毫秒）
		Status           string        `db:"status"`            // 调用状态，success/failed
		ErrorMsg         string        `db:"error_msg"`         // 失败时的错误信息
		CreatedAt        time.Time     `db:"created_at"`        // 创建时间
	}
)

func newAiLlmCallLogModel(conn sqlx.SqlConn) *defaultAiLlmCallLogModel {
	return &defaultAiLlmCallLogModel{
		conn:  conn,
		table: `"public"."ai_llm_call_log"`,
	}
}

func (m *defaultAiLlmCallLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiLlmCallLogModel) FindOne(ctx context.Context, id int64) (*AiLlmCallLog, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aiLlmCallLogRows, m.table)
	var resp AiLlmCallLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiLlmCallLogModel) Insert(ctx context.Context, data *AiLlmCallLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, aiLlmCallLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TraceId, data.Provider, data.Model, data.Prompt, data.PromptTokens, data.CompletionTokens, data.LatencyMs, data.Status, data.ErrorMsg)
	return ret, err
}

func (m *defaultAiLlmCallLogModel) Update(ctx context.Context, data *AiLlmCallLog) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aiLlmCallLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.TraceId, data.Provider, data.Model, data.Prompt, data.PromptTokens, data.CompletionTokens, data.LatencyMs, data.Status, data.ErrorMsg)
	return err
}

func (m *defaultAiLlmCallLogModel) tableName() string {
	return m.table
}
