// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiMessageFieldNames          = builder.RawFieldNames(&AiMessage{}, true)
	aiMessageRows                = strings.Join(aiMessageFieldNames, ",")
	aiMessageRowsExpectAutoSet   = strings.Join(stringx.Remove(aiMessageFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aiMessageRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aiMessageFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aiMessageModel interface {
		Insert(ctx context.Context, data *AiMessage) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiMessage, error)
		Update(ctx context.Context, data *AiMessage) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiMessageModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiMessage struct {
		Id             int64     `db:"id"`              // 主键ID，自增
		ConversationId int64     `db:"conversation_id"` // 所属会话ID，外键关联ai_conversation，级联删除
		Role           string    `db:"role"`            // 消息角色，user/assistant/tool/system
		Content        string    `db:"content"`         // 消息内容
		Citations      string    `db:"citations"`       // 引用来源，JSON数组，包含document_id、chunk_id、snippet等
		TraceId        string    `db:"trace_id"`        // 链路追踪ID，用于关联LLM调用日志
		CreatedAt      time.Time `db:"created_at"`      // 创建时间
	}
)

func newAiMessageModel(conn sqlx.SqlConn) *defaultAiMessageModel {
	return &defaultAiMessageModel{
		conn:  conn,
		table: `"public"."ai_message"`,
	}
}

func (m *defaultAiMessageModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiMessageModel) FindOne(ctx context.Context, id int64) (*AiMessage, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aiMessageRows, m.table)
	var resp AiMessage
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiMessageModel) Insert(ctx context.Context, data *AiMessage) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, aiMessageRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ConversationId, data.Role, data.Content, data.Citations, data.TraceId)
	return ret, err
}

func (m *defaultAiMessageModel) Update(ctx context.Context, data *AiMessage) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aiMessageRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.ConversationId, data.Role, data.Content, data.Citations, data.TraceId)
	return err
}

func (m *defaultAiMessageModel) tableName() string {
	return m.table
}
