// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiModelConfigFieldNames          = builder.RawFieldNames(&AiModelConfig{}, true)
	aiModelConfigRows                = strings.Join(aiModelConfigFieldNames, ",")
	aiModelConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(aiModelConfigFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aiModelConfigRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aiModelConfigFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aiModelConfigModel interface {
		Insert(ctx context.Context, data *AiModelConfig) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiModelConfig, error)
		Update(ctx context.Context, data *AiModelConfig) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiModelConfigModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiModelConfig struct {
		Id        int64     `db:"id"`          // 主键ID，自增
		Provider  string    `db:"provider"`    // 模型提供商，如openai/azure/zhipu等
		ModelName string    `db:"model_name"`  // 模型名称，如gpt-4/text-embedding-3-small等
		ModelType string    `db:"model_type"`  // 模型类型，chat/embedding/rerank
		BaseUrl   string    `db:"base_url"`    // API基础地址
		ApiKeyRef string    `db:"api_key_ref"` // API密钥引用标识，实际密钥存储在环境变量或密钥管理服务中
		Enabled   bool      `db:"enabled"`     // 是否启用，true=启用，false=禁用
		CreatedAt time.Time `db:"created_at"`  // 创建时间
	}
)

func newAiModelConfigModel(conn sqlx.SqlConn) *defaultAiModelConfigModel {
	return &defaultAiModelConfigModel{
		conn:  conn,
		table: `"public"."ai_model_config"`,
	}
}

func (m *defaultAiModelConfigModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiModelConfigModel) FindOne(ctx context.Context, id int64) (*AiModelConfig, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aiModelConfigRows, m.table)
	var resp AiModelConfig
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiModelConfigModel) Insert(ctx context.Context, data *AiModelConfig) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, aiModelConfigRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Provider, data.ModelName, data.ModelType, data.BaseUrl, data.ApiKeyRef, data.Enabled)
	return ret, err
}

func (m *defaultAiModelConfigModel) Update(ctx context.Context, data *AiModelConfig) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aiModelConfigRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Provider, data.ModelName, data.ModelType, data.BaseUrl, data.ApiKeyRef, data.Enabled)
	return err
}

func (m *defaultAiModelConfigModel) tableName() string {
	return m.table
}
