// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiMaintenanceTicketDraftFieldNames          = builder.RawFieldNames(&AiMaintenanceTicketDraft{}, true)
	aiMaintenanceTicketDraftRows                = strings.Join(aiMaintenanceTicketDraftFieldNames, ",")
	aiMaintenanceTicketDraftRowsExpectAutoSet   = strings.Join(stringx.Remove(aiMaintenanceTicketDraftFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aiMaintenanceTicketDraftRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aiMaintenanceTicketDraftFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aiMaintenanceTicketDraftModel interface {
		Insert(ctx context.Context, data *AiMaintenanceTicketDraft) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiMaintenanceTicketDraft, error)
		Update(ctx context.Context, data *AiMaintenanceTicketDraft) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiMaintenanceTicketDraftModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiMaintenanceTicketDraft struct {
		Id        int64     `db:"id"`
		UserId    int64     `db:"user_id"`
		TraceId   string    `db:"trace_id"`
		FarmCode  string    `db:"farm_code"`
		TowerCode string    `db:"tower_code"`
		AlarmCode string    `db:"alarm_code"`
		Title     string    `db:"title"`
		Content   string    `db:"content"`
		Evidence  string    `db:"evidence"`
		Status    string    `db:"status"`
		CreatedAt time.Time `db:"created_at"`
	}
)

func newAiMaintenanceTicketDraftModel(conn sqlx.SqlConn) *defaultAiMaintenanceTicketDraftModel {
	return &defaultAiMaintenanceTicketDraftModel{
		conn:  conn,
		table: `"public"."ai_maintenance_ticket_draft"`,
	}
}

func (m *defaultAiMaintenanceTicketDraftModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiMaintenanceTicketDraftModel) FindOne(ctx context.Context, id int64) (*AiMaintenanceTicketDraft, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aiMaintenanceTicketDraftRows, m.table)
	var resp AiMaintenanceTicketDraft
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiMaintenanceTicketDraftModel) Insert(ctx context.Context, data *AiMaintenanceTicketDraft) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, aiMaintenanceTicketDraftRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TraceId, data.FarmCode, data.TowerCode, data.AlarmCode, data.Title, data.Content, data.Evidence, data.Status)
	return ret, err
}

func (m *defaultAiMaintenanceTicketDraftModel) Update(ctx context.Context, data *AiMaintenanceTicketDraft) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aiMaintenanceTicketDraftRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.TraceId, data.FarmCode, data.TowerCode, data.AlarmCode, data.Title, data.Content, data.Evidence, data.Status)
	return err
}

func (m *defaultAiMaintenanceTicketDraftModel) tableName() string {
	return m.table
}
