// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiSecurityAlertFieldNames          = builder.RawFieldNames(&AiSecurityAlert{}, true)
	aiSecurityAlertRows                = strings.Join(aiSecurityAlertFieldNames, ",")
	aiSecurityAlertRowsExpectAutoSet   = strings.Join(stringx.Remove(aiSecurityAlertFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aiSecurityAlertRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aiSecurityAlertFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aiSecurityAlertModel interface {
		Insert(ctx context.Context, data *AiSecurityAlert) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiSecurityAlert, error)
		Update(ctx context.Context, data *AiSecurityAlert) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiSecurityAlertModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiSecurityAlert struct {
		Id          int64        `db:"id"`            // 主键ID，自增
		UserId      int64        `db:"user_id"`       // 告警所属用户ID
		AlertType   string       `db:"alert_type"`    // 告警类型，如ssh_bruteforce/high_risk_ip等
		Severity    string       `db:"severity"`      // 严重程度，low/medium/high/critical
		Title       string       `db:"title"`         // 告警标题
		Detail      string       `db:"detail"`        // 告警详情描述
		Status      string       `db:"status"`        // 告警状态，open=待处理，ignored=已忽略，resolved=已解决
		FirstSeenAt sql.NullTime `db:"first_seen_at"` // 首次发现时间
		LastSeenAt  sql.NullTime `db:"last_seen_at"`  // 最近发现时间
		CreatedAt   time.Time    `db:"created_at"`    // 创建时间
		UpdatedAt   time.Time    `db:"updated_at"`    // 更新时间
	}
)

func newAiSecurityAlertModel(conn sqlx.SqlConn) *defaultAiSecurityAlertModel {
	return &defaultAiSecurityAlertModel{
		conn:  conn,
		table: `"public"."ai_security_alert"`,
	}
}

func (m *defaultAiSecurityAlertModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiSecurityAlertModel) FindOne(ctx context.Context, id int64) (*AiSecurityAlert, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aiSecurityAlertRows, m.table)
	var resp AiSecurityAlert
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiSecurityAlertModel) Insert(ctx context.Context, data *AiSecurityAlert) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, aiSecurityAlertRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.AlertType, data.Severity, data.Title, data.Detail, data.Status, data.FirstSeenAt, data.LastSeenAt)
	return ret, err
}

func (m *defaultAiSecurityAlertModel) Update(ctx context.Context, data *AiSecurityAlert) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aiSecurityAlertRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.AlertType, data.Severity, data.Title, data.Detail, data.Status, data.FirstSeenAt, data.LastSeenAt)
	return err
}

func (m *defaultAiSecurityAlertModel) tableName() string {
	return m.table
}
