// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiSecurityEventFieldNames          = builder.RawFieldNames(&AiSecurityEvent{}, true)
	aiSecurityEventRows                = strings.Join(aiSecurityEventFieldNames, ",")
	aiSecurityEventRowsExpectAutoSet   = strings.Join(stringx.Remove(aiSecurityEventFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aiSecurityEventRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aiSecurityEventFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aiSecurityEventModel interface {
		Insert(ctx context.Context, data *AiSecurityEvent) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiSecurityEvent, error)
		Update(ctx context.Context, data *AiSecurityEvent) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiSecurityEventModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiSecurityEvent struct {
		Id         int64        `db:"id"`          // 主键ID，自增
		UserId     int64        `db:"user_id"`     // 事件所属用户ID
		EventType  string       `db:"event_type"`  // 事件类型，如ssh_login_failed/ssh_login_success/ssh_bruteforce/high_risk_ip/abnormal_location_login
		Severity   string       `db:"severity"`    // 严重程度，low/medium/high/critical
		Ip         string       `db:"ip"`          // 来源IP地址
		Username   string       `db:"username"`    // 登录用户名
		Location   string       `db:"location"`    // 登录地理位置
		RawLog     string       `db:"raw_log"`     // 原始日志内容
		OccurredAt sql.NullTime `db:"occurred_at"` // 事件发生时间
		CreatedAt  time.Time    `db:"created_at"`  // 记录创建时间
	}
)

func newAiSecurityEventModel(conn sqlx.SqlConn) *defaultAiSecurityEventModel {
	return &defaultAiSecurityEventModel{
		conn:  conn,
		table: `"public"."ai_security_event"`,
	}
}

func (m *defaultAiSecurityEventModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiSecurityEventModel) FindOne(ctx context.Context, id int64) (*AiSecurityEvent, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aiSecurityEventRows, m.table)
	var resp AiSecurityEvent
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiSecurityEventModel) Insert(ctx context.Context, data *AiSecurityEvent) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, aiSecurityEventRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.EventType, data.Severity, data.Ip, data.Username, data.Location, data.RawLog, data.OccurredAt)
	return ret, err
}

func (m *defaultAiSecurityEventModel) Update(ctx context.Context, data *AiSecurityEvent) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aiSecurityEventRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.EventType, data.Severity, data.Ip, data.Username, data.Location, data.RawLog, data.OccurredAt)
	return err
}

func (m *defaultAiSecurityEventModel) tableName() string {
	return m.table
}
