// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aiToolCallLogFieldNames          = builder.RawFieldNames(&AiToolCallLog{}, true)
	aiToolCallLogRows                = strings.Join(aiToolCallLogFieldNames, ",")
	aiToolCallLogRowsExpectAutoSet   = strings.Join(stringx.Remove(aiToolCallLogFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aiToolCallLogRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aiToolCallLogFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aiToolCallLogModel interface {
		Insert(ctx context.Context, data *AiToolCallLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AiToolCallLog, error)
		Update(ctx context.Context, data *AiToolCallLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAiToolCallLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AiToolCallLog struct {
		Id        int64     `db:"id"`         // 主键ID，自增
		UserId    int64     `db:"user_id"`    // 调用用户ID
		TraceId   string    `db:"trace_id"`   // 链路追踪ID
		ToolName  string    `db:"tool_name"`  // 工具名称，如search_knowledge_base/query_security_events等
		Arguments string    `db:"arguments"`  // 工具调用参数，JSON格式
		Result    string    `db:"result"`     // 工具调用结果，JSON格式
		Status    string    `db:"status"`     // 调用状态，success/failed/rejected
		ErrorMsg  string    `db:"error_msg"`  // 失败时的错误信息
		LatencyMs int64     `db:"latency_ms"` // 调用延迟（毫秒）
		CreatedAt time.Time `db:"created_at"` // 创建时间
	}
)

func newAiToolCallLogModel(conn sqlx.SqlConn) *defaultAiToolCallLogModel {
	return &defaultAiToolCallLogModel{
		conn:  conn,
		table: `"public"."ai_tool_call_log"`,
	}
}

func (m *defaultAiToolCallLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAiToolCallLogModel) FindOne(ctx context.Context, id int64) (*AiToolCallLog, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aiToolCallLogRows, m.table)
	var resp AiToolCallLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAiToolCallLogModel) Insert(ctx context.Context, data *AiToolCallLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, aiToolCallLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TraceId, data.ToolName, data.Arguments, data.Result, data.Status, data.ErrorMsg, data.LatencyMs)
	return ret, err
}

func (m *defaultAiToolCallLogModel) Update(ctx context.Context, data *AiToolCallLog) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aiToolCallLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.TraceId, data.ToolName, data.Arguments, data.Result, data.Status, data.ErrorMsg, data.LatencyMs)
	return err
}

func (m *defaultAiToolCallLogModel) tableName() string {
	return m.table
}
