// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	windStructureTypeFieldNames          = builder.RawFieldNames(&WindStructureType{}, true)
	windStructureTypeRows                = strings.Join(windStructureTypeFieldNames, ",")
	windStructureTypeRowsExpectAutoSet   = strings.Join(stringx.Remove(windStructureTypeFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	windStructureTypeRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(windStructureTypeFieldNames, "structure_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	windStructureTypeModel interface {
		Insert(ctx context.Context, data *WindStructureType) (sql.Result, error)
		FindOne(ctx context.Context, structureId int64) (*WindStructureType, error)
		Update(ctx context.Context, data *WindStructureType) error
		Delete(ctx context.Context, structureId int64) error
	}

	defaultWindStructureTypeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WindStructureType struct {
		StructureId   int64     `db:"structure_id"`
		StructureCode string    `db:"structure_code"`
		StructureName string    `db:"structure_name"`
		CreatedAt     time.Time `db:"created_at"`
		IsDelete      int64     `db:"is_delete"`
		Remark        string    `db:"remark"`
	}
)

func newWindStructureTypeModel(conn sqlx.SqlConn) *defaultWindStructureTypeModel {
	return &defaultWindStructureTypeModel{
		conn:  conn,
		table: `"public"."wind_structure_type"`,
	}
}

func (m *defaultWindStructureTypeModel) Delete(ctx context.Context, structureId int64) error {
	query := fmt.Sprintf("delete from %s where structure_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, structureId)
	return err
}

func (m *defaultWindStructureTypeModel) FindOne(ctx context.Context, structureId int64) (*WindStructureType, error) {
	query := fmt.Sprintf("select %s from %s where structure_id = $1 limit 1", windStructureTypeRows, m.table)
	var resp WindStructureType
	err := m.conn.QueryRowCtx(ctx, &resp, query, structureId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWindStructureTypeModel) Insert(ctx context.Context, data *WindStructureType) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, windStructureTypeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.StructureId, data.StructureCode, data.StructureName, data.IsDelete, data.Remark)
	return ret, err
}

func (m *defaultWindStructureTypeModel) Update(ctx context.Context, data *WindStructureType) error {
	query := fmt.Sprintf("update %s set %s where structure_id = $1", m.table, windStructureTypeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.StructureId, data.StructureCode, data.StructureName, data.IsDelete, data.Remark)
	return err
}

func (m *defaultWindStructureTypeModel) tableName() string {
	return m.table
}
