// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	windFarmFieldNames          = builder.RawFieldNames(&WindFarm{}, true)
	windFarmRows                = strings.Join(windFarmFieldNames, ",")
	windFarmRowsExpectAutoSet   = strings.Join(stringx.Remove(windFarmFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	windFarmRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(windFarmFieldNames, "farm_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	windFarmModel interface {
		Insert(ctx context.Context, data *WindFarm) (sql.Result, error)
		FindOne(ctx context.Context, farmId int64) (*WindFarm, error)
		Update(ctx context.Context, data *WindFarm) error
		Delete(ctx context.Context, farmId int64) error
	}

	defaultWindFarmModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WindFarm struct {
		FarmId     int64     `db:"farm_id"`
		FarmCode   string    `db:"farm_code"` // 风场编号，例如 FY、YS
		FarmName   string    `db:"farm_name"`
		Province   string    `db:"province"`
		Location   string    `db:"location"`
		Latitude   string    `db:"latitude"`
		Longitude  string    `db:"longitude"`
		CreatedAt  time.Time `db:"created_at"`
		IsDelete   int64     `db:"is_delete"`
		Remark     string    `db:"remark"`
		TdDatabase string    `db:"td_database"` // 对应 TDengine 数据库名，例如 fuyu、yushu
		AiEnabled  bool      `db:"ai_enabled"`  // 是否允许 AI Copilot 查询该风场数据
	}
)

func newWindFarmModel(conn sqlx.SqlConn) *defaultWindFarmModel {
	return &defaultWindFarmModel{
		conn:  conn,
		table: `"public"."wind_farm"`,
	}
}

func (m *defaultWindFarmModel) Delete(ctx context.Context, farmId int64) error {
	query := fmt.Sprintf("delete from %s where farm_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, farmId)
	return err
}

func (m *defaultWindFarmModel) FindOne(ctx context.Context, farmId int64) (*WindFarm, error) {
	query := fmt.Sprintf("select %s from %s where farm_id = $1 limit 1", windFarmRows, m.table)
	var resp WindFarm
	err := m.conn.QueryRowCtx(ctx, &resp, query, farmId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWindFarmModel) Insert(ctx context.Context, data *WindFarm) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)", m.table, windFarmRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.FarmId, data.FarmCode, data.FarmName, data.Province, data.Location, data.Latitude, data.Longitude, data.IsDelete, data.Remark, data.TdDatabase, data.AiEnabled)
	return ret, err
}

func (m *defaultWindFarmModel) Update(ctx context.Context, data *WindFarm) error {
	query := fmt.Sprintf("update %s set %s where farm_id = $1", m.table, windFarmRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.FarmId, data.FarmCode, data.FarmName, data.Province, data.Location, data.Latitude, data.Longitude, data.IsDelete, data.Remark, data.TdDatabase, data.AiEnabled)
	return err
}

func (m *defaultWindFarmModel) tableName() string {
	return m.table
}
