// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	windCameraRecordFieldNames          = builder.RawFieldNames(&WindCameraRecord{}, true)
	windCameraRecordRows                = strings.Join(windCameraRecordFieldNames, ",")
	windCameraRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(windCameraRecordFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	windCameraRecordRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(windCameraRecordFieldNames, "record_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	windCameraRecordModel interface {
		Insert(ctx context.Context, data *WindCameraRecord) (sql.Result, error)
		FindOne(ctx context.Context, recordId int64) (*WindCameraRecord, error)
		Update(ctx context.Context, data *WindCameraRecord) error
		Delete(ctx context.Context, recordId int64) error
	}

	defaultWindCameraRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WindCameraRecord struct {
		RecordId    int64     `db:"record_id"`
		RecordName  string    `db:"record_name"`
		CaptureTime time.Time `db:"capture_time"`
		FarmCode    string    `db:"farm_code"`
		TowerCode   string    `db:"tower_code"`
		DeviceCode  string    `db:"device_code"`
		ImageUrl    string    `db:"image_url"`
		IsDelete    int64     `db:"is_delete"`
	}
)

func newWindCameraRecordModel(conn sqlx.SqlConn) *defaultWindCameraRecordModel {
	return &defaultWindCameraRecordModel{
		conn:  conn,
		table: `"public"."wind_camera_record"`,
	}
}

func (m *defaultWindCameraRecordModel) Delete(ctx context.Context, recordId int64) error {
	query := fmt.Sprintf("delete from %s where record_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, recordId)
	return err
}

func (m *defaultWindCameraRecordModel) FindOne(ctx context.Context, recordId int64) (*WindCameraRecord, error) {
	query := fmt.Sprintf("select %s from %s where record_id = $1 limit 1", windCameraRecordRows, m.table)
	var resp WindCameraRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, recordId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWindCameraRecordModel) Insert(ctx context.Context, data *WindCameraRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, windCameraRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RecordId, data.RecordName, data.CaptureTime, data.FarmCode, data.TowerCode, data.DeviceCode, data.ImageUrl, data.IsDelete)
	return ret, err
}

func (m *defaultWindCameraRecordModel) Update(ctx context.Context, data *WindCameraRecord) error {
	query := fmt.Sprintf("update %s set %s where record_id = $1", m.table, windCameraRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.RecordId, data.RecordName, data.CaptureTime, data.FarmCode, data.TowerCode, data.DeviceCode, data.ImageUrl, data.IsDelete)
	return err
}

func (m *defaultWindCameraRecordModel) tableName() string {
	return m.table
}
