// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	windDeviceFieldNames          = builder.RawFieldNames(&WindDevice{}, true)
	windDeviceRows                = strings.Join(windDeviceFieldNames, ",")
	windDeviceRowsExpectAutoSet   = strings.Join(stringx.Remove(windDeviceFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	windDeviceRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(windDeviceFieldNames, "device_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	windDeviceModel interface {
		Insert(ctx context.Context, data *WindDevice) (sql.Result, error)
		FindOne(ctx context.Context, deviceId int64) (*WindDevice, error)
		Update(ctx context.Context, data *WindDevice) error
		Delete(ctx context.Context, deviceId int64) error
	}

	defaultWindDeviceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WindDevice struct {
		DeviceId       int64          `db:"device_id"`        // 传感器实例ID
		DeviceCode     string         `db:"device_code"`      // 传感器编号, 从00开始(通道编号)
		DeviceTypeId   int64          `db:"device_type_id"`   // 传感器类型表的主键id
		DeviceTypeCode string         `db:"device_type_code"` // 传感器类型编号，如: HLS
		DeviceTypeName string         `db:"device_type_name"` // 传感器类型名称，如: 静力水准仪
		TowerId        int64          `db:"tower_id"`         // 所属风机id
		StructureId    int64          `db:"structure_id"`     // 风机结构类型id
		StructureCode  string         `db:"structure_code"`   // 结构编号，例如: BL
		StructureName  string         `db:"structure_name"`   // 结构名称，例如: 叶片
		Frequency      string         `db:"frequency"`        // 采样频率，单位为HZ
		Height         string         `db:"height"`           // 传感器高度，单位为m，精度为小数点后2位。
		Longitude      string         `db:"longitude"`        // 传感器经度
		Latitude       string         `db:"latitude"`         // 传感器纬度
		Status         int64          `db:"status"`           // 状态：在线0 离线 1
		InstallDate    string         `db:"install_date"`     // 安装日期
		CreatedAt      time.Time      `db:"created_at"`       // 记录创建时间
		UpdatedAt      time.Time      `db:"updated_at"`       // 记录修改时间
		IsDelete       int64          `db:"is_delete"`        // 是否删除 0 未删除 1 已删除
		Remark         string         `db:"remark"`           // 备注
		RtspUrl        string         `db:"rtsp_url"`         // 摄像机视频流地址
		VideoUrl       string         `db:"video_url"`        // 摄像机前端播放地址
		SwitchIp       string         `db:"switch_ip"`        // 所属的远程开关ip
		LocationCode   string         `db:"location_code"`    // 监测位置下的逻辑编号
		DeviceCodeOld  sql.NullString `db:"device_code_old"`
		InstallImage   string         `db:"install_image"` // 传感器安装图片
	}
)

func newWindDeviceModel(conn sqlx.SqlConn) *defaultWindDeviceModel {
	return &defaultWindDeviceModel{
		conn:  conn,
		table: `"public"."wind_device"`,
	}
}

func (m *defaultWindDeviceModel) Delete(ctx context.Context, deviceId int64) error {
	query := fmt.Sprintf("delete from %s where device_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, deviceId)
	return err
}

func (m *defaultWindDeviceModel) FindOne(ctx context.Context, deviceId int64) (*WindDevice, error) {
	query := fmt.Sprintf("select %s from %s where device_id = $1 limit 1", windDeviceRows, m.table)
	var resp WindDevice
	err := m.conn.QueryRowCtx(ctx, &resp, query, deviceId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWindDeviceModel) Insert(ctx context.Context, data *WindDevice) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)", m.table, windDeviceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeviceId, data.DeviceCode, data.DeviceTypeId, data.DeviceTypeCode, data.DeviceTypeName, data.TowerId, data.StructureId, data.StructureCode, data.StructureName, data.Frequency, data.Height, data.Longitude, data.Latitude, data.Status, data.InstallDate, data.IsDelete, data.Remark, data.RtspUrl, data.VideoUrl, data.SwitchIp, data.LocationCode, data.DeviceCodeOld, data.InstallImage)
	return ret, err
}

func (m *defaultWindDeviceModel) Update(ctx context.Context, data *WindDevice) error {
	query := fmt.Sprintf("update %s set %s where device_id = $1", m.table, windDeviceRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DeviceId, data.DeviceCode, data.DeviceTypeId, data.DeviceTypeCode, data.DeviceTypeName, data.TowerId, data.StructureId, data.StructureCode, data.StructureName, data.Frequency, data.Height, data.Longitude, data.Latitude, data.Status, data.InstallDate, data.IsDelete, data.Remark, data.RtspUrl, data.VideoUrl, data.SwitchIp, data.LocationCode, data.DeviceCodeOld, data.InstallImage)
	return err
}

func (m *defaultWindDeviceModel) tableName() string {
	return m.table
}
