// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	windTowerFieldNames          = builder.RawFieldNames(&WindTower{}, true)
	windTowerRows                = strings.Join(windTowerFieldNames, ",")
	windTowerRowsExpectAutoSet   = strings.Join(stringx.Remove(windTowerFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	windTowerRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(windTowerFieldNames, "tower_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	windTowerModel interface {
		Insert(ctx context.Context, data *WindTower) (sql.Result, error)
		FindOne(ctx context.Context, towerId int64) (*WindTower, error)
		Update(ctx context.Context, data *WindTower) error
		Delete(ctx context.Context, towerId int64) error
	}

	defaultWindTowerModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WindTower struct {
		TowerId   int64     `db:"tower_id"`
		TowerCode string    `db:"tower_code"` // 风机编号，如 04 表示 4 号风机
		FarmId    int64     `db:"farm_id"`
		FarmCode  string    `db:"farm_code"`
		FarmName  string    `db:"farm_name"`
		CreatedAt time.Time `db:"created_at"`
		IsDelete  int64     `db:"is_delete"`
		Remark    string    `db:"remark"`
		Longitude string    `db:"longitude"`
		Latitude  string    `db:"latitude"`
		Models    string    `db:"models"`
		RiskLevel string    `db:"risk_level"` // AI 风险等级：normal/warning/high/critical
		AiEnabled bool      `db:"ai_enabled"`
	}
)

func newWindTowerModel(conn sqlx.SqlConn) *defaultWindTowerModel {
	return &defaultWindTowerModel{
		conn:  conn,
		table: `"public"."wind_tower"`,
	}
}

func (m *defaultWindTowerModel) Delete(ctx context.Context, towerId int64) error {
	query := fmt.Sprintf("delete from %s where tower_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, towerId)
	return err
}

func (m *defaultWindTowerModel) FindOne(ctx context.Context, towerId int64) (*WindTower, error) {
	query := fmt.Sprintf("select %s from %s where tower_id = $1 limit 1", windTowerRows, m.table)
	var resp WindTower
	err := m.conn.QueryRowCtx(ctx, &resp, query, towerId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWindTowerModel) Insert(ctx context.Context, data *WindTower) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)", m.table, windTowerRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TowerId, data.TowerCode, data.FarmId, data.FarmCode, data.FarmName, data.IsDelete, data.Remark, data.Longitude, data.Latitude, data.Models, data.RiskLevel, data.AiEnabled)
	return ret, err
}

func (m *defaultWindTowerModel) Update(ctx context.Context, data *WindTower) error {
	query := fmt.Sprintf("update %s set %s where tower_id = $1", m.table, windTowerRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TowerId, data.TowerCode, data.FarmId, data.FarmCode, data.FarmName, data.IsDelete, data.Remark, data.Longitude, data.Latitude, data.Models, data.RiskLevel, data.AiEnabled)
	return err
}

func (m *defaultWindTowerModel) tableName() string {
	return m.table
}
