// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	windDeviceMetaFieldNames          = builder.RawFieldNames(&WindDeviceMeta{}, true)
	windDeviceMetaRows                = strings.Join(windDeviceMetaFieldNames, ",")
	windDeviceMetaRowsExpectAutoSet   = strings.Join(stringx.Remove(windDeviceMetaFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	windDeviceMetaRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(windDeviceMetaFieldNames, "meta_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	windDeviceMetaModel interface {
		Insert(ctx context.Context, data *WindDeviceMeta) (sql.Result, error)
		FindOne(ctx context.Context, metaId int64) (*WindDeviceMeta, error)
		Update(ctx context.Context, data *WindDeviceMeta) error
		Delete(ctx context.Context, metaId int64) error
	}

	defaultWindDeviceMetaModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WindDeviceMeta struct {
		MetaId          int64  `db:"meta_id"`
		DeviceTypeCode  string `db:"device_type_code"` // 传感器类型编号
		ColumnName      string `db:"column_name"`      // TDengine 字段名，例如 x、y、accel、strain、settlement
		DisplayName     string `db:"display_name"`     // 前端显示名
		Unit            string `db:"unit"`             // 单位
		Ord             int64  `db:"ord"`              // 字段显示顺序
		Remark          string `db:"remark"`           // 备注
		DeviceTypeId    int64  `db:"device_type_id"`   // 传感器类型id
		AiEnabled       bool   `db:"ai_enabled"`
		ThresholdConfig string `db:"threshold_config"`
	}
)

func newWindDeviceMetaModel(conn sqlx.SqlConn) *defaultWindDeviceMetaModel {
	return &defaultWindDeviceMetaModel{
		conn:  conn,
		table: `"public"."wind_device_meta"`,
	}
}

func (m *defaultWindDeviceMetaModel) Delete(ctx context.Context, metaId int64) error {
	query := fmt.Sprintf("delete from %s where meta_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, metaId)
	return err
}

func (m *defaultWindDeviceMetaModel) FindOne(ctx context.Context, metaId int64) (*WindDeviceMeta, error) {
	query := fmt.Sprintf("select %s from %s where meta_id = $1 limit 1", windDeviceMetaRows, m.table)
	var resp WindDeviceMeta
	err := m.conn.QueryRowCtx(ctx, &resp, query, metaId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWindDeviceMetaModel) Insert(ctx context.Context, data *WindDeviceMeta) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, windDeviceMetaRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MetaId, data.DeviceTypeCode, data.ColumnName, data.DisplayName, data.Unit, data.Ord, data.Remark, data.DeviceTypeId, data.AiEnabled, data.ThresholdConfig)
	return ret, err
}

func (m *defaultWindDeviceMetaModel) Update(ctx context.Context, data *WindDeviceMeta) error {
	query := fmt.Sprintf("update %s set %s where meta_id = $1", m.table, windDeviceMetaRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.MetaId, data.DeviceTypeCode, data.ColumnName, data.DisplayName, data.Unit, data.Ord, data.Remark, data.DeviceTypeId, data.AiEnabled, data.ThresholdConfig)
	return err
}

func (m *defaultWindDeviceMetaModel) tableName() string {
	return m.table
}
