// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	windDeviceTypeFieldNames          = builder.RawFieldNames(&WindDeviceType{}, true)
	windDeviceTypeRows                = strings.Join(windDeviceTypeFieldNames, ",")
	windDeviceTypeRowsExpectAutoSet   = strings.Join(stringx.Remove(windDeviceTypeFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	windDeviceTypeRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(windDeviceTypeFieldNames, "device_type_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	windDeviceTypeModel interface {
		Insert(ctx context.Context, data *WindDeviceType) (sql.Result, error)
		FindOne(ctx context.Context, deviceTypeId int64) (*WindDeviceType, error)
		Update(ctx context.Context, data *WindDeviceType) error
		Delete(ctx context.Context, deviceTypeId int64) error
	}

	defaultWindDeviceTypeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WindDeviceType struct {
		DeviceTypeId    int64     `db:"device_type_id"`
		DeviceTypeCode  string    `db:"device_type_code"`
		DeviceTypeName  string    `db:"device_type_name"`
		SampleUnit      string    `db:"sample_unit"`
		ThresholdConfig string    `db:"threshold_config"` // AI 分析阈值配置，JSON 格式
		AiEnabled       bool      `db:"ai_enabled"`
		CreatedAt       time.Time `db:"created_at"`
		UpdatedAt       time.Time `db:"updated_at"`
		IsDelete        int64     `db:"is_delete"`
		Remark          string    `db:"remark"`
	}
)

func newWindDeviceTypeModel(conn sqlx.SqlConn) *defaultWindDeviceTypeModel {
	return &defaultWindDeviceTypeModel{
		conn:  conn,
		table: `"public"."wind_device_type"`,
	}
}

func (m *defaultWindDeviceTypeModel) Delete(ctx context.Context, deviceTypeId int64) error {
	query := fmt.Sprintf("delete from %s where device_type_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, deviceTypeId)
	return err
}

func (m *defaultWindDeviceTypeModel) FindOne(ctx context.Context, deviceTypeId int64) (*WindDeviceType, error) {
	query := fmt.Sprintf("select %s from %s where device_type_id = $1 limit 1", windDeviceTypeRows, m.table)
	var resp WindDeviceType
	err := m.conn.QueryRowCtx(ctx, &resp, query, deviceTypeId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWindDeviceTypeModel) Insert(ctx context.Context, data *WindDeviceType) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, windDeviceTypeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeviceTypeId, data.DeviceTypeCode, data.DeviceTypeName, data.SampleUnit, data.ThresholdConfig, data.AiEnabled, data.IsDelete, data.Remark)
	return ret, err
}

func (m *defaultWindDeviceTypeModel) Update(ctx context.Context, data *WindDeviceType) error {
	query := fmt.Sprintf("update %s set %s where device_type_id = $1", m.table, windDeviceTypeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DeviceTypeId, data.DeviceTypeCode, data.DeviceTypeName, data.SampleUnit, data.ThresholdConfig, data.AiEnabled, data.IsDelete, data.Remark)
	return err
}

func (m *defaultWindDeviceTypeModel) tableName() string {
	return m.table
}
