// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AiAddKbMemberReq struct {
	KbId   int64  `path:"kbId"`
	UserId int64  `json:"userId"`
	Role   string `json:"role"`
}

type AiAgentRunReq struct {
	ConversationId string `json:"conversationId,optional"`
	Input          string `json:"input"`
}

type AiAgentRunResp struct {
	Answer    string           `json:"answer"`
	TraceId   string           `json:"traceId"`
	ToolCalls []AiToolCallItem `json:"toolCalls"`
}

type AiAnalyzeSecurityEventsReq struct {
	RawLogs []string `json:"rawLogs"`
}

type AiAnalyzeSecurityEventsResp struct {
	Events  []AiSecurityEventItem `json:"events"`
	Alerts  []string              `json:"alerts"`
	Message string                `json:"message"`
}

type AiChatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type AiChatReq struct {
	KbId           int64           `json:"kbId,optional"`
	ConversationId string          `json:"conversationId,optional"`
	Question       string          `json:"question"`
	AnswerMode     string          `json:"answerMode,optional"`
	SearchScope    string          `json:"searchScope,optional"`
	DomainId       int64           `json:"domainId,optional"`
	DocumentIds    []int64         `json:"documentIds,optional"`
	History        []AiChatMessage `json:"history,optional"`
}

type AiChatResp struct {
	Answer    string       `json:"answer"`
	TraceId   string       `json:"traceId"`
	Mode      string       `json:"mode"`
	Citations []AiCitation `json:"citations"`
}

type AiChunkItem struct {
	DocumentId int64   `json:"documentId"`
	ChunkId    int64   `json:"chunkId"`
	Title      string  `json:"title"`
	Snippet    string  `json:"snippet"`
	Content    string  `json:"content,optional"`
	Score      float64 `json:"score"`
	Source     string  `json:"source"`
}

type AiCitation struct {
	DocumentId int64   `json:"documentId"`
	ChunkId    int64   `json:"chunkId"`
	Title      string  `json:"title"`
	Snippet    string  `json:"snippet"`
	Score      float64 `json:"score"`
}

type AiCommonResp struct {
	Message string `json:"message"`
}

type AiCreateKbDomainReq struct {
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description,optional"`
	Sort        int    `json:"sort,optional"`
	Status      int    `json:"status,optional"`
}

type AiCreateKbDomainResp struct {
	DomainId int64 `json:"domainId"`
}

type AiCreatePersonalKbReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
}

type AiCreatePersonalKbResp struct {
	KbId int64 `json:"kbId"`
}

type AiCreatePublicKbReq struct {
	DomainId    int64  `json:"domainId"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Visibility  string `json:"visibility,optional"`
	Status      int    `json:"status,optional"`
}

type AiCreatePublicKbResp struct {
	KbId int64 `json:"kbId"`
}

type AiDailyReportItem struct {
	ReportId          int64            `json:"reportId"`
	Date              string           `json:"date"`
	Title             string           `json:"title"`
	Content           string           `json:"content"`
	Status            string           `json:"status"`
	FailedLoginCount  int64            `json:"failedLoginCount"`
	SuccessLoginCount int64            `json:"successLoginCount"`
	AlertCount        int64            `json:"alertCount"`
	TopIps            []AiTopCountItem `json:"topIps"`
	TopUsers          []AiTopCountItem `json:"topUsers"`
	CreatedAt         string           `json:"createdAt"`
}

type AiDailyReportPathReq struct {
	ReportId int64 `path:"reportId"`
}

type AiDailyReportQueryReq struct {
	Page      int    `form:"page,optional"`
	PageSize  int    `form:"pageSize,optional"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
	Status    string `form:"status,optional"`
}

type AiDailyReportReq struct {
	Date string `json:"date"`
}

type AiDailyReportResp struct {
	Report AiDailyReportItem `json:"report"`
}

type AiDocumentItem struct {
	DocumentId   int64  `json:"documentId"`
	KbId         int64  `json:"kbId"`
	FileName     string `json:"fileName"`
	FileType     string `json:"fileType"`
	Status       string `json:"status"`
	ErrorMessage string `json:"errorMessage"`
	UploadedBy   int64  `json:"uploadedBy"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type AiDocumentPathReq struct {
	KbId       int64 `path:"kbId"`
	DocumentId int64 `path:"documentId"`
}

type AiHealthResp struct {
	Status      string `json:"status"`
	EngineReady bool   `json:"engineReady"`
	Message     string `json:"message"`
}

type AiIdPathReq struct {
	Id int64 `path:"id"`
}

type AiIngestDocumentReq struct {
	KbId        int64  `path:"kbId"`
	FileName    string `json:"fileName"`
	FileType    string `json:"fileType"`
	Content     string `json:"content,optional"`
	SourceType  string `json:"sourceType,optional"`
	StoredPath  string `json:"storedPath,optional"`
	ContentHash string `json:"contentHash,optional"`
}

type AiKbDomainItem struct {
	DomainId    int64  `json:"domainId"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
	Sort        int    `json:"sort"`
	Status      int    `json:"status"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type AiKbDomainPathReq struct {
	DomainId int64 `path:"domainId"`
}

type AiKbMemberItem struct {
	KbId      int64  `json:"kbId"`
	UserId    int64  `json:"userId"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Role      string `json:"role"`
	CreatedAt string `json:"createdAt"`
}

type AiKbMemberPathReq struct {
	KbId   int64 `path:"kbId"`
	UserId int64 `path:"userId"`
}

type AiListDailyReportResp struct {
	Total int64               `json:"total"`
	List  []AiDailyReportItem `json:"list"`
}

type AiListDocumentReq struct {
	KbId     int64  `path:"kbId"`
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Keyword  string `form:"keyword,optional"`
	Status   string `form:"status,optional"`
}

type AiListDocumentResp struct {
	Total int64            `json:"total"`
	List  []AiDocumentItem `json:"list"`
}

type AiListKbDomainReq struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Keyword  string `form:"keyword,optional"`
	Status   int    `form:"status,optional"`
}

type AiListKbDomainResp struct {
	Total int64            `json:"total"`
	List  []AiKbDomainItem `json:"list"`
}

type AiListKbMemberReq struct {
	KbId     int64  `path:"kbId"`
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Keyword  string `form:"keyword,optional"`
	Role     string `form:"role,optional"`
}

type AiListKbMemberResp struct {
	Total int64            `json:"total"`
	List  []AiKbMemberItem `json:"list"`
}

type AiListLlmCallReq struct {
	Page      int    `form:"page,optional"`
	PageSize  int    `form:"pageSize,optional"`
	TraceId   string `form:"traceId,optional"`
	Provider  string `form:"provider,optional"`
	Model     string `form:"model,optional"`
	Status    string `form:"status,optional"`
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
}

type AiListLlmCallResp struct {
	Total int64           `json:"total"`
	List  []AiLlmCallItem `json:"list"`
}

type AiListPersonalKbReq struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Keyword  string `form:"keyword,optional"`
	Status   int    `form:"status,optional"`
}

type AiListPersonalKbResp struct {
	Total int64              `json:"total"`
	List  []AiPersonalKbItem `json:"list"`
}

type AiListPublicKbReq struct {
	Page       int    `form:"page,optional"`
	PageSize   int    `form:"pageSize,optional"`
	DomainId   int64  `form:"domainId,optional"`
	Keyword    string `form:"keyword,optional"`
	Visibility string `form:"visibility,optional"`
	Status     int    `form:"status,optional"`
}

type AiListPublicKbResp struct {
	Total int64            `json:"total"`
	List  []AiPublicKbItem `json:"list"`
}

type AiListSecurityAlertsReq struct {
	Page      int    `form:"page,optional"`
	PageSize  int    `form:"pageSize,optional"`
	AlertType string `form:"alertType,optional"`
	Severity  string `form:"severity,optional"`
	Status    string `form:"status,optional"`
	Ip        string `form:"ip,optional"`
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
}

type AiListSecurityAlertsResp struct {
	Total int64                 `json:"total"`
	List  []AiSecurityAlertItem `json:"list"`
}

type AiListSecurityEventsReq struct {
	Page      int    `form:"page,optional"`
	PageSize  int    `form:"pageSize,optional"`
	EventType string `form:"eventType,optional"`
	Severity  string `form:"severity,optional"`
	Ip        string `form:"ip,optional"`
	Username  string `form:"username,optional"`
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
}

type AiListSecurityEventsResp struct {
	Total int64                 `json:"total"`
	List  []AiSecurityEventItem `json:"list"`
}

type AiListToolCallReq struct {
	Page      int    `form:"page,optional"`
	PageSize  int    `form:"pageSize,optional"`
	TraceId   string `form:"traceId,optional"`
	ToolName  string `form:"toolName,optional"`
	Status    string `form:"status,optional"`
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
}

type AiListToolCallResp struct {
	Total int64            `json:"total"`
	List  []AiToolCallItem `json:"list"`
}

type AiLlmCallItem struct {
	TraceId          string `json:"traceId"`
	Provider         string `json:"provider"`
	Model            string `json:"model"`
	PromptTokens     int64  `json:"promptTokens"`
	CompletionTokens int64  `json:"completionTokens"`
	LatencyMs        int64  `json:"latencyMs"`
	Status           string `json:"status"`
	ErrorMsg         string `json:"errorMsg"`
	CreatedAt        string `json:"createdAt"`
}

type AiLlmTracePathReq struct {
	TraceId string `path:"traceId"`
}

type AiLlmTraceResp struct {
	TraceId string          `json:"traceId"`
	Calls   []AiLlmCallItem `json:"calls"`
}

type AiPageReq struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type AiPersonalKbItem struct {
	KbId          int64  `json:"kbId"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Status        int    `json:"status"`
	DocumentCount int64  `json:"documentCount"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type AiPersonalKbPathReq struct {
	KbId int64 `path:"kbId"`
}

type AiPublicKbItem struct {
	KbId          int64  `json:"kbId"`
	DomainId      int64  `json:"domainId"`
	DomainName    string `json:"domainName"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Visibility    string `json:"visibility"`
	Status        int    `json:"status"`
	DocumentCount int64  `json:"documentCount"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type AiPublicKbPathReq struct {
	KbId int64 `path:"kbId"`
}

type AiSearchKnowledgeReq struct {
	KbId        int64   `json:"kbId,optional"`
	Query       string  `json:"query"`
	TopK        int     `json:"topK,optional"`
	AnswerMode  string  `json:"answerMode,optional"`
	SearchScope string  `json:"searchScope,optional"`
	DomainId    int64   `json:"domainId,optional"`
	DocumentIds []int64 `json:"documentIds,optional"`
}

type AiSearchKnowledgeResp struct {
	Chunks  []AiChunkItem `json:"chunks"`
	Mode    string        `json:"mode"`
	Message string        `json:"message"`
}

type AiSecurityAlertItem struct {
	AlertId    int64  `json:"alertId"`
	AlertType  string `json:"alertType"`
	Severity   string `json:"severity"`
	Ip         string `json:"ip"`
	Username   string `json:"username"`
	Title      string `json:"title"`
	Summary    string `json:"summary"`
	Detail     string `json:"detail"`
	Status     string `json:"status"`
	OccurredAt string `json:"occurredAt"`
	CreatedAt  string `json:"createdAt"`
}

type AiSecurityEventItem struct {
	EventId    int64  `json:"eventId"`
	EventType  string `json:"eventType"`
	Severity   string `json:"severity"`
	Ip         string `json:"ip"`
	Username   string `json:"username"`
	Summary    string `json:"summary"`
	Detail     string `json:"detail"`
	OccurredAt string `json:"occurredAt"`
	CreatedAt  string `json:"createdAt"`
}

type AiSecurityLogItem struct {
	Id        string `json:"id"`
	Timestamp string `json:"timestamp"`
	Host      string `json:"host"`
	Ip        string `json:"ip"`
	Username  string `json:"username"`
	Message   string `json:"message"`
}

type AiSecurityLogSearchReq struct {
	Query     string `json:"query,optional"`
	Ip        string `json:"ip,optional"`
	Username  string `json:"username,optional"`
	StartTime string `json:"startTime,optional"`
	EndTime   string `json:"endTime,optional"`
	Page      int    `json:"page,optional"`
	PageSize  int    `json:"pageSize,optional"`
}

type AiSecurityLogSearchResp struct {
	Total   int64               `json:"total"`
	List    []AiSecurityLogItem `json:"list"`
	Message string              `json:"message"`
}

type AiTaskResp struct {
	TaskId  string `json:"taskId"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type AiTokenStatsReq struct {
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
	Provider  string `form:"provider,optional"`
	Model     string `form:"model,optional"`
}

type AiTokenStatsResp struct {
	PromptTokens     int64 `json:"promptTokens"`
	CompletionTokens int64 `json:"completionTokens"`
	TotalTokens      int64 `json:"totalTokens"`
	CallCount        int64 `json:"callCount"`
}

type AiToolCallItem struct {
	ToolCallId    int64  `json:"toolCallId"`
	ToolName      string `json:"toolName"`
	Status        string `json:"status"`
	ArgumentsJson string `json:"argumentsJson"`
	ResultJson    string `json:"resultJson"`
	Message       string `json:"message"`
	CreatedAt     string `json:"createdAt"`
}

type AiTopCountItem struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

type AiUpdateKbDomainReq struct {
	DomainId    int64  `path:"domainId"`
	Name        string `json:"name,optional"`
	Code        string `json:"code,optional"`
	Description string `json:"description,optional"`
	Sort        int    `json:"sort,optional"`
	Status      int    `json:"status,optional"`
}

type AiUpdateKbMemberReq struct {
	KbId   int64  `path:"kbId"`
	UserId int64  `path:"userId"`
	Role   string `json:"role"`
}

type AiUpdatePersonalKbReq struct {
	KbId        int64  `path:"kbId"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	Status      int    `json:"status,optional"`
}

type AiUpdatePublicKbReq struct {
	KbId        int64  `path:"kbId"`
	DomainId    int64  `json:"domainId,optional"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	Visibility  string `json:"visibility,optional"`
	Status      int    `json:"status,optional"`
}

type AiUpdateSecurityAlertStatusReq struct {
	AlertId int64  `path:"alertId"`
	Status  string `json:"status"`
}
