// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AiAddKbMemberReq struct {
	KbId   int64  `path:"kbId"`
	UserId int64  `json:"userId"`
	Role   string `json:"role"`
}

type AiChatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type AiChatReq struct {
	KbId           int64   `json:"kbId,optional"`
	ConversationId string  `json:"conversationId,optional"`
	Question       string  `json:"question"`
	AnswerMode     string  `json:"answerMode,optional"`
	SearchScope    string  `json:"searchScope,optional"`
	DomainId       int64   `json:"domainId,optional"`
	DocumentIds    []int64 `json:"documentIds,optional"`
}

type AiChatResp struct {
	Answer         string       `json:"answer"`
	TraceId        string       `json:"traceId"`
	Mode           string       `json:"mode"`
	ConversationId string       `json:"conversationId"`
	Citations      []AiCitation `json:"citations"`
}

type AiChunkItem struct {
	DocumentId int64   `json:"documentId"`
	ChunkId    int64   `json:"chunkId"`
	Title      string  `json:"title"`
	Snippet    string  `json:"snippet"`
	Content    string  `json:"content,optional"`
	Score      float64 `json:"score"`
	Source     string  `json:"source"`
}

type AiCitation struct {
	DocumentId int64   `json:"documentId"`
	ChunkId    int64   `json:"chunkId"`
	Title      string  `json:"title"`
	Snippet    string  `json:"snippet"`
	Score      float64 `json:"score"`
}

type AiCommonResp struct {
	Message string `json:"message"`
}

type AiConversationItem struct {
	ConversationId string `json:"conversationId"`
	KbId           int64  `json:"kbId"`
	Title          string `json:"title"`
	LatestMessage  string `json:"latestMessage"`
	CreatedAt      string `json:"createdAt"`
	UpdatedAt      string `json:"updatedAt"`
}

type AiConversationMessagesReq struct {
	ConversationId string `path:"conversationId"`
	Page           int64  `form:"page,optional"`
	PageSize       int64  `form:"pageSize,optional"`
}

type AiConversationMessagesResp struct {
	Total int64           `json:"total"`
	List  []AiMessageItem `json:"list"`
}

type AiConversationPathReq struct {
	ConversationId string `path:"conversationId"`
}

type AiCreateKbDomainReq struct {
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description,optional"`
	Sort        int    `json:"sort,optional"`
	Status      int    `json:"status,optional"`
}

type AiCreateKbDomainResp struct {
	DomainId int64 `json:"domainId"`
}

type AiCreatePersonalKbReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
}

type AiCreatePersonalKbResp struct {
	KbId int64 `json:"kbId"`
}

type AiCreatePublicKbReq struct {
	DomainId    int64  `json:"domainId"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Visibility  string `json:"visibility,optional"`
	Status      int    `json:"status,optional"`
}

type AiCreatePublicKbResp struct {
	KbId int64 `json:"kbId"`
}

type AiDeleteMessageReq struct {
	ConversationId string `path:"conversationId"`
	MessageId      int64  `path:"messageId"`
}

type AiDocumentItem struct {
	DocumentId   int64  `json:"documentId"`
	KbId         int64  `json:"kbId"`
	FileName     string `json:"fileName"`
	FileType     string `json:"fileType"`
	Status       string `json:"status"`
	ErrorMessage string `json:"errorMessage"`
	UploadedBy   int64  `json:"uploadedBy"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type AiDocumentPathReq struct {
	KbId       int64 `path:"kbId"`
	DocumentId int64 `path:"documentId"`
}

type AiHealthResp struct {
	Status      string `json:"status"`
	EngineReady bool   `json:"engineReady"`
	Message     string `json:"message"`
}

type AiIdPathReq struct {
	Id int64 `path:"id"`
}

type AiIngestDocumentReq struct {
	KbId        int64  `path:"kbId"`
	FileName    string `json:"fileName"`
	FileType    string `json:"fileType"`
	Content     string `json:"content,optional"`
	SourceType  string `json:"sourceType,optional"`
	StoredPath  string `json:"storedPath,optional"`
	ContentHash string `json:"contentHash,optional"`
}

type AiKbDomainItem struct {
	DomainId    int64  `json:"domainId"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
	Sort        int    `json:"sort"`
	Status      int    `json:"status"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type AiKbDomainPathReq struct {
	DomainId int64 `path:"domainId"`
}

type AiKbMemberItem struct {
	KbId      int64  `json:"kbId"`
	UserId    int64  `json:"userId"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Role      string `json:"role"`
	CreatedAt string `json:"createdAt"`
}

type AiKbMemberPathReq struct {
	KbId   int64 `path:"kbId"`
	UserId int64 `path:"userId"`
}

type AiListConversationReq struct {
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
	KbId     int64  `form:"kbId,optional"`
	Keyword  string `form:"keyword,optional"`
}

type AiListConversationResp struct {
	Total int64                `json:"total"`
	List  []AiConversationItem `json:"list"`
}

type AiListDocumentReq struct {
	KbId     int64  `path:"kbId"`
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Keyword  string `form:"keyword,optional"`
	Status   string `form:"status,optional"`
}

type AiListDocumentResp struct {
	Total int64            `json:"total"`
	List  []AiDocumentItem `json:"list"`
}

type AiListKbDomainReq struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Keyword  string `form:"keyword,optional"`
	Status   int    `form:"status,optional"`
}

type AiListKbDomainResp struct {
	Total int64            `json:"total"`
	List  []AiKbDomainItem `json:"list"`
}

type AiListKbMemberReq struct {
	KbId     int64  `path:"kbId"`
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Keyword  string `form:"keyword,optional"`
	Role     string `form:"role,optional"`
}

type AiListKbMemberResp struct {
	Total int64            `json:"total"`
	List  []AiKbMemberItem `json:"list"`
}

type AiListLlmCallReq struct {
	Page      int    `form:"page,optional"`
	PageSize  int    `form:"pageSize,optional"`
	TraceId   string `form:"traceId,optional"`
	Provider  string `form:"provider,optional"`
	Model     string `form:"model,optional"`
	Status    string `form:"status,optional"`
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
}

type AiListLlmCallResp struct {
	Total int64           `json:"total"`
	List  []AiLlmCallItem `json:"list"`
}

type AiListPersonalKbReq struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Keyword  string `form:"keyword,optional"`
	Status   int    `form:"status,optional"`
}

type AiListPersonalKbResp struct {
	Total int64              `json:"total"`
	List  []AiPersonalKbItem `json:"list"`
}

type AiListPublicKbReq struct {
	Page       int    `form:"page,optional"`
	PageSize   int    `form:"pageSize,optional"`
	DomainId   int64  `form:"domainId,optional"`
	Keyword    string `form:"keyword,optional"`
	Visibility string `form:"visibility,optional"`
	Status     int    `form:"status,optional"`
}

type AiListPublicKbResp struct {
	Total int64            `json:"total"`
	List  []AiPublicKbItem `json:"list"`
}

type AiLlmCallItem struct {
	TraceId          string `json:"traceId"`
	Provider         string `json:"provider"`
	Model            string `json:"model"`
	PromptTokens     int64  `json:"promptTokens"`
	CompletionTokens int64  `json:"completionTokens"`
	LatencyMs        int64  `json:"latencyMs"`
	Status           string `json:"status"`
	ErrorMsg         string `json:"errorMsg"`
	CreatedAt        string `json:"createdAt"`
}

type AiLlmTracePathReq struct {
	TraceId string `path:"traceId"`
}

type AiLlmTraceResp struct {
	TraceId string          `json:"traceId"`
	Calls   []AiLlmCallItem `json:"calls"`
}

type AiMessageItem struct {
	MessageId      int64        `json:"messageId"`
	ConversationId string       `json:"conversationId"`
	Role           string       `json:"role"`
	Content        string       `json:"content"`
	Citations      []AiCitation `json:"citations"`
	TraceId        string       `json:"traceId"`
	CreatedAt      string       `json:"createdAt"`
}

type AiPageReq struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type AiPersonalKbItem struct {
	KbId          int64  `json:"kbId"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Status        int    `json:"status"`
	DocumentCount int64  `json:"documentCount"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type AiPersonalKbPathReq struct {
	KbId int64 `path:"kbId"`
}

type AiPublicKbItem struct {
	KbId          int64  `json:"kbId"`
	DomainId      int64  `json:"domainId"`
	DomainName    string `json:"domainName"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Visibility    string `json:"visibility"`
	Status        int    `json:"status"`
	DocumentCount int64  `json:"documentCount"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type AiPublicKbPathReq struct {
	KbId int64 `path:"kbId"`
}

type AiSearchKnowledgeReq struct {
	KbId        int64   `json:"kbId,optional"`
	Query       string  `json:"query"`
	TopK        int     `json:"topK,optional"`
	AnswerMode  string  `json:"answerMode,optional"`
	SearchScope string  `json:"searchScope,optional"`
	DomainId    int64   `json:"domainId,optional"`
	DocumentIds []int64 `json:"documentIds,optional"`
}

type AiSearchKnowledgeResp struct {
	Chunks  []AiChunkItem `json:"chunks"`
	Mode    string        `json:"mode"`
	Message string        `json:"message"`
}

type AiTaskResp struct {
	TaskId  string `json:"taskId"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type AiTokenStatsReq struct {
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
	Provider  string `form:"provider,optional"`
	Model     string `form:"model,optional"`
}

type AiTokenStatsResp struct {
	PromptTokens     int64 `json:"promptTokens"`
	CompletionTokens int64 `json:"completionTokens"`
	TotalTokens      int64 `json:"totalTokens"`
	CallCount        int64 `json:"callCount"`
}

type AiTopCountItem struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

type AiUpdateConversationTitleReq struct {
	ConversationId string `path:"conversationId"`
	Title          string `json:"title"`
}

type AiUpdateKbDomainReq struct {
	DomainId    int64  `path:"domainId"`
	Name        string `json:"name,optional"`
	Code        string `json:"code,optional"`
	Description string `json:"description,optional"`
	Sort        int    `json:"sort,optional"`
	Status      int    `json:"status,optional"`
}

type AiUpdateKbMemberReq struct {
	KbId   int64  `path:"kbId"`
	UserId int64  `path:"userId"`
	Role   string `json:"role"`
}

type AiUpdatePersonalKbReq struct {
	KbId        int64  `path:"kbId"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	Status      int    `json:"status,optional"`
}

type AiUpdatePublicKbReq struct {
	KbId        int64  `path:"kbId"`
	DomainId    int64  `json:"domainId,optional"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	Visibility  string `json:"visibility,optional"`
	Status      int    `json:"status,optional"`
}

type AiWindAgentRunReq struct {
	ConversationId string `json:"conversationId,optional"`
	Input          string `json:"input"`
}

type AiWindAgentRunResp struct {
	Answer    string               `json:"answer"`
	TraceId   string               `json:"traceId"`
	ToolCalls []AiWindToolCallItem `json:"toolCalls"`
}

type AiWindAlarmAnalyzeReq struct {
	FarmCode     string `json:"farmCode"`
	TowerCode    string `json:"towerCode,optional"`
	AlarmCode    string `json:"alarmCode,optional"`
	StartTime    string `json:"startTime,optional"`
	EndTime      string `json:"endTime,optional"`
	EvidenceJson string `json:"evidenceJson,optional"`
}

type AiWindAlarmItem struct {
	Ts            string `json:"ts"`
	FarmCode      string `json:"farmCode"`
	TowerCode     string `json:"towerCode"`
	DeviceChannel int64  `json:"deviceChannel"`
	DeviceType    int64  `json:"deviceType"`
	AlarmLocation string `json:"alarmLocation"`
	AlarmLevel    int64  `json:"alarmLevel"`
	AlarmCode     int64  `json:"alarmCode"`
	AlarmValue    string `json:"alarmValue"`
	Status        int64  `json:"status"`
}

type AiWindAlarmQueryReq struct {
	FarmCode       string `json:"farmCode"`
	TowerCode      string `json:"towerCode,optional"`
	DeviceTypeCode string `json:"deviceTypeCode,optional"`
	DeviceCode     string `json:"deviceCode,optional"`
	AlarmCode      string `json:"alarmCode,optional"`
	AlarmLevel     int    `json:"alarmLevel,optional"`
	Status         int    `json:"status,optional"`
	StartTime      string `json:"startTime,optional"`
	EndTime        string `json:"endTime,optional"`
	Page           int    `json:"page,optional"`
	PageSize       int    `json:"pageSize,optional"`
}

type AiWindAlarmQueryResp struct {
	Total        int64             `json:"total"`
	List         []AiWindAlarmItem `json:"list"`
	EvidenceJson string            `json:"evidenceJson"`
	Message      string            `json:"message"`
}

type AiWindDataPoint struct {
	Ts     string            `json:"ts"`
	Values map[string]string `json:"values"`
}

type AiWindDeviceItem struct {
	DeviceId       int64  `json:"deviceId"`
	DeviceCode     string `json:"deviceCode"`
	DeviceTypeCode string `json:"deviceTypeCode"`
	DeviceTypeName string `json:"deviceTypeName"`
	TowerId        int64  `json:"towerId"`
	TowerCode      string `json:"towerCode"`
	StructureCode  string `json:"structureCode"`
	StructureName  string `json:"structureName"`
	Status         int    `json:"status"`
}

type AiWindFarmItem struct {
	FarmId     int64  `json:"farmId"`
	FarmCode   string `json:"farmCode"`
	FarmName   string `json:"farmName"`
	Province   string `json:"province"`
	Location   string `json:"location"`
	TdDatabase string `json:"tdDatabase"`
	AiEnabled  bool   `json:"aiEnabled"`
}

type AiWindHealthReportPathReq struct {
	ReportId int64 `path:"reportId"`
}

type AiWindHealthReportReq struct {
	ReportType   string `json:"reportType,optional"`
	FarmCode     string `json:"farmCode"`
	TowerCode    string `json:"towerCode,optional"`
	StartTime    string `json:"startTime,optional"`
	EndTime      string `json:"endTime,optional"`
	EvidenceJson string `json:"evidenceJson,optional"`
}

type AiWindListDeviceReq struct {
	FarmCode       string `form:"farmCode,optional"`
	TowerCode      string `form:"towerCode,optional"`
	DeviceTypeCode string `form:"deviceTypeCode,optional"`
	Keyword        string `form:"keyword,optional"`
}

type AiWindListDeviceResp struct {
	Total   int64              `json:"total"`
	List    []AiWindDeviceItem `json:"list"`
	Message string             `json:"message"`
}

type AiWindListFarmReq struct {
	Keyword string `form:"keyword,optional"`
}

type AiWindListFarmResp struct {
	Total   int64            `json:"total"`
	List    []AiWindFarmItem `json:"list"`
	Message string           `json:"message"`
}

type AiWindListToolCallReq struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	TraceId  string `form:"traceId,optional"`
	ToolName string `form:"toolName,optional"`
	Status   string `form:"status,optional"`
}

type AiWindListToolCallResp struct {
	Total int64                `json:"total"`
	List  []AiWindToolCallItem `json:"list"`
}

type AiWindListTurbineReq struct {
	FarmCode string `form:"farmCode,optional"`
	Keyword  string `form:"keyword,optional"`
}

type AiWindListTurbineResp struct {
	Total   int64               `json:"total"`
	List    []AiWindTurbineItem `json:"list"`
	Message string              `json:"message"`
}

type AiWindScaffoldResp struct {
	Id           int64  `json:"id"`
	TraceId      string `json:"traceId"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	EvidenceJson string `json:"evidenceJson"`
	Message      string `json:"message"`
}

type AiWindTicketDraftReq struct {
	FarmCode     string `json:"farmCode"`
	TowerCode    string `json:"towerCode,optional"`
	AlarmCode    string `json:"alarmCode,optional"`
	EvidenceJson string `json:"evidenceJson,optional"`
}

type AiWindTimeseriesQueryReq struct {
	FarmCode       string   `json:"farmCode"`
	TowerCode      string   `json:"towerCode,optional"`
	DeviceCode     string   `json:"deviceCode,optional"`
	DeviceTypeCode string   `json:"deviceTypeCode"`
	Field          []string `json:"field,optional"`
	StartTime      string   `json:"startTime,optional"`
	EndTime        string   `json:"endTime,optional"`
	Page           int      `json:"page,optional"`
	PageSize       int      `json:"pageSize,optional"`
	IndexId        int64    `json:"indexId,optional"`
}

type AiWindTimeseriesQueryResp struct {
	Total        int64             `json:"total"`
	Database     string            `json:"database"`
	Stable       string            `json:"stable"`
	Fields       []string          `json:"fields"`
	Points       []AiWindDataPoint `json:"points"`
	EvidenceJson string            `json:"evidenceJson"`
	Message      string            `json:"message"`
}

type AiWindToolCallItem struct {
	ToolCallId    int64  `json:"toolCallId"`
	ToolName      string `json:"toolName"`
	Status        string `json:"status"`
	ArgumentsJson string `json:"argumentsJson"`
	ResultJson    string `json:"resultJson"`
	Message       string `json:"message"`
	CreatedAt     string `json:"createdAt"`
}

type AiWindTrendCompareReq struct {
	FarmCode       string   `json:"farmCode"`
	TowerCode      string   `json:"towerCode,optional"`
	DeviceTypeCode string   `json:"deviceTypeCode"`
	DeviceCode     string   `json:"deviceCode,optional"`
	Field          []string `json:"field,optional"`
	StartTime      string   `json:"startTime,optional"`
	EndTime        string   `json:"endTime,optional"`
	IndexId        int64    `json:"indexId,optional"`
}

type AiWindTrendCompareResp struct {
	Summary      string `json:"summary"`
	EvidenceJson string `json:"evidenceJson"`
	Message      string `json:"message"`
}

type AiWindTurbineItem struct {
	TowerId   int64  `json:"towerId"`
	TowerCode string `json:"towerCode"`
	FarmId    int64  `json:farmId`
	FarmCode  string `json:"farmCode"`
	FarmName  string `json:"farmName"`
	RiskLevel string `json:"riskLevel"`
	AiEnabled bool   `json:"aiEnabled"`
	Remark    string `json:"remark"`
}
