// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"context"

	"ai-copilot-platform/ai-rpc/internal/logic/aichatservice"
	"ai-copilot-platform/ai-rpc/internal/svc"
	"ai-copilot-platform/ai-rpc/pb"
)

type AiChatServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiChatServiceServer
}

func NewAiChatServiceServer(svcCtx *svc.ServiceContext) *AiChatServiceServer {
	return &AiChatServiceServer{
		svcCtx: svcCtx,
	}
}

// 执行普通 RAG 问答，返回完整答案。
func (s *AiChatServiceServer) RagChat(ctx context.Context, in *pb.RagChatReq) (*pb.RagChatResp, error) {
	l := aichatservicelogic.NewRagChatLogic(ctx, s.svcCtx)
	return l.RagChat(in)
}

// 执行流式 RAG 问答，逐步返回 token、引用和完成事件。
func (s *AiChatServiceServer) RagChatStream(in *pb.RagChatReq, stream pb.AiChatService_RagChatStreamServer) error {
	l := aichatservicelogic.NewRagChatStreamLogic(stream.Context(), s.svcCtx)
	return l.RagChatStream(in, stream)
}

// 查询当前用户的 AI 会话列表。
func (s *AiChatServiceServer) ListConversation(ctx context.Context, in *pb.ListConversationReq) (*pb.ListConversationResp, error) {
	l := aichatservicelogic.NewListConversationLogic(ctx, s.svcCtx)
	return l.ListConversation(in)
}

// 查询指定会话的消息历史。
func (s *AiChatServiceServer) GetConversationMessages(ctx context.Context, in *pb.GetConversationMessagesReq) (*pb.GetConversationMessagesResp, error) {
	l := aichatservicelogic.NewGetConversationMessagesLogic(ctx, s.svcCtx)
	return l.GetConversationMessages(in)
}

func (s *AiChatServiceServer) UpdateConversationTitle(ctx context.Context, in *pb.UpdateConversationTitleReq) (*pb.Empty, error) {
	l := aichatservicelogic.NewUpdateConversationTitleLogic(ctx, s.svcCtx)
	return l.UpdateConversationTitle(in)
}

func (s *AiChatServiceServer) DeleteConversation(ctx context.Context, in *pb.DeleteConversationReq) (*pb.Empty, error) {
	l := aichatservicelogic.NewDeleteConversationLogic(ctx, s.svcCtx)
	return l.DeleteConversation(in)
}

func (s *AiChatServiceServer) DeleteMessage(ctx context.Context, in *pb.DeleteMessageReq) (*pb.Empty, error) {
	l := aichatservicelogic.NewDeleteMessageLogic(ctx, s.svcCtx)
	return l.DeleteMessage(in)
}
