// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"context"

	"ai-copilot-platform/ai-rpc/internal/logic/aiwindalarmservice"
	"ai-copilot-platform/ai-rpc/internal/svc"
	"ai-copilot-platform/ai-rpc/pb"
)

type AiWindAlarmServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiWindAlarmServiceServer
}

func NewAiWindAlarmServiceServer(svcCtx *svc.ServiceContext) *AiWindAlarmServiceServer {
	return &AiWindAlarmServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AiWindAlarmServiceServer) QueryAlarms(ctx context.Context, in *pb.WindAlarmQueryReq) (*pb.WindAlarmQueryResp, error) {
	l := aiwindalarmservicelogic.NewQueryAlarmsLogic(ctx, s.svcCtx)
	return l.QueryAlarms(in)
}

func (s *AiWindAlarmServiceServer) AnalyzeAlarm(ctx context.Context, in *pb.WindAlarmAnalyzeReq) (*pb.WindScaffoldResp, error) {
	l := aiwindalarmservicelogic.NewAnalyzeAlarmLogic(ctx, s.svcCtx)
	return l.AnalyzeAlarm(in)
}
