// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package aistatusservice

import (
	"context"

	"ai-copilot-platform/ai-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	HealthReq  = pb.HealthReq
	HealthResp = pb.HealthResp

	AiStatusService interface {
		// 检查 AI 引擎健康状态。
		Health(ctx context.Context, in *HealthReq, opts ...grpc.CallOption) (*HealthResp, error)
	}

	defaultAiStatusService struct {
		cli zrpc.Client
	}
)

func NewAiStatusService(cli zrpc.Client) AiStatusService {
	return &defaultAiStatusService{
		cli: cli,
	}
}

// 检查 AI 引擎健康状态。
func (m *defaultAiStatusService) Health(ctx context.Context, in *HealthReq, opts ...grpc.CallOption) (*HealthResp, error) {
	client := pb.NewAiStatusServiceClient(m.cli.Conn())
	return client.Health(ctx, in, opts...)
}
