// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package aiwindtimeseriesservice

import (
	"context"

	"ai-copilot-platform/ai-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	WindTimeseriesQueryReq  = pb.WindTimeseriesQueryReq
	WindTimeseriesQueryResp = pb.WindTimeseriesQueryResp
	WindTrendCompareReq     = pb.WindTrendCompareReq
	WindTrendCompareResp    = pb.WindTrendCompareResp

	AiWindTimeseriesService interface {
		QueryTimeseries(ctx context.Context, in *WindTimeseriesQueryReq, opts ...grpc.CallOption) (*WindTimeseriesQueryResp, error)
		CompareTrend(ctx context.Context, in *WindTrendCompareReq, opts ...grpc.CallOption) (*WindTrendCompareResp, error)
	}

	defaultAiWindTimeseriesService struct {
		cli zrpc.Client
	}
)

func NewAiWindTimeseriesService(cli zrpc.Client) AiWindTimeseriesService {
	return &defaultAiWindTimeseriesService{
		cli: cli,
	}
}

func (m *defaultAiWindTimeseriesService) QueryTimeseries(ctx context.Context, in *WindTimeseriesQueryReq, opts ...grpc.CallOption) (*WindTimeseriesQueryResp, error) {
	client := pb.NewAiWindTimeseriesServiceClient(m.cli.Conn())
	return client.QueryTimeseries(ctx, in, opts...)
}

func (m *defaultAiWindTimeseriesService) CompareTrend(ctx context.Context, in *WindTrendCompareReq, opts ...grpc.CallOption) (*WindTrendCompareResp, error) {
	client := pb.NewAiWindTimeseriesServiceClient(m.cli.Conn())
	return client.CompareTrend(ctx, in, opts...)
}
