// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package aiagentservice

import (
	"context"

	"ai-copilot-platform/ai-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AgentRunReq         = pb.AgentRunReq
	AgentRunResp        = pb.AgentRunResp
	ListToolCallLogReq  = pb.ListToolCallLogReq
	ListToolCallLogResp = pb.ListToolCallLogResp

	AiAgentService interface {
		// 运行受控 Agent，只允许调用白名单工具。
		RunAgent(ctx context.Context, in *AgentRunReq, opts ...grpc.CallOption) (*AgentRunResp, error)
		// 查询 Agent 工具调用日志。
		ListToolCallLog(ctx context.Context, in *ListToolCallLogReq, opts ...grpc.CallOption) (*ListToolCallLogResp, error)
	}

	defaultAiAgentService struct {
		cli zrpc.Client
	}
)

func NewAiAgentService(cli zrpc.Client) AiAgentService {
	return &defaultAiAgentService{
		cli: cli,
	}
}

// 运行受控 Agent，只允许调用白名单工具。
func (m *defaultAiAgentService) RunAgent(ctx context.Context, in *AgentRunReq, opts ...grpc.CallOption) (*AgentRunResp, error) {
	client := pb.NewAiAgentServiceClient(m.cli.Conn())
	return client.RunAgent(ctx, in, opts...)
}

// 查询 Agent 工具调用日志。
func (m *defaultAiAgentService) ListToolCallLog(ctx context.Context, in *ListToolCallLogReq, opts ...grpc.CallOption) (*ListToolCallLogResp, error) {
	client := pb.NewAiAgentServiceClient(m.cli.Conn())
	return client.ListToolCallLog(ctx, in, opts...)
}
