// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package aichatservice

import (
	"context"

	"ai-copilot-platform/ai-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteConversationReq       = pb.DeleteConversationReq
	DeleteMessageReq            = pb.DeleteMessageReq
	Empty                       = pb.Empty
	GetConversationMessagesReq  = pb.GetConversationMessagesReq
	GetConversationMessagesResp = pb.GetConversationMessagesResp
	ListConversationReq         = pb.ListConversationReq
	ListConversationResp        = pb.ListConversationResp
	RagChatReq                  = pb.RagChatReq
	RagChatResp                 = pb.RagChatResp
	RagChatStreamEvent          = pb.RagChatStreamEvent
	UpdateConversationTitleReq  = pb.UpdateConversationTitleReq

	AiChatService interface {
		// 执行普通 RAG 问答，返回完整答案。
		RagChat(ctx context.Context, in *RagChatReq, opts ...grpc.CallOption) (*RagChatResp, error)
		// 执行流式 RAG 问答，逐步返回 token、引用和完成事件。
		RagChatStream(ctx context.Context, in *RagChatReq, opts ...grpc.CallOption) (pb.AiChatService_RagChatStreamClient, error)
		// 查询当前用户的 AI 会话列表。
		ListConversation(ctx context.Context, in *ListConversationReq, opts ...grpc.CallOption) (*ListConversationResp, error)
		// 查询指定会话的消息历史。
		GetConversationMessages(ctx context.Context, in *GetConversationMessagesReq, opts ...grpc.CallOption) (*GetConversationMessagesResp, error)
		UpdateConversationTitle(ctx context.Context, in *UpdateConversationTitleReq, opts ...grpc.CallOption) (*Empty, error)
		DeleteConversation(ctx context.Context, in *DeleteConversationReq, opts ...grpc.CallOption) (*Empty, error)
		DeleteMessage(ctx context.Context, in *DeleteMessageReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultAiChatService struct {
		cli zrpc.Client
	}
)

func NewAiChatService(cli zrpc.Client) AiChatService {
	return &defaultAiChatService{
		cli: cli,
	}
}

// 执行普通 RAG 问答，返回完整答案。
func (m *defaultAiChatService) RagChat(ctx context.Context, in *RagChatReq, opts ...grpc.CallOption) (*RagChatResp, error) {
	client := pb.NewAiChatServiceClient(m.cli.Conn())
	return client.RagChat(ctx, in, opts...)
}

// 执行流式 RAG 问答，逐步返回 token、引用和完成事件。
func (m *defaultAiChatService) RagChatStream(ctx context.Context, in *RagChatReq, opts ...grpc.CallOption) (pb.AiChatService_RagChatStreamClient, error) {
	client := pb.NewAiChatServiceClient(m.cli.Conn())
	return client.RagChatStream(ctx, in, opts...)
}

// 查询当前用户的 AI 会话列表。
func (m *defaultAiChatService) ListConversation(ctx context.Context, in *ListConversationReq, opts ...grpc.CallOption) (*ListConversationResp, error) {
	client := pb.NewAiChatServiceClient(m.cli.Conn())
	return client.ListConversation(ctx, in, opts...)
}

// 查询指定会话的消息历史。
func (m *defaultAiChatService) GetConversationMessages(ctx context.Context, in *GetConversationMessagesReq, opts ...grpc.CallOption) (*GetConversationMessagesResp, error) {
	client := pb.NewAiChatServiceClient(m.cli.Conn())
	return client.GetConversationMessages(ctx, in, opts...)
}

func (m *defaultAiChatService) UpdateConversationTitle(ctx context.Context, in *UpdateConversationTitleReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAiChatServiceClient(m.cli.Conn())
	return client.UpdateConversationTitle(ctx, in, opts...)
}

func (m *defaultAiChatService) DeleteConversation(ctx context.Context, in *DeleteConversationReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAiChatServiceClient(m.cli.Conn())
	return client.DeleteConversation(ctx, in, opts...)
}

func (m *defaultAiChatService) DeleteMessage(ctx context.Context, in *DeleteMessageReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAiChatServiceClient(m.cli.Conn())
	return client.DeleteMessage(ctx, in, opts...)
}
