// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package aiwindagentservice

import (
	"context"

	"ai-copilot-platform/ai-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	WindAgentRunReq         = pb.WindAgentRunReq
	WindAgentRunResp        = pb.WindAgentRunResp
	WindListToolCallLogReq  = pb.WindListToolCallLogReq
	WindListToolCallLogResp = pb.WindListToolCallLogResp
	WindScaffoldResp        = pb.WindScaffoldResp
	WindTicketDraftReq      = pb.WindTicketDraftReq

	AiWindAgentService interface {
		CreateTicketDraft(ctx context.Context, in *WindTicketDraftReq, opts ...grpc.CallOption) (*WindScaffoldResp, error)
		RunAgent(ctx context.Context, in *WindAgentRunReq, opts ...grpc.CallOption) (*WindAgentRunResp, error)
		ListToolCallLog(ctx context.Context, in *WindListToolCallLogReq, opts ...grpc.CallOption) (*WindListToolCallLogResp, error)
	}

	defaultAiWindAgentService struct {
		cli zrpc.Client
	}
)

func NewAiWindAgentService(cli zrpc.Client) AiWindAgentService {
	return &defaultAiWindAgentService{
		cli: cli,
	}
}

func (m *defaultAiWindAgentService) CreateTicketDraft(ctx context.Context, in *WindTicketDraftReq, opts ...grpc.CallOption) (*WindScaffoldResp, error) {
	client := pb.NewAiWindAgentServiceClient(m.cli.Conn())
	return client.CreateTicketDraft(ctx, in, opts...)
}

func (m *defaultAiWindAgentService) RunAgent(ctx context.Context, in *WindAgentRunReq, opts ...grpc.CallOption) (*WindAgentRunResp, error) {
	client := pb.NewAiWindAgentServiceClient(m.cli.Conn())
	return client.RunAgent(ctx, in, opts...)
}

func (m *defaultAiWindAgentService) ListToolCallLog(ctx context.Context, in *WindListToolCallLogReq, opts ...grpc.CallOption) (*WindListToolCallLogResp, error) {
	client := pb.NewAiWindAgentServiceClient(m.cli.Conn())
	return client.ListToolCallLog(ctx, in, opts...)
}
