apiVersion: v1
kind: Service
metadata:
  name: blade-rpc
  namespace: blade
  labels:
    app: blade-rpc
spec:
  type: ClusterIP
  ports:
    - port: 9300
      targetPort: 9300
      protocol: TCP
  selector:
    app: blade-rpc
