// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"context"

	"ai-copilot-platform/ai-rpc/internal/logic/aiwindagentservice"
	"ai-copilot-platform/ai-rpc/internal/svc"
	"ai-copilot-platform/ai-rpc/pb"
)

type AiWindAgentServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiWindAgentServiceServer
}

func NewAiWindAgentServiceServer(svcCtx *svc.ServiceContext) *AiWindAgentServiceServer {
	return &AiWindAgentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AiWindAgentServiceServer) CreateTicketDraft(ctx context.Context, in *pb.WindTicketDraftReq) (*pb.WindScaffoldResp, error) {
	l := aiwindagentservicelogic.NewCreateTicketDraftLogic(ctx, s.svcCtx)
	return l.CreateTicketDraft(in)
}

func (s *AiWindAgentServiceServer) RunAgent(ctx context.Context, in *pb.WindAgentRunReq) (*pb.WindAgentRunResp, error) {
	l := aiwindagentservicelogic.NewRunAgentLogic(ctx, s.svcCtx)
	return l.RunAgent(in)
}

func (s *AiWindAgentServiceServer) ListToolCallLog(ctx context.Context, in *pb.WindListToolCallLogReq) (*pb.WindListToolCallLogResp, error) {
	l := aiwindagentservicelogic.NewListToolCallLogLogic(ctx, s.svcCtx)
	return l.ListToolCallLog(in)
}

func (s *AiWindAgentServiceServer) ExecuteTool(ctx context.Context, in *pb.WindToolExecuteReq) (*pb.WindToolExecuteResp, error) {
	l := aiwindagentservicelogic.NewExecuteToolLogic(ctx, s.svcCtx)
	return l.ExecuteTool(in)
}

func (s *AiWindAgentServiceServer) RunAgentStream(in *pb.WindAgentRunReq, stream pb.AiWindAgentService_RunAgentStreamServer) error {
	l := aiwindagentservicelogic.NewRunAgentStreamLogic(stream.Context(), s.svcCtx)
	return l.RunAgentStream(in, stream)
}

func (s *AiWindAgentServiceServer) ResumeAgentStream(in *pb.WindAgentResumeReq, stream pb.AiWindAgentService_ResumeAgentStreamServer) error {
	l := aiwindagentservicelogic.NewResumeAgentStreamLogic(stream.Context(), s.svcCtx)
	return l.ResumeAgentStream(in, stream)
}
